/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.nvdb.datakatalog.model

import no.vegvesen.nvdb.datakatalog.model.Egenskapstype
import no.vegvesen.nvdb.datakatalog.model.EgenskapstypeEnum
import no.vegvesen.nvdb.datakatalog.model.Viktighet

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param egenskapstype 
 * @param sorteringsnummer 
 * @param avledet 
 * @param obligatoriskVerdi 
 * @param skrivebeskyttet 
 * @param sensitivitet 
 * @param høydereferanseTall 
 * @param nøyaktighetskravGrunnriss 
 * @param nøyaktighetskravHøyde 
 * @param referansegeometriTilstrekkelig 
 * @param viktighet 
 * @param kategori 
 * @param navn 
 * @param komplementærEgenskapstype 
 * @param kortnavn 
 * @param beskrivelse 
 * @param sosinavn 
 * @param sosinvdbnavn 
 * @param gruppesorteringsnummer 
 * @param veiledning 
 * @param grunnrissreferanse 
 * @param høydereferanse 
 * @param sosiReferanse 
 * @param stedfestingstype 
 * @param geometritype 
 * @param overlappOk 
 * @param kjørefeltRelevant 
 * @param sideposisjonRelevant 
 * @param innenforMor 
 * @param vegnettsajourholdSplitt 
 * @param overlappsautomatikk 
 * @param retningRelevant 
 */


data class EgenskapstypeStedfesting (

    @get:JsonProperty("id")
    override val id: kotlin.Int,

    @get:JsonProperty("egenskapstype")
    override val egenskapstype: EgenskapstypeEnum,

    @get:JsonProperty("sorteringsnummer")
    override val sorteringsnummer: kotlin.Int,

    @get:JsonProperty("avledet")
    override val avledet: kotlin.Boolean,

    @get:JsonProperty("obligatorisk_verdi")
    override val obligatoriskVerdi: kotlin.Boolean,

    @get:JsonProperty("skrivebeskyttet")
    override val skrivebeskyttet: kotlin.Boolean,

    @get:JsonProperty("sensitivitet")
    override val sensitivitet: kotlin.Int,

    @get:JsonProperty("høydereferanse_tall")
    override val høydereferanseTall: kotlin.Int,

    @get:JsonProperty("nøyaktighetskrav_grunnriss")
    override val nøyaktighetskravGrunnriss: kotlin.Double,

    @get:JsonProperty("nøyaktighetskrav_høyde")
    override val nøyaktighetskravHøyde: kotlin.Double,

    @get:JsonProperty("referansegeometri_tilstrekkelig")
    override val referansegeometriTilstrekkelig: kotlin.Boolean,

    @get:JsonProperty("viktighet")
    override val viktighet: Viktighet,

    @get:JsonProperty("kategori")
    override val kategori: kotlin.Int,

    @get:JsonProperty("navn")
    override val navn: kotlin.String? = null,

    @get:JsonProperty("komplementær_egenskapstype")
    override val komplementærEgenskapstype: kotlin.Int? = null,

    @get:JsonProperty("kortnavn")
    override val kortnavn: kotlin.String? = null,

    @get:JsonProperty("beskrivelse")
    override val beskrivelse: kotlin.String? = null,

    @get:JsonProperty("sosinavn")
    override val sosinavn: kotlin.String? = null,

    @get:JsonProperty("sosinvdbnavn")
    override val sosinvdbnavn: kotlin.String? = null,

    @get:JsonProperty("gruppesorteringsnummer")
    override val gruppesorteringsnummer: kotlin.Int? = null,

    @get:JsonProperty("veiledning")
    override val veiledning: kotlin.String? = null,

    @get:JsonProperty("grunnrissreferanse")
    override val grunnrissreferanse: kotlin.String? = null,

    @get:JsonProperty("høydereferanse")
    override val høydereferanse: kotlin.String? = null,

    @get:JsonProperty("sosi_referanse")
    override val sosiReferanse: kotlin.String? = null,

    @get:JsonProperty("stedfestingstype")
    val stedfestingstype: EgenskapstypeStedfesting.Stedfestingstype? = null,

    @get:JsonProperty("geometritype")
    val geometritype: EgenskapstypeStedfesting.Geometritype? = null,

    @get:JsonProperty("overlapp_ok")
    val overlappOk: kotlin.Boolean? = null,

    @get:JsonProperty("kjørefelt_relevant")
    val kjørefeltRelevant: EgenskapstypeStedfesting.KjørefeltRelevant? = null,

    @get:JsonProperty("sideposisjon_relevant")
    val sideposisjonRelevant: EgenskapstypeStedfesting.SideposisjonRelevant? = null,

    @get:JsonProperty("innenfor_mor")
    val innenforMor: kotlin.Boolean? = null,

    @get:JsonProperty("vegnettsajourhold_splitt")
    val vegnettsajourholdSplitt: EgenskapstypeStedfesting.VegnettsajourholdSplitt? = null,

    @get:JsonProperty("overlappsautomatikk")
    val overlappsautomatikk: kotlin.String? = null,

    @get:JsonProperty("retning_relevant")
    val retningRelevant: kotlin.Boolean? = null

) : Egenskapstype {

    /**
     * 
     *
     * Values: Punkt,Linje,Sving
     */
    enum class Stedfestingstype(val value: kotlin.String) {
        @JsonProperty(value = "Punkt") Punkt("Punkt"),
        @JsonProperty(value = "Linje") Linje("Linje"),
        @JsonProperty(value = "Sving") Sving("Sving");
    }
    /**
     * 
     *
     * Values: PUNKT,LINJE,SVING
     */
    enum class Geometritype(val value: kotlin.String) {
        @JsonProperty(value = "PUNKT") PUNKT("PUNKT"),
        @JsonProperty(value = "LINJE") LINJE("LINJE"),
        @JsonProperty(value = "SVING") SVING("SVING");
    }
    /**
     * 
     *
     * Values: KAN,NEI,MÅ
     */
    enum class KjørefeltRelevant(val value: kotlin.String) {
        @JsonProperty(value = "KAN") KAN("KAN"),
        @JsonProperty(value = "NEI") NEI("NEI"),
        @JsonProperty(value = "MÅ") MÅ("MÅ");
    }
    /**
     * 
     *
     * Values: KAN,NEI,MÅ
     */
    enum class SideposisjonRelevant(val value: kotlin.String) {
        @JsonProperty(value = "KAN") KAN("KAN"),
        @JsonProperty(value = "NEI") NEI("NEI"),
        @JsonProperty(value = "MÅ") MÅ("MÅ");
    }
    /**
     * 
     *
     * Values: IKKE_TATT_STILLING,KAN_IKKE_SPLITTES,KAN_SPLITTES
     */
    enum class VegnettsajourholdSplitt(val value: kotlin.String) {
        @JsonProperty(value = "IKKE_TATT_STILLING") IKKE_TATT_STILLING("IKKE_TATT_STILLING"),
        @JsonProperty(value = "KAN_IKKE_SPLITTES") KAN_IKKE_SPLITTES("KAN_IKKE_SPLITTES"),
        @JsonProperty(value = "KAN_SPLITTES") KAN_SPLITTES("KAN_SPLITTES");
    }

}

