/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.nvdb.datakatalog.model


import kotlinx.serialization.*

/**
 * 
 *
 * Values: iKKESATT,pÅKREVDABSOLUTT,pÅKREVDIKKEABSOLUTT,bETINGET,oPSJONELL,mINDREVIKTIG,hISTORISK
 */
@Serializable
enum class Viktighet(val value: kotlin.String) {

    @SerialName(value = "IKKE_SATT")
    iKKESATT("IKKE_SATT"),

    @SerialName(value = "PÅKREVD_ABSOLUTT")
    pÅKREVDABSOLUTT("PÅKREVD_ABSOLUTT"),

    @SerialName(value = "PÅKREVD_IKKE_ABSOLUTT")
    pÅKREVDIKKEABSOLUTT("PÅKREVD_IKKE_ABSOLUTT"),

    @SerialName(value = "BETINGET")
    bETINGET("BETINGET"),

    @SerialName(value = "OPSJONELL")
    oPSJONELL("OPSJONELL"),

    @SerialName(value = "MINDRE_VIKTIG")
    mINDREVIKTIG("MINDRE_VIKTIG"),

    @SerialName(value = "HISTORISK")
    hISTORISK("HISTORISK");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is Viktighet) "$data" else null

        /**
         * Returns a valid [Viktighet] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): Viktighet? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

