/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.nvdb.vegobjekter.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param navn 
 * @param kortnavn 
 */


data class Enhet (

    @get:JsonProperty("id")
    val id: kotlin.Int,

    @get:JsonProperty("navn")
    val navn: kotlin.String? = null,

    @get:JsonProperty("kortnavn")
    val kortnavn: kotlin.String? = null

) {


}

