/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.nvdb.vegobjekter.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param retning 
 * @param sideposisjon 
 * @param kjørefelt 
 */
@Serializable

data class MetrertLokasjon (

    @SerialName(value = "retning") val retning: MetrertLokasjon.Retning? = null,

    @SerialName(value = "sideposisjon") val sideposisjon: MetrertLokasjon.Sideposisjon? = null,

    @SerialName(value = "kjørefelt") val kjørefelt: kotlin.collections.List<kotlin.String>? = null

) {

    /**
     * 
     *
     * Values: mED,mOT
     */
    @Serializable
    enum class Retning(val value: kotlin.String) {
        @SerialName(value = "MED") mED("MED"),
        @SerialName(value = "MOT") mOT("MOT");
    }
    /**
     * 
     *
     * Values: mH,mV,vT,m,h,hT,vH,hV,k,v,l,r,r0
     */
    @Serializable
    enum class Sideposisjon(val value: kotlin.String) {
        @SerialName(value = "MH") mH("MH"),
        @SerialName(value = "MV") mV("MV"),
        @SerialName(value = "VT") vT("VT"),
        @SerialName(value = "M") m("M"),
        @SerialName(value = "H") h("H"),
        @SerialName(value = "HT") hT("HT"),
        @SerialName(value = "VH") vH("VH"),
        @SerialName(value = "HV") hV("HV"),
        @SerialName(value = "K") k("K"),
        @SerialName(value = "V") v("V"),
        @SerialName(value = "L") l("L"),
        @SerialName(value = "R") r("R"),
        @SerialName(value = "R0") r0("R0");
    }
}

