/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.nvdb.vegobjekter.model

import no.vegvesen.nvdb.vegobjekter.model.Relasjon
import no.vegvesen.nvdb.vegobjekter.model.Vegobjekt
import no.vegvesen.nvdb.vegobjekter.model.VegobjektType

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param id 
 * @param type 
 * @param relasjonstype 
 * @param vegobjekter 
 * @param listeid 
 */


data class RelasjonMedVegobjekter (

    @get:JsonProperty("id")
    override val id: kotlin.Int,

    @get:JsonProperty("type")
    override val type: VegobjektType,

    @get:JsonProperty("relasjonstype")
    override val relasjonstype: RelasjonMedVegobjekter.Relasjonstype,

    @get:JsonProperty("vegobjekter")
    val vegobjekter: kotlin.collections.List<Vegobjekt>,

    @get:JsonProperty("listeid")
    override val listeid: kotlin.Int? = null

) : Relasjon {


}

