/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.nvdb.vegobjekter.model

import no.vegvesen.nvdb.vegobjekter.model.Geometri
import no.vegvesen.nvdb.vegobjekter.model.Vegsystemreferanse

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param veglenkesekvensid 
 * @param retning 
 * @param veglenkeType 
 * @param detaljnivå 
 * @param typeVeg 
 * @param typeVegSosi 
 * @param startdato 
 * @param geometri 
 * @param kommune 
 * @param fylke 
 * @param startposisjon 
 * @param sluttposisjon 
 * @param relativPosisjon 
 * @param lengde 
 * @param kjørefelt 
 * @param sideposisjon 
 * @param feltoversikt 
 * @param sluttdato 
 * @param vegsystemreferanse 
 * @param kontraktsområder 
 * @param riksvegruter 
 * @param vegforvaltere 
 * @param adresser 
 */


data class Vegsegment (

    @get:JsonProperty("veglenkesekvensid")
    val veglenkesekvensid: kotlin.Long,

    @get:JsonProperty("retning")
    val retning: Vegsegment.Retning,

    @get:JsonProperty("veglenkeType")
    val veglenkeType: Vegsegment.VeglenkeType,

    @get:JsonProperty("detaljnivå")
    val detaljnivå: Vegsegment.Detaljnivå,

    @get:JsonProperty("typeVeg")
    val typeVeg: Vegsegment.TypeVeg,

    @get:JsonProperty("typeVeg_sosi")
    val typeVegSosi: Vegsegment.TypeVegSosi,

    @get:JsonProperty("startdato")
    val startdato: java.time.LocalDate,

    @get:JsonProperty("geometri")
    val geometri: Geometri,

    @get:JsonProperty("kommune")
    val kommune: kotlin.Int,

    @get:JsonProperty("fylke")
    val fylke: kotlin.Int,

    @get:JsonProperty("startposisjon")
    val startposisjon: kotlin.Double? = null,

    @get:JsonProperty("sluttposisjon")
    val sluttposisjon: kotlin.Double? = null,

    @get:JsonProperty("relativPosisjon")
    val relativPosisjon: kotlin.Double? = null,

    @get:JsonProperty("lengde")
    val lengde: kotlin.Double? = null,

    @get:JsonProperty("kjørefelt")
    val kjørefelt: kotlin.collections.List<kotlin.String>? = null,

    @get:JsonProperty("sideposisjon")
    val sideposisjon: Vegsegment.Sideposisjon? = null,

    @get:JsonProperty("feltoversikt")
    val feltoversikt: kotlin.collections.List<kotlin.String>? = null,

    @get:JsonProperty("sluttdato")
    val sluttdato: java.time.LocalDate? = null,

    @get:JsonProperty("vegsystemreferanse")
    val vegsystemreferanse: Vegsystemreferanse? = null,

    @get:JsonProperty("kontraktsområder")
    val kontraktsområder: kotlin.collections.Set<kotlin.Long>? = null,

    @get:JsonProperty("riksvegruter")
    val riksvegruter: kotlin.collections.Set<kotlin.Int>? = null,

    @get:JsonProperty("vegforvaltere")
    val vegforvaltere: kotlin.collections.Set<kotlin.Int>? = null,

    @get:JsonProperty("adresser")
    val adresser: kotlin.collections.Set<kotlin.Long>? = null

) {

    /**
     * 
     *
     * Values: MED,MOT
     */
    enum class Retning(val value: kotlin.String) {
        @JsonProperty(value = "MED") MED("MED"),
        @JsonProperty(value = "MOT") MOT("MOT");
    }
    /**
     * 
     *
     * Values: Ukjent,DETALJERT,KONNEKTERING,DETALJERT_KONNEKTERING,HOVED
     */
    enum class VeglenkeType(val value: kotlin.String) {
        @JsonProperty(value = "Ukjent") Ukjent("Ukjent"),
        @JsonProperty(value = "DETALJERT") DETALJERT("DETALJERT"),
        @JsonProperty(value = "KONNEKTERING") KONNEKTERING("KONNEKTERING"),
        @JsonProperty(value = "DETALJERT_KONNEKTERING") DETALJERT_KONNEKTERING("DETALJERT_KONNEKTERING"),
        @JsonProperty(value = "HOVED") HOVED("HOVED");
    }
    /**
     * 
     *
     * Values: Vegtrase,Kjørebane,Kjørefelt,Vegtrase_og_kjørebane
     */
    enum class Detaljnivå(val value: kotlin.String) {
        @JsonProperty(value = "Vegtrase") Vegtrase("Vegtrase"),
        @JsonProperty(value = "Kjørebane") Kjørebane("Kjørebane"),
        @JsonProperty(value = "Kjørefelt") Kjørefelt("Kjørefelt"),
        @JsonProperty(value = "Vegtrase og kjørebane") Vegtrase_og_kjørebane("Vegtrase og kjørebane");
    }
    /**
     * 
     *
     * Values: Kanalisert_veg,Enkel_bilveg,Rampe,Rundkjøring,Bilferje,Passasjerferje,GangMinus_og_sykkelveg,Sykkelveg,Gangveg,Gågate,Fortau,Trapp,Gangfelt,Gatetun,Traktorveg,Sti,Annet
     */
    enum class TypeVeg(val value: kotlin.String) {
        @JsonProperty(value = "Kanalisert veg") Kanalisert_veg("Kanalisert veg"),
        @JsonProperty(value = "Enkel bilveg") Enkel_bilveg("Enkel bilveg"),
        @JsonProperty(value = "Rampe") Rampe("Rampe"),
        @JsonProperty(value = "Rundkjøring") Rundkjøring("Rundkjøring"),
        @JsonProperty(value = "Bilferje") Bilferje("Bilferje"),
        @JsonProperty(value = "Passasjerferje") Passasjerferje("Passasjerferje"),
        @JsonProperty(value = "Gang- og sykkelveg") GangMinus_og_sykkelveg("Gang- og sykkelveg"),
        @JsonProperty(value = "Sykkelveg") Sykkelveg("Sykkelveg"),
        @JsonProperty(value = "Gangveg") Gangveg("Gangveg"),
        @JsonProperty(value = "Gågate") Gågate("Gågate"),
        @JsonProperty(value = "Fortau") Fortau("Fortau"),
        @JsonProperty(value = "Trapp") Trapp("Trapp"),
        @JsonProperty(value = "Gangfelt") Gangfelt("Gangfelt"),
        @JsonProperty(value = "Gatetun") Gatetun("Gatetun"),
        @JsonProperty(value = "Traktorveg") Traktorveg("Traktorveg"),
        @JsonProperty(value = "Sti") Sti("Sti"),
        @JsonProperty(value = "Annet") Annet("Annet");
    }
    /**
     * 
     *
     * Values: kanalisertVeg,enkelBilveg,rampe,rundkjøring,bilferje,passasjerferje,gangOgSykkelveg,sykkelveg,gangveg,gågate,fortau,trapp,gangfelt,gatetun,traktorveg,sti,annet
     */
    enum class TypeVegSosi(val value: kotlin.String) {
        @JsonProperty(value = "kanalisertVeg") kanalisertVeg("kanalisertVeg"),
        @JsonProperty(value = "enkelBilveg") enkelBilveg("enkelBilveg"),
        @JsonProperty(value = "rampe") rampe("rampe"),
        @JsonProperty(value = "rundkjøring") rundkjøring("rundkjøring"),
        @JsonProperty(value = "bilferje") bilferje("bilferje"),
        @JsonProperty(value = "passasjerferje") passasjerferje("passasjerferje"),
        @JsonProperty(value = "gangOgSykkelveg") gangOgSykkelveg("gangOgSykkelveg"),
        @JsonProperty(value = "sykkelveg") sykkelveg("sykkelveg"),
        @JsonProperty(value = "gangveg") gangveg("gangveg"),
        @JsonProperty(value = "gågate") gågate("gågate"),
        @JsonProperty(value = "fortau") fortau("fortau"),
        @JsonProperty(value = "trapp") trapp("trapp"),
        @JsonProperty(value = "gangfelt") gangfelt("gangfelt"),
        @JsonProperty(value = "gatetun") gatetun("gatetun"),
        @JsonProperty(value = "traktorveg") traktorveg("traktorveg"),
        @JsonProperty(value = "sti") sti("sti"),
        @JsonProperty(value = "annet") annet("annet");
    }
    /**
     * 
     *
     * Values: MH,MV,VT,M,H,HT,VH,HV,K,V,L,R,R0
     */
    enum class Sideposisjon(val value: kotlin.String) {
        @JsonProperty(value = "MH") MH("MH"),
        @JsonProperty(value = "MV") MV("MV"),
        @JsonProperty(value = "VT") VT("VT"),
        @JsonProperty(value = "M") M("M"),
        @JsonProperty(value = "H") H("H"),
        @JsonProperty(value = "HT") HT("HT"),
        @JsonProperty(value = "VH") VH("VH"),
        @JsonProperty(value = "HV") HV("HV"),
        @JsonProperty(value = "K") K("K"),
        @JsonProperty(value = "V") V("V"),
        @JsonProperty(value = "L") L("L"),
        @JsonProperty(value = "R") R("R"),
        @JsonProperty(value = "R0") R0("R0");
    }

}

