/*
 * NVDB Datakatalog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.vegvesen.nvdb.datakatalog.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import no.vegvesen.nvdb.datakatalog.model.Egenskapstype;
import no.vegvesen.nvdb.datakatalog.model.EgenskapstypeEnum;
import no.vegvesen.nvdb.datakatalog.model.Enhet;
import no.vegvesen.nvdb.datakatalog.model.Viktighet;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EgenskapstypeFlyttall
 */
@JsonPropertyOrder({
  EgenskapstypeFlyttall.JSON_PROPERTY_OBJEKTLISTE_DATO,
  EgenskapstypeFlyttall.JSON_PROPERTY_SLUTT_DATO,
  EgenskapstypeFlyttall.JSON_PROPERTY_LENGDEAVHENGIG_VERDI,
  EgenskapstypeFlyttall.JSON_PROPERTY_AJOURHOLD_SNU,
  EgenskapstypeFlyttall.JSON_PROPERTY_STANDARDVERDI,
  EgenskapstypeFlyttall.JSON_PROPERTY_MIN_ANBEFALT,
  EgenskapstypeFlyttall.JSON_PROPERTY_MAKS_ANBEFALT,
  EgenskapstypeFlyttall.JSON_PROPERTY_MIN,
  EgenskapstypeFlyttall.JSON_PROPERTY_MAKS,
  EgenskapstypeFlyttall.JSON_PROPERTY_DESIMALER,
  EgenskapstypeFlyttall.JSON_PROPERTY_FELTLENGDE,
  EgenskapstypeFlyttall.JSON_PROPERTY_FORTEGNSENDRING_SNU,
  EgenskapstypeFlyttall.JSON_PROPERTY_ENHET
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
@JsonIgnoreProperties(
  value = "egenskapstype", // ignore manually set egenskapstype, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the egenskapstype to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "egenskapstype", visible = true)

public class EgenskapstypeFlyttall extends Egenskapstype {
  public static final String JSON_PROPERTY_OBJEKTLISTE_DATO = "objektliste_dato";
  private LocalDate objektlisteDato;

  public static final String JSON_PROPERTY_SLUTT_DATO = "slutt_dato";
  private LocalDate sluttDato;

  public static final String JSON_PROPERTY_LENGDEAVHENGIG_VERDI = "lengdeavhengig_verdi";
  private Boolean lengdeavhengigVerdi;

  public static final String JSON_PROPERTY_AJOURHOLD_SNU = "ajourhold_snu";
  private Boolean ajourholdSnu;

  public static final String JSON_PROPERTY_STANDARDVERDI = "standardverdi";
  private Double standardverdi;

  public static final String JSON_PROPERTY_MIN_ANBEFALT = "min_anbefalt";
  private Double minAnbefalt;

  public static final String JSON_PROPERTY_MAKS_ANBEFALT = "maks_anbefalt";
  private Double maksAnbefalt;

  public static final String JSON_PROPERTY_MIN = "min";
  private Double min;

  public static final String JSON_PROPERTY_MAKS = "maks";
  private Double maks;

  public static final String JSON_PROPERTY_DESIMALER = "desimaler";
  private Integer desimaler;

  public static final String JSON_PROPERTY_FELTLENGDE = "feltlengde";
  private Integer feltlengde;

  public static final String JSON_PROPERTY_FORTEGNSENDRING_SNU = "fortegnsendring_snu";
  private Boolean fortegnsendringSnu;

  public static final String JSON_PROPERTY_ENHET = "enhet";
  private Enhet enhet;

  public EgenskapstypeFlyttall() {

  }

  public EgenskapstypeFlyttall objektlisteDato(LocalDate objektlisteDato) {
    
    this.objektlisteDato = objektlisteDato;
    return this;
  }

   /**
   * Get objektlisteDato
   * @return objektlisteDato
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OBJEKTLISTE_DATO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getObjektlisteDato() {
    return objektlisteDato;
  }


  @JsonProperty(JSON_PROPERTY_OBJEKTLISTE_DATO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObjektlisteDato(LocalDate objektlisteDato) {
    this.objektlisteDato = objektlisteDato;
  }


  public EgenskapstypeFlyttall sluttDato(LocalDate sluttDato) {
    
    this.sluttDato = sluttDato;
    return this;
  }

   /**
   * Get sluttDato
   * @return sluttDato
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SLUTT_DATO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getSluttDato() {
    return sluttDato;
  }


  @JsonProperty(JSON_PROPERTY_SLUTT_DATO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSluttDato(LocalDate sluttDato) {
    this.sluttDato = sluttDato;
  }


  public EgenskapstypeFlyttall lengdeavhengigVerdi(Boolean lengdeavhengigVerdi) {
    
    this.lengdeavhengigVerdi = lengdeavhengigVerdi;
    return this;
  }

   /**
   * Get lengdeavhengigVerdi
   * @return lengdeavhengigVerdi
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LENGDEAVHENGIG_VERDI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getLengdeavhengigVerdi() {
    return lengdeavhengigVerdi;
  }


  @JsonProperty(JSON_PROPERTY_LENGDEAVHENGIG_VERDI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLengdeavhengigVerdi(Boolean lengdeavhengigVerdi) {
    this.lengdeavhengigVerdi = lengdeavhengigVerdi;
  }


  public EgenskapstypeFlyttall ajourholdSnu(Boolean ajourholdSnu) {
    
    this.ajourholdSnu = ajourholdSnu;
    return this;
  }

   /**
   * Get ajourholdSnu
   * @return ajourholdSnu
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AJOURHOLD_SNU)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getAjourholdSnu() {
    return ajourholdSnu;
  }


  @JsonProperty(JSON_PROPERTY_AJOURHOLD_SNU)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAjourholdSnu(Boolean ajourholdSnu) {
    this.ajourholdSnu = ajourholdSnu;
  }


  public EgenskapstypeFlyttall standardverdi(Double standardverdi) {
    
    this.standardverdi = standardverdi;
    return this;
  }

   /**
   * Get standardverdi
   * @return standardverdi
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STANDARDVERDI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getStandardverdi() {
    return standardverdi;
  }


  @JsonProperty(JSON_PROPERTY_STANDARDVERDI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStandardverdi(Double standardverdi) {
    this.standardverdi = standardverdi;
  }


  public EgenskapstypeFlyttall minAnbefalt(Double minAnbefalt) {
    
    this.minAnbefalt = minAnbefalt;
    return this;
  }

   /**
   * Get minAnbefalt
   * @return minAnbefalt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MIN_ANBEFALT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMinAnbefalt() {
    return minAnbefalt;
  }


  @JsonProperty(JSON_PROPERTY_MIN_ANBEFALT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinAnbefalt(Double minAnbefalt) {
    this.minAnbefalt = minAnbefalt;
  }


  public EgenskapstypeFlyttall maksAnbefalt(Double maksAnbefalt) {
    
    this.maksAnbefalt = maksAnbefalt;
    return this;
  }

   /**
   * Get maksAnbefalt
   * @return maksAnbefalt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAKS_ANBEFALT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMaksAnbefalt() {
    return maksAnbefalt;
  }


  @JsonProperty(JSON_PROPERTY_MAKS_ANBEFALT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaksAnbefalt(Double maksAnbefalt) {
    this.maksAnbefalt = maksAnbefalt;
  }


  public EgenskapstypeFlyttall min(Double min) {
    
    this.min = min;
    return this;
  }

   /**
   * Get min
   * @return min
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMin() {
    return min;
  }


  @JsonProperty(JSON_PROPERTY_MIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMin(Double min) {
    this.min = min;
  }


  public EgenskapstypeFlyttall maks(Double maks) {
    
    this.maks = maks;
    return this;
  }

   /**
   * Get maks
   * @return maks
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMaks() {
    return maks;
  }


  @JsonProperty(JSON_PROPERTY_MAKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaks(Double maks) {
    this.maks = maks;
  }


  public EgenskapstypeFlyttall desimaler(Integer desimaler) {
    
    this.desimaler = desimaler;
    return this;
  }

   /**
   * Get desimaler
   * @return desimaler
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESIMALER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDesimaler() {
    return desimaler;
  }


  @JsonProperty(JSON_PROPERTY_DESIMALER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDesimaler(Integer desimaler) {
    this.desimaler = desimaler;
  }


  public EgenskapstypeFlyttall feltlengde(Integer feltlengde) {
    
    this.feltlengde = feltlengde;
    return this;
  }

   /**
   * Get feltlengde
   * @return feltlengde
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FELTLENGDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFeltlengde() {
    return feltlengde;
  }


  @JsonProperty(JSON_PROPERTY_FELTLENGDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFeltlengde(Integer feltlengde) {
    this.feltlengde = feltlengde;
  }


  public EgenskapstypeFlyttall fortegnsendringSnu(Boolean fortegnsendringSnu) {
    
    this.fortegnsendringSnu = fortegnsendringSnu;
    return this;
  }

   /**
   * Get fortegnsendringSnu
   * @return fortegnsendringSnu
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FORTEGNSENDRING_SNU)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getFortegnsendringSnu() {
    return fortegnsendringSnu;
  }


  @JsonProperty(JSON_PROPERTY_FORTEGNSENDRING_SNU)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFortegnsendringSnu(Boolean fortegnsendringSnu) {
    this.fortegnsendringSnu = fortegnsendringSnu;
  }


  public EgenskapstypeFlyttall enhet(Enhet enhet) {
    
    this.enhet = enhet;
    return this;
  }

   /**
   * Get enhet
   * @return enhet
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENHET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Enhet getEnhet() {
    return enhet;
  }


  @JsonProperty(JSON_PROPERTY_ENHET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnhet(Enhet enhet) {
    this.enhet = enhet;
  }

  @Override
  public EgenskapstypeFlyttall id(Integer id) {
    this.setId(id);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall navn(String navn) {
    this.setNavn(navn);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall egenskapstype(EgenskapstypeEnum egenskapstype) {
    this.setEgenskapstype(egenskapstype);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall komplementærEgenskapstype(Integer komplementærEgenskapstype) {
    this.setKomplementærEgenskapstype(komplementærEgenskapstype);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall kortnavn(String kortnavn) {
    this.setKortnavn(kortnavn);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall beskrivelse(String beskrivelse) {
    this.setBeskrivelse(beskrivelse);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall sosinavn(String sosinavn) {
    this.setSosinavn(sosinavn);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall sosinvdbnavn(String sosinvdbnavn) {
    this.setSosinvdbnavn(sosinvdbnavn);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall sorteringsnummer(Integer sorteringsnummer) {
    this.setSorteringsnummer(sorteringsnummer);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall avledet(Boolean avledet) {
    this.setAvledet(avledet);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall obligatoriskVerdi(Boolean obligatoriskVerdi) {
    this.setObligatoriskVerdi(obligatoriskVerdi);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall skrivebeskyttet(Boolean skrivebeskyttet) {
    this.setSkrivebeskyttet(skrivebeskyttet);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall sensitivitet(Integer sensitivitet) {
    this.setSensitivitet(sensitivitet);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall gruppesorteringsnummer(Integer gruppesorteringsnummer) {
    this.setGruppesorteringsnummer(gruppesorteringsnummer);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall veiledning(String veiledning) {
    this.setVeiledning(veiledning);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall grunnrissreferanse(String grunnrissreferanse) {
    this.setGrunnrissreferanse(grunnrissreferanse);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall høydereferanse(String høydereferanse) {
    this.setHøydereferanse(høydereferanse);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall høydereferanseTall(Integer høydereferanseTall) {
    this.setHøydereferanseTall(høydereferanseTall);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall nøyaktighetskravGrunnriss(Double nøyaktighetskravGrunnriss) {
    this.setNøyaktighetskravGrunnriss(nøyaktighetskravGrunnriss);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall nøyaktighetskravHøyde(Double nøyaktighetskravHøyde) {
    this.setNøyaktighetskravHøyde(nøyaktighetskravHøyde);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall sosiReferanse(String sosiReferanse) {
    this.setSosiReferanse(sosiReferanse);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall referansegeometriTilstrekkelig(Boolean referansegeometriTilstrekkelig) {
    this.setReferansegeometriTilstrekkelig(referansegeometriTilstrekkelig);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall viktighet(Viktighet viktighet) {
    this.setViktighet(viktighet);
    return this;
  }

  @Override
  public EgenskapstypeFlyttall kategori(Integer kategori) {
    this.setKategori(kategori);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EgenskapstypeFlyttall egenskapstypeFlyttall = (EgenskapstypeFlyttall) o;
    return Objects.equals(this.objektlisteDato, egenskapstypeFlyttall.objektlisteDato) &&
        Objects.equals(this.sluttDato, egenskapstypeFlyttall.sluttDato) &&
        Objects.equals(this.lengdeavhengigVerdi, egenskapstypeFlyttall.lengdeavhengigVerdi) &&
        Objects.equals(this.ajourholdSnu, egenskapstypeFlyttall.ajourholdSnu) &&
        Objects.equals(this.standardverdi, egenskapstypeFlyttall.standardverdi) &&
        Objects.equals(this.minAnbefalt, egenskapstypeFlyttall.minAnbefalt) &&
        Objects.equals(this.maksAnbefalt, egenskapstypeFlyttall.maksAnbefalt) &&
        Objects.equals(this.min, egenskapstypeFlyttall.min) &&
        Objects.equals(this.maks, egenskapstypeFlyttall.maks) &&
        Objects.equals(this.desimaler, egenskapstypeFlyttall.desimaler) &&
        Objects.equals(this.feltlengde, egenskapstypeFlyttall.feltlengde) &&
        Objects.equals(this.fortegnsendringSnu, egenskapstypeFlyttall.fortegnsendringSnu) &&
        Objects.equals(this.enhet, egenskapstypeFlyttall.enhet) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objektlisteDato, sluttDato, lengdeavhengigVerdi, ajourholdSnu, standardverdi, minAnbefalt, maksAnbefalt, min, maks, desimaler, feltlengde, fortegnsendringSnu, enhet, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EgenskapstypeFlyttall {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    objektlisteDato: ").append(toIndentedString(objektlisteDato)).append("\n");
    sb.append("    sluttDato: ").append(toIndentedString(sluttDato)).append("\n");
    sb.append("    lengdeavhengigVerdi: ").append(toIndentedString(lengdeavhengigVerdi)).append("\n");
    sb.append("    ajourholdSnu: ").append(toIndentedString(ajourholdSnu)).append("\n");
    sb.append("    standardverdi: ").append(toIndentedString(standardverdi)).append("\n");
    sb.append("    minAnbefalt: ").append(toIndentedString(minAnbefalt)).append("\n");
    sb.append("    maksAnbefalt: ").append(toIndentedString(maksAnbefalt)).append("\n");
    sb.append("    min: ").append(toIndentedString(min)).append("\n");
    sb.append("    maks: ").append(toIndentedString(maks)).append("\n");
    sb.append("    desimaler: ").append(toIndentedString(desimaler)).append("\n");
    sb.append("    feltlengde: ").append(toIndentedString(feltlengde)).append("\n");
    sb.append("    fortegnsendringSnu: ").append(toIndentedString(fortegnsendringSnu)).append("\n");
    sb.append("    enhet: ").append(toIndentedString(enhet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

