/*
 * NVDB Datakatalog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.vegvesen.nvdb.datakatalog.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import no.vegvesen.nvdb.datakatalog.model.Egenskapstype;
import no.vegvesen.nvdb.datakatalog.model.Relasjonstyper;
import no.vegvesen.nvdb.datakatalog.model.Stedfesting;
import no.vegvesen.nvdb.datakatalog.model.VegobjektKategori;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Vegobjekttype
 */
@JsonPropertyOrder({
  Vegobjekttype.JSON_PROPERTY_ID,
  Vegobjekttype.JSON_PROPERTY_NAVN,
  Vegobjekttype.JSON_PROPERTY_KORTNAVN,
  Vegobjekttype.JSON_PROPERTY_BESKRIVELSE,
  Vegobjekttype.JSON_PROPERTY_STEDFESTING,
  Vegobjekttype.JSON_PROPERTY_SOSINAVN,
  Vegobjekttype.JSON_PROPERTY_SOSINVDBNAVN,
  Vegobjekttype.JSON_PROPERTY_SORTERINGSNUMMER,
  Vegobjekttype.JSON_PROPERTY_STATUS,
  Vegobjekttype.JSON_PROPERTY_HOVEDKATEGORI,
  Vegobjekttype.JSON_PROPERTY_TIDSROM_RELEVANT,
  Vegobjekttype.JSON_PROPERTY_KONNEKTERINGSLENKE_OK,
  Vegobjekttype.JSON_PROPERTY_ABSTRAKT_TYPE,
  Vegobjekttype.JSON_PROPERTY_AVLEDET,
  Vegobjekttype.JSON_PROPERTY_Må_HA_MOR,
  Vegobjekttype.JSON_PROPERTY_EN_VERSJON,
  Vegobjekttype.JSON_PROPERTY_TILLEGGSINFORMASJON,
  Vegobjekttype.JSON_PROPERTY_KATEGORIER,
  Vegobjekttype.JSON_PROPERTY_EGENSKAPSTYPER,
  Vegobjekttype.JSON_PROPERTY_RELASJONSTYPER,
  Vegobjekttype.JSON_PROPERTY_SENSITIV
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-22T10:51:46.288517Z[Etc/UTC]")
public class Vegobjekttype {
  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_NAVN = "navn";
  private String navn;

  public static final String JSON_PROPERTY_KORTNAVN = "kortnavn";
  private String kortnavn;

  public static final String JSON_PROPERTY_BESKRIVELSE = "beskrivelse";
  private String beskrivelse;

  public static final String JSON_PROPERTY_STEDFESTING = "stedfesting";
  private Stedfesting stedfesting;

  public static final String JSON_PROPERTY_SOSINAVN = "sosinavn";
  private String sosinavn;

  public static final String JSON_PROPERTY_SOSINVDBNAVN = "sosinvdbnavn";
  private String sosinvdbnavn;

  public static final String JSON_PROPERTY_SORTERINGSNUMMER = "sorteringsnummer";
  private Integer sorteringsnummer;

  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_HOVEDKATEGORI = "hovedkategori";
  private String hovedkategori;

  public static final String JSON_PROPERTY_TIDSROM_RELEVANT = "tidsrom_relevant";
  private Boolean tidsromRelevant;

  public static final String JSON_PROPERTY_KONNEKTERINGSLENKE_OK = "konnekteringslenke_ok";
  private Boolean konnekteringslenkeOk;

  public static final String JSON_PROPERTY_ABSTRAKT_TYPE = "abstrakt_type";
  private Boolean abstraktType;

  public static final String JSON_PROPERTY_AVLEDET = "avledet";
  private Boolean avledet;

  public static final String JSON_PROPERTY_Må_HA_MOR = "må_ha_mor";
  private Boolean måHaMor;

  public static final String JSON_PROPERTY_EN_VERSJON = "en_versjon";
  private Boolean enVersjon;

  public static final String JSON_PROPERTY_TILLEGGSINFORMASJON = "tilleggsinformasjon";
  private String tilleggsinformasjon;

  public static final String JSON_PROPERTY_KATEGORIER = "kategorier";
  private List<VegobjektKategori> kategorier = new ArrayList<>();

  public static final String JSON_PROPERTY_EGENSKAPSTYPER = "egenskapstyper";
  private List<Egenskapstype> egenskapstyper;

  public static final String JSON_PROPERTY_RELASJONSTYPER = "relasjonstyper";
  private Relasjonstyper relasjonstyper;

  public static final String JSON_PROPERTY_SENSITIV = "sensitiv";
  private Boolean sensitiv;

  public Vegobjekttype() {
  }

  public Vegobjekttype id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(Integer id) {
    this.id = id;
  }


  public Vegobjekttype navn(String navn) {
    
    this.navn = navn;
    return this;
  }

   /**
   * Get navn
   * @return navn
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAVN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNavn() {
    return navn;
  }


  @JsonProperty(JSON_PROPERTY_NAVN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNavn(String navn) {
    this.navn = navn;
  }


  public Vegobjekttype kortnavn(String kortnavn) {
    
    this.kortnavn = kortnavn;
    return this;
  }

   /**
   * Get kortnavn
   * @return kortnavn
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KORTNAVN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKortnavn() {
    return kortnavn;
  }


  @JsonProperty(JSON_PROPERTY_KORTNAVN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKortnavn(String kortnavn) {
    this.kortnavn = kortnavn;
  }


  public Vegobjekttype beskrivelse(String beskrivelse) {
    
    this.beskrivelse = beskrivelse;
    return this;
  }

   /**
   * Get beskrivelse
   * @return beskrivelse
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BESKRIVELSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBeskrivelse() {
    return beskrivelse;
  }


  @JsonProperty(JSON_PROPERTY_BESKRIVELSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBeskrivelse(String beskrivelse) {
    this.beskrivelse = beskrivelse;
  }


  public Vegobjekttype stedfesting(Stedfesting stedfesting) {
    
    this.stedfesting = stedfesting;
    return this;
  }

   /**
   * Get stedfesting
   * @return stedfesting
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STEDFESTING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Stedfesting getStedfesting() {
    return stedfesting;
  }


  @JsonProperty(JSON_PROPERTY_STEDFESTING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStedfesting(Stedfesting stedfesting) {
    this.stedfesting = stedfesting;
  }


  public Vegobjekttype sosinavn(String sosinavn) {
    
    this.sosinavn = sosinavn;
    return this;
  }

   /**
   * Get sosinavn
   * @return sosinavn
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOSINAVN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSosinavn() {
    return sosinavn;
  }


  @JsonProperty(JSON_PROPERTY_SOSINAVN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSosinavn(String sosinavn) {
    this.sosinavn = sosinavn;
  }


  public Vegobjekttype sosinvdbnavn(String sosinvdbnavn) {
    
    this.sosinvdbnavn = sosinvdbnavn;
    return this;
  }

   /**
   * Get sosinvdbnavn
   * @return sosinvdbnavn
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOSINVDBNAVN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSosinvdbnavn() {
    return sosinvdbnavn;
  }


  @JsonProperty(JSON_PROPERTY_SOSINVDBNAVN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSosinvdbnavn(String sosinvdbnavn) {
    this.sosinvdbnavn = sosinvdbnavn;
  }


  public Vegobjekttype sorteringsnummer(Integer sorteringsnummer) {
    
    this.sorteringsnummer = sorteringsnummer;
    return this;
  }

   /**
   * Get sorteringsnummer
   * @return sorteringsnummer
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SORTERINGSNUMMER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSorteringsnummer() {
    return sorteringsnummer;
  }


  @JsonProperty(JSON_PROPERTY_SORTERINGSNUMMER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSorteringsnummer(Integer sorteringsnummer) {
    this.sorteringsnummer = sorteringsnummer;
  }


  public Vegobjekttype status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(String status) {
    this.status = status;
  }


  public Vegobjekttype hovedkategori(String hovedkategori) {
    
    this.hovedkategori = hovedkategori;
    return this;
  }

   /**
   * Get hovedkategori
   * @return hovedkategori
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HOVEDKATEGORI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHovedkategori() {
    return hovedkategori;
  }


  @JsonProperty(JSON_PROPERTY_HOVEDKATEGORI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHovedkategori(String hovedkategori) {
    this.hovedkategori = hovedkategori;
  }


  public Vegobjekttype tidsromRelevant(Boolean tidsromRelevant) {
    
    this.tidsromRelevant = tidsromRelevant;
    return this;
  }

   /**
   * Get tidsromRelevant
   * @return tidsromRelevant
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TIDSROM_RELEVANT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getTidsromRelevant() {
    return tidsromRelevant;
  }


  @JsonProperty(JSON_PROPERTY_TIDSROM_RELEVANT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTidsromRelevant(Boolean tidsromRelevant) {
    this.tidsromRelevant = tidsromRelevant;
  }


  public Vegobjekttype konnekteringslenkeOk(Boolean konnekteringslenkeOk) {
    
    this.konnekteringslenkeOk = konnekteringslenkeOk;
    return this;
  }

   /**
   * Get konnekteringslenkeOk
   * @return konnekteringslenkeOk
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KONNEKTERINGSLENKE_OK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getKonnekteringslenkeOk() {
    return konnekteringslenkeOk;
  }


  @JsonProperty(JSON_PROPERTY_KONNEKTERINGSLENKE_OK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKonnekteringslenkeOk(Boolean konnekteringslenkeOk) {
    this.konnekteringslenkeOk = konnekteringslenkeOk;
  }


  public Vegobjekttype abstraktType(Boolean abstraktType) {
    
    this.abstraktType = abstraktType;
    return this;
  }

   /**
   * Get abstraktType
   * @return abstraktType
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ABSTRAKT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getAbstraktType() {
    return abstraktType;
  }


  @JsonProperty(JSON_PROPERTY_ABSTRAKT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAbstraktType(Boolean abstraktType) {
    this.abstraktType = abstraktType;
  }


  public Vegobjekttype avledet(Boolean avledet) {
    
    this.avledet = avledet;
    return this;
  }

   /**
   * Get avledet
   * @return avledet
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AVLEDET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getAvledet() {
    return avledet;
  }


  @JsonProperty(JSON_PROPERTY_AVLEDET)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAvledet(Boolean avledet) {
    this.avledet = avledet;
  }


  public Vegobjekttype måHaMor(Boolean måHaMor) {
    
    this.måHaMor = måHaMor;
    return this;
  }

   /**
   * Get måHaMor
   * @return måHaMor
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_Må_HA_MOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getMåHaMor() {
    return måHaMor;
  }


  @JsonProperty(JSON_PROPERTY_Må_HA_MOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMåHaMor(Boolean måHaMor) {
    this.måHaMor = måHaMor;
  }


  public Vegobjekttype enVersjon(Boolean enVersjon) {
    
    this.enVersjon = enVersjon;
    return this;
  }

   /**
   * Get enVersjon
   * @return enVersjon
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EN_VERSJON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getEnVersjon() {
    return enVersjon;
  }


  @JsonProperty(JSON_PROPERTY_EN_VERSJON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEnVersjon(Boolean enVersjon) {
    this.enVersjon = enVersjon;
  }


  public Vegobjekttype tilleggsinformasjon(String tilleggsinformasjon) {
    
    this.tilleggsinformasjon = tilleggsinformasjon;
    return this;
  }

   /**
   * Get tilleggsinformasjon
   * @return tilleggsinformasjon
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TILLEGGSINFORMASJON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTilleggsinformasjon() {
    return tilleggsinformasjon;
  }


  @JsonProperty(JSON_PROPERTY_TILLEGGSINFORMASJON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTilleggsinformasjon(String tilleggsinformasjon) {
    this.tilleggsinformasjon = tilleggsinformasjon;
  }


  public Vegobjekttype kategorier(List<VegobjektKategori> kategorier) {
    
    this.kategorier = kategorier;
    return this;
  }

  public Vegobjekttype addKategorierItem(VegobjektKategori kategorierItem) {
    if (this.kategorier == null) {
      this.kategorier = new ArrayList<>();
    }
    this.kategorier.add(kategorierItem);
    return this;
  }

   /**
   * Get kategorier
   * @return kategorier
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_KATEGORIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<VegobjektKategori> getKategorier() {
    return kategorier;
  }


  @JsonProperty(JSON_PROPERTY_KATEGORIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKategorier(List<VegobjektKategori> kategorier) {
    this.kategorier = kategorier;
  }


  public Vegobjekttype egenskapstyper(List<Egenskapstype> egenskapstyper) {
    
    this.egenskapstyper = egenskapstyper;
    return this;
  }

  public Vegobjekttype addEgenskapstyperItem(Egenskapstype egenskapstyperItem) {
    if (this.egenskapstyper == null) {
      this.egenskapstyper = new ArrayList<>();
    }
    this.egenskapstyper.add(egenskapstyperItem);
    return this;
  }

   /**
   * Get egenskapstyper
   * @return egenskapstyper
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EGENSKAPSTYPER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Egenskapstype> getEgenskapstyper() {
    return egenskapstyper;
  }


  @JsonProperty(JSON_PROPERTY_EGENSKAPSTYPER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEgenskapstyper(List<Egenskapstype> egenskapstyper) {
    this.egenskapstyper = egenskapstyper;
  }


  public Vegobjekttype relasjonstyper(Relasjonstyper relasjonstyper) {
    
    this.relasjonstyper = relasjonstyper;
    return this;
  }

   /**
   * Get relasjonstyper
   * @return relasjonstyper
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELASJONSTYPER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Relasjonstyper getRelasjonstyper() {
    return relasjonstyper;
  }


  @JsonProperty(JSON_PROPERTY_RELASJONSTYPER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelasjonstyper(Relasjonstyper relasjonstyper) {
    this.relasjonstyper = relasjonstyper;
  }


  public Vegobjekttype sensitiv(Boolean sensitiv) {
    
    this.sensitiv = sensitiv;
    return this;
  }

   /**
   * Get sensitiv
   * @return sensitiv
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SENSITIV)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getSensitiv() {
    return sensitiv;
  }


  @JsonProperty(JSON_PROPERTY_SENSITIV)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSensitiv(Boolean sensitiv) {
    this.sensitiv = sensitiv;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Vegobjekttype vegobjekttype = (Vegobjekttype) o;
    return Objects.equals(this.id, vegobjekttype.id) &&
        Objects.equals(this.navn, vegobjekttype.navn) &&
        Objects.equals(this.kortnavn, vegobjekttype.kortnavn) &&
        Objects.equals(this.beskrivelse, vegobjekttype.beskrivelse) &&
        Objects.equals(this.stedfesting, vegobjekttype.stedfesting) &&
        Objects.equals(this.sosinavn, vegobjekttype.sosinavn) &&
        Objects.equals(this.sosinvdbnavn, vegobjekttype.sosinvdbnavn) &&
        Objects.equals(this.sorteringsnummer, vegobjekttype.sorteringsnummer) &&
        Objects.equals(this.status, vegobjekttype.status) &&
        Objects.equals(this.hovedkategori, vegobjekttype.hovedkategori) &&
        Objects.equals(this.tidsromRelevant, vegobjekttype.tidsromRelevant) &&
        Objects.equals(this.konnekteringslenkeOk, vegobjekttype.konnekteringslenkeOk) &&
        Objects.equals(this.abstraktType, vegobjekttype.abstraktType) &&
        Objects.equals(this.avledet, vegobjekttype.avledet) &&
        Objects.equals(this.måHaMor, vegobjekttype.måHaMor) &&
        Objects.equals(this.enVersjon, vegobjekttype.enVersjon) &&
        Objects.equals(this.tilleggsinformasjon, vegobjekttype.tilleggsinformasjon) &&
        Objects.equals(this.kategorier, vegobjekttype.kategorier) &&
        Objects.equals(this.egenskapstyper, vegobjekttype.egenskapstyper) &&
        Objects.equals(this.relasjonstyper, vegobjekttype.relasjonstyper) &&
        Objects.equals(this.sensitiv, vegobjekttype.sensitiv);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, navn, kortnavn, beskrivelse, stedfesting, sosinavn, sosinvdbnavn, sorteringsnummer, status, hovedkategori, tidsromRelevant, konnekteringslenkeOk, abstraktType, avledet, måHaMor, enVersjon, tilleggsinformasjon, kategorier, egenskapstyper, relasjonstyper, sensitiv);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Vegobjekttype {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    kortnavn: ").append(toIndentedString(kortnavn)).append("\n");
    sb.append("    beskrivelse: ").append(toIndentedString(beskrivelse)).append("\n");
    sb.append("    stedfesting: ").append(toIndentedString(stedfesting)).append("\n");
    sb.append("    sosinavn: ").append(toIndentedString(sosinavn)).append("\n");
    sb.append("    sosinvdbnavn: ").append(toIndentedString(sosinvdbnavn)).append("\n");
    sb.append("    sorteringsnummer: ").append(toIndentedString(sorteringsnummer)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    hovedkategori: ").append(toIndentedString(hovedkategori)).append("\n");
    sb.append("    tidsromRelevant: ").append(toIndentedString(tidsromRelevant)).append("\n");
    sb.append("    konnekteringslenkeOk: ").append(toIndentedString(konnekteringslenkeOk)).append("\n");
    sb.append("    abstraktType: ").append(toIndentedString(abstraktType)).append("\n");
    sb.append("    avledet: ").append(toIndentedString(avledet)).append("\n");
    sb.append("    måHaMor: ").append(toIndentedString(måHaMor)).append("\n");
    sb.append("    enVersjon: ").append(toIndentedString(enVersjon)).append("\n");
    sb.append("    tilleggsinformasjon: ").append(toIndentedString(tilleggsinformasjon)).append("\n");
    sb.append("    kategorier: ").append(toIndentedString(kategorier)).append("\n");
    sb.append("    egenskapstyper: ").append(toIndentedString(egenskapstyper)).append("\n");
    sb.append("    relasjonstyper: ").append(toIndentedString(relasjonstyper)).append("\n");
    sb.append("    sensitiv: ").append(toIndentedString(sensitiv)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

