/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Egenskapstype } from './Egenskapstype.ts'
import type { EgenskapstypeEnum } from './EgenskapstypeEnum.ts'
import type { Viktighet } from './Viktighet.ts'

export type EgenskapstypeAssosiasjon = (Egenskapstype & {
  egenskapstype: 'Assosiasjon'
}) & {
  /**
   * @type integer | undefined, int32
   */
  tilknytning?: number
  /**
   * @type integer | undefined, int32
   */
  vegobjekttypeid?: number
  /**
   * @type integer | undefined, int32
   */
  innenfor_mor?: number
  /**
   * @type string | undefined, date
   */
  startdato?: string
  /**
   * @type string | undefined, date
   */
  sluttdato?: string
  /**
   * @type integer | undefined, int32
   */
  assosiasjonskrav?: number
  /**
   * @type string | undefined
   */
  assosiasjonskravkommentar?: string
  /**
   * @type boolean
   */
  avledet: boolean
  /**
   * @type string
   */
  egenskapstype: EgenskapstypeEnum
  /**
   * @type integer, int32
   */
  høydereferanse_tall: number
  /**
   * @type integer, int32
   */
  id: number
  /**
   * @type integer, int32
   */
  kategori: number
  /**
   * @type number, double
   */
  nøyaktighetskrav_grunnriss: number
  /**
   * @type number, double
   */
  nøyaktighetskrav_høyde: number
  /**
   * @type boolean
   */
  obligatorisk_verdi: boolean
  /**
   * @type boolean
   */
  referansegeometri_tilstrekkelig: boolean
  /**
   * @type integer, int32
   */
  sensitivitet: number
  /**
   * @type boolean
   */
  skrivebeskyttet: boolean
  /**
   * @type integer, int32
   */
  sorteringsnummer: number
  /**
   * @type string
   */
  viktighet: Viktighet
}
