/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Egenskapstype } from './Egenskapstype.ts'
import type { ProblemDetail } from './ProblemDetail.ts'

export type GetEgenskapstypeForVegobjekttypePathParams = {
  /**
   * @type integer, int32
   */
  vegobjekttypeid: number
  /**
   * @type integer, int32
   */
  egenskapstypeid: number
}

/**
 * @description OK
 */
export type GetEgenskapstypeForVegobjekttype200 = Egenskapstype

/**
 * @description Not Found
 */
export type GetEgenskapstypeForVegobjekttype404 = ProblemDetail

/**
 * @description Internal Server Error
 */
export type GetEgenskapstypeForVegobjekttype500 = ProblemDetail

/**
 * @description Service Unavailable
 */
export type GetEgenskapstypeForVegobjekttype503 = ProblemDetail

export type GetEgenskapstypeForVegobjekttypeQueryResponse =
  GetEgenskapstypeForVegobjekttype200

export type GetEgenskapstypeForVegobjekttypeQuery = {
  Response: GetEgenskapstypeForVegobjekttype200
  PathParams: GetEgenskapstypeForVegobjekttypePathParams
  Errors:
    | GetEgenskapstypeForVegobjekttype404
    | GetEgenskapstypeForVegobjekttype500
    | GetEgenskapstypeForVegobjekttype503
}
