/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Example } from './Example.ts'
import type { RegistrationConstraint } from './RegistrationConstraint.ts'

export type ProductSpecification = {
  /**
   * @type string | undefined
   */
  url?: string
  /**
   * @type array
   */
  registrationConstraints: RegistrationConstraint[]
  /**
   * @type array
   */
  examples: Example[]
}
