/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.nvdb.vegnett.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param maksAvstand 
 * @param omkrets 
 * @param konnekteringslenker 
 * @param detaljerteLenker 
 * @param kortform 
 * @param beholdTrafikantgruppe 
 * @param start 
 * @param slutt 
 * @param geometri 
 * @param vegsystemreferanse 
 * @param trafikantgruppe 
 * @param typeveg 
 * @param tidspunkt 
 * @param srid 
 */


data class FinnRuteParameters (

    @get:JsonProperty("maks_avstand")
    val maksAvstand: kotlin.Int,

    @get:JsonProperty("omkrets")
    val omkrets: kotlin.Int,

    @get:JsonProperty("konnekteringslenker")
    val konnekteringslenker: kotlin.Boolean,

    @get:JsonProperty("detaljerte_lenker")
    val detaljerteLenker: kotlin.Boolean,

    @get:JsonProperty("kortform")
    val kortform: kotlin.Boolean,

    @get:JsonProperty("behold_trafikantgruppe")
    val beholdTrafikantgruppe: kotlin.Boolean,

    @get:JsonProperty("start")
    val start: kotlin.String? = null,

    @get:JsonProperty("slutt")
    val slutt: kotlin.String? = null,

    @get:JsonProperty("geometri")
    val geometri: kotlin.String? = null,

    @get:JsonProperty("vegsystemreferanse")
    val vegsystemreferanse: kotlin.collections.Set<kotlin.String>? = null,

    @get:JsonProperty("trafikantgruppe")
    val trafikantgruppe: FinnRuteParameters.Trafikantgruppe? = null,

    @get:JsonProperty("typeveg")
    val typeveg: kotlin.collections.Set<FinnRuteParameters.Typeveg>? = null,

    @get:JsonProperty("tidspunkt")
    val tidspunkt: java.time.LocalDate? = null,

    @get:JsonProperty("srid")
    val srid: FinnRuteParameters.Srid? = null

) {

    /**
     * 
     *
     * Values: K,G
     */
    enum class Trafikantgruppe(val value: kotlin.String) {
        @JsonProperty(value = "K") K("K"),
        @JsonProperty(value = "G") G("G");
    }
    /**
     * 
     *
     * Values: Enkel_bilveg,Kanalisert_veg,Rampe,Rundkjøring,Bilferje,GangMinus_og_sykkelveg,Sykkelveg,Gangveg,Gågate,Fortau,Trapp,Gangfelt,Gatetun,Passasjerferje,Traktorveg,Sti,Annet
     */
    enum class Typeveg(val value: kotlin.String) {
        @JsonProperty(value = "Enkel bilveg") Enkel_bilveg("Enkel bilveg"),
        @JsonProperty(value = "Kanalisert veg") Kanalisert_veg("Kanalisert veg"),
        @JsonProperty(value = "Rampe") Rampe("Rampe"),
        @JsonProperty(value = "Rundkjøring") Rundkjøring("Rundkjøring"),
        @JsonProperty(value = "Bilferje") Bilferje("Bilferje"),
        @JsonProperty(value = "Gang- og sykkelveg") GangMinus_og_sykkelveg("Gang- og sykkelveg"),
        @JsonProperty(value = "Sykkelveg") Sykkelveg("Sykkelveg"),
        @JsonProperty(value = "Gangveg") Gangveg("Gangveg"),
        @JsonProperty(value = "Gågate") Gågate("Gågate"),
        @JsonProperty(value = "Fortau") Fortau("Fortau"),
        @JsonProperty(value = "Trapp") Trapp("Trapp"),
        @JsonProperty(value = "Gangfelt") Gangfelt("Gangfelt"),
        @JsonProperty(value = "Gatetun") Gatetun("Gatetun"),
        @JsonProperty(value = "Passasjerferje") Passasjerferje("Passasjerferje"),
        @JsonProperty(value = "Traktorveg") Traktorveg("Traktorveg"),
        @JsonProperty(value = "Sti") Sti("Sti"),
        @JsonProperty(value = "Annet") Annet("Annet");
    }
    /**
     * 
     *
     * Values: _5972,_5973,_5975,_4326,UTM32,UTM33,UTM35,WGS84
     */
    enum class Srid(val value: kotlin.String) {
        @JsonProperty(value = "5972") _5972("5972"),
        @JsonProperty(value = "5973") _5973("5973"),
        @JsonProperty(value = "5975") _5975("5975"),
        @JsonProperty(value = "4326") _4326("4326"),
        @JsonProperty(value = "UTM32") UTM32("UTM32"),
        @JsonProperty(value = "UTM33") UTM33("UTM33"),
        @JsonProperty(value = "UTM35") UTM35("UTM35"),
        @JsonProperty(value = "WGS84") WGS84("WGS84");
    }

}

