/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.nvdb.vegnett.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param målemetode 
 * @param datafangstmetode 
 * @param nøyaktighet 
 * @param målemetodeHøyde 
 * @param datafangstmetodeHøyde 
 * @param nøyaktighetHøyde 
 * @param maksimaltAvvik 
 * @param synbarhet 
 */


data class Kvalitet (

    @get:JsonProperty("målemetode")
    val målemetode: kotlin.Int? = null,

    @get:JsonProperty("datafangstmetode")
    val datafangstmetode: kotlin.String? = null,

    @get:JsonProperty("nøyaktighet")
    val nøyaktighet: kotlin.Int? = null,

    @get:JsonProperty("målemetodeHøyde")
    val målemetodeHøyde: kotlin.Int? = null,

    @get:JsonProperty("datafangstmetodeHøyde")
    val datafangstmetodeHøyde: kotlin.String? = null,

    @get:JsonProperty("nøyaktighetHøyde")
    val nøyaktighetHøyde: kotlin.Int? = null,

    @get:JsonProperty("maksimaltAvvik")
    val maksimaltAvvik: kotlin.Int? = null,

    @get:JsonProperty("synbarhet")
    val synbarhet: kotlin.Int? = null

) {


}

