/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.nvdb.vegnett.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param målemetode 
 * @param datafangstmetode 
 * @param nøyaktighet 
 * @param målemetodeHøyde 
 * @param datafangstmetodeHøyde 
 * @param nøyaktighetHøyde 
 * @param maksimaltAvvik 
 * @param synbarhet 
 */
@Serializable

data class Kvalitet (

    @SerialName(value = "målemetode") val målemetode: kotlin.Int? = null,

    @SerialName(value = "datafangstmetode") val datafangstmetode: kotlin.String? = null,

    @SerialName(value = "nøyaktighet") val nøyaktighet: kotlin.Int? = null,

    @SerialName(value = "målemetodeHøyde") val målemetodeHøyde: kotlin.Int? = null,

    @SerialName(value = "datafangstmetodeHøyde") val datafangstmetodeHøyde: kotlin.String? = null,

    @SerialName(value = "nøyaktighetHøyde") val nøyaktighetHøyde: kotlin.Int? = null,

    @SerialName(value = "maksimaltAvvik") val maksimaltAvvik: kotlin.Int? = null,

    @SerialName(value = "synbarhet") val synbarhet: kotlin.Int? = null

) {


}

