/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.nvdb.vegnett.model

import no.vegvesen.nvdb.vegnett.model.Node
import no.vegvesen.nvdb.vegnett.model.SideMetadata

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param objekter 
 * @param metadata 
 */
@Serializable

data class NodeSide (

    @SerialName(value = "objekter") @Required val objekter: kotlin.collections.List<Node>,

    @SerialName(value = "metadata") @Required val metadata: SideMetadata

)

