/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.nvdb.vegnett.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param type 
 * @param title 
 * @param status 
 * @param detail 
 * @param instance 
 * @param properties 
 */


data class ProblemDetail (

    @get:JsonProperty("type")
    val type: java.net.URI? = null,

    @get:JsonProperty("title")
    val title: kotlin.String? = null,

    @get:JsonProperty("status")
    val status: kotlin.Int? = null,

    @get:JsonProperty("detail")
    val detail: kotlin.String? = null,

    @get:JsonProperty("instance")
    val instance: java.net.URI? = null,

    @get:JsonProperty("properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

