/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.nvdb.vegnett.model

import no.vegvesen.nvdb.vegnett.model.RuteMetadata
import no.vegvesen.nvdb.vegnett.model.Rutesegment

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param vegnettsrutesegmenter 
 * @param metadata 
 */


data class Rute (

    @get:JsonProperty("vegnettsrutesegmenter")
    val vegnettsrutesegmenter: kotlin.collections.List<Rutesegment>,

    @get:JsonProperty("metadata")
    val metadata: RuteMetadata

) {


}

