/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.nvdb.vegnett.model


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param veglenkesekvensid 
 * @param startposisjon 
 * @param sluttposisjon 
 * @param retning 
 * @param kjørefelt 
 * @param sideposisjon 
 */


data class Superstedfesting (

    @get:JsonProperty("veglenkesekvensid")
    val veglenkesekvensid: kotlin.Long,

    @get:JsonProperty("startposisjon")
    val startposisjon: kotlin.Double,

    @get:JsonProperty("sluttposisjon")
    val sluttposisjon: kotlin.Double,

    @get:JsonProperty("retning")
    val retning: Superstedfesting.Retning,

    @get:JsonProperty("kjørefelt")
    val kjørefelt: kotlin.collections.List<kotlin.String>,

    @get:JsonProperty("sideposisjon")
    val sideposisjon: Superstedfesting.Sideposisjon? = null

) {

    /**
     * 
     *
     * Values: MED,MOT
     */
    enum class Retning(val value: kotlin.String) {
        @JsonProperty(value = "MED") MED("MED"),
        @JsonProperty(value = "MOT") MOT("MOT");
    }
    /**
     * 
     *
     * Values: MH,MV,VT,M,H,HT,VH,HV,K,V,L,R,R0
     */
    enum class Sideposisjon(val value: kotlin.String) {
        @JsonProperty(value = "MH") MH("MH"),
        @JsonProperty(value = "MV") MV("MV"),
        @JsonProperty(value = "VT") VT("VT"),
        @JsonProperty(value = "M") M("M"),
        @JsonProperty(value = "H") H("H"),
        @JsonProperty(value = "HT") HT("HT"),
        @JsonProperty(value = "VH") VH("VH"),
        @JsonProperty(value = "HV") HV("HV"),
        @JsonProperty(value = "K") K("K"),
        @JsonProperty(value = "V") V("V"),
        @JsonProperty(value = "L") L("L"),
        @JsonProperty(value = "R") R("R"),
        @JsonProperty(value = "R0") R0("R0");
    }

}

