/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.nvdb.vegnett.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param antall 
 * @param fylke 
 * @param vegkategori 
 */
@Serializable

data class VeglenkesegmenterStatistikkGruppert (

    @SerialName(value = "antall") @Required val antall: kotlin.Int,

    @SerialName(value = "fylke") val fylke: kotlin.Int? = null,

    @SerialName(value = "vegkategori") val vegkategori: VeglenkesegmenterStatistikkGruppert.Vegkategori? = null

) {

    /**
     * 
     *
     * Values: e,f,k,p,r,s
     */
    @Serializable
    enum class Vegkategori(val value: kotlin.String) {
        @SerialName(value = "E") e("E"),
        @SerialName(value = "F") f("F"),
        @SerialName(value = "K") k("K"),
        @SerialName(value = "P") p("P"),
        @SerialName(value = "R") r("R"),
        @SerialName(value = "S") s("S");
    }
}

