/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.nvdb.vegnett.model

import no.vegvesen.nvdb.vegnett.model.Kryssystem
import no.vegvesen.nvdb.vegnett.model.Sideanlegg
import no.vegvesen.nvdb.vegnett.model.Strekning
import no.vegvesen.nvdb.vegnett.model.Vegsystem

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param vegsystem 
 * @param strekning 
 * @param kryssystem 
 * @param sideanlegg 
 * @param kortform 
 */


data class Vegsystemreferanse (

    @get:JsonProperty("vegsystem")
    val vegsystem: Vegsystem? = null,

    @get:JsonProperty("strekning")
    val strekning: Strekning? = null,

    @get:JsonProperty("kryssystem")
    val kryssystem: Kryssystem? = null,

    @get:JsonProperty("sideanlegg")
    val sideanlegg: Sideanlegg? = null,

    @get:JsonProperty("kortform")
    val kortform: kotlin.String? = null

) {


}

