/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Egenskap } from './Egenskap.ts'
import type { Egenskapstype } from './Egenskapstype.ts'

export type BinaerEgenskap = (Egenskap & {
  egenskapstype: 'Bin\u00E6r'
}) & {
  /**
   * @type integer | undefined, int32
   */
  blob_id?: number
  /**
   * @type string | undefined
   */
  blob_format?: string
  /**
   * @type string | undefined
   */
  href?: string
  /**
   * @type string
   */
  egenskapstype: Egenskapstype
  /**
   * @type integer, int32
   */
  id: number
  /**
   * @type string
   */
  navn: string
}
