/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { InkluderGeometri } from './InkluderGeometri.ts'
import type { InkluderIEgenskaper } from './InkluderIEgenskaper.ts'
import type { InkluderIVegobjekt } from './InkluderIVegobjekt.ts'
import type { ProblemDetail } from './ProblemDetail.ts'
import type { SridParameter } from './SridParameter.ts'
import type { Vegobjekt } from './Vegobjekt.ts'

export type GetVegobjektByTypeAndIdPathParams = {
  /**
   * @description Finn vegobjekter med denne vegobjekttypen. Se [Datakatalogen](https://datakatalogen.atlas.vegvesen.no) for mulige verdier.\n\nEksempel: 581\n
   * @type integer, int32
   */
  vegobjekttypeId: number
  /**
   * @type integer, int64
   */
  vegobjektId: number
}

export type GetVegobjektByTypeAndIdQueryParams = {
  /**
   * @description Kommaseparert liste over hvilke informasjonselementer som skal returneres i tillegg til vegobjektenes ID.
   * @type array | undefined
   */
  inkluder?: InkluderIVegobjekt[]
  /**
   * @description Angir hvilket geografisk referansesystem geometrien skal returneres i. Utdata i UTM-formater begrenses til 3 desimaler, 4326/WGS84 begrenses til 8 desimaler. Query-parametere med koordinater oppgis i UTM33 for UTM-formater, 4326/WGS84 oppgis dersom srid er 4326/WGS84. Mer informasjon: <a href=\'https://epsg.io/5972\'>EPSG:5972</a> <a href=\'https://epsg.io/5973\'>EPSG:5973</a> <a href=\'https://epsg.io/5975\'>EPSG:5975</a> <a href=\'https://epsg.io/4326\'>EPSG:4326</a>.
   * @type string | undefined
   */
  srid?: SridParameter
  /**
   * @description Et vegobjekt har opptil to geometrier, egengeometri og stedfestet geometri. Egengeometrien er plassert under `vegobjekt.egenskaper` om den finnes, stedfestet geometri er plassert under `vegobjekt.lokasjon`. I tillegg til de nevnte feltene på vegobjekt-responsen returneres også `vegobjekt.geometri` (dersom man har `inkluder=geometri` eller `alle`), slik at man alltid finner geometrien for vegobjektet ett sted. Dette feltet er egengeometri dersom objektet har det, hvis ikke har feltet stedfestet geometri Ved hvilken av disse som er tilfelle finner man ut ved å se på `vegobjekt.geometri.egengeometri`.
   * @type string | undefined
   */
  inkludergeometri?: InkluderGeometri
  /**
   * @description Gir mulighet til å filtrere hvilke egenskaper som skal returneres med inkluder=egenskaper. `basis` er alle egenskaper som ikke er geometri, eller lister av geometri.
   * @type string | undefined
   */
  inkluder_egenskaper?: InkluderIEgenskaper
  /**
   * @description Hvor mange nivå barn skal inkluderes. 1 betyr bare IDer, 2-n betyr ett eller flere mellomnivåer, \'full\' betyr alle nivåer.
   * @type string | undefined
   */
  dybde?: string
  /**
   * @description Angir om det skal returneres en forenklet geometri. Dersom parameteren utelates, returneres full geometri for vegobjektene. Nummeret angir distansetoleranse i meter for generering av forenklet geometri.
   * @type integer | undefined, int32
   */
  geometritoleranse?: number
  /**
   * @description Finner versjonen som var gyldig denne datoen.
   * @type string | undefined, date
   */
  tidspunkt?: string
}

/**
 * @description OK
 */
export type GetVegobjektByTypeAndId200 = Vegobjekt

/**
 * @description Bad Request
 */
export type GetVegobjektByTypeAndId400 = ProblemDetail

/**
 * @description Unauthorized
 */
export type GetVegobjektByTypeAndId401 = ProblemDetail

/**
 * @description Forbidden
 */
export type GetVegobjektByTypeAndId403 = ProblemDetail

/**
 * @description Not Found
 */
export type GetVegobjektByTypeAndId404 = ProblemDetail

/**
 * @description Internal Server Error
 */
export type GetVegobjektByTypeAndId500 = ProblemDetail

export type GetVegobjektByTypeAndIdQueryResponse = GetVegobjektByTypeAndId200

export type GetVegobjektByTypeAndIdQuery = {
  Response: GetVegobjektByTypeAndId200
  PathParams: GetVegobjektByTypeAndIdPathParams
  QueryParams: GetVegobjektByTypeAndIdQueryParams
  Errors:
    | GetVegobjektByTypeAndId400
    | GetVegobjektByTypeAndId401
    | GetVegobjektByTypeAndId403
    | GetVegobjektByTypeAndId404
    | GetVegobjektByTypeAndId500
}
