/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type InkluderGeometriEnum = 'ingen' | 'egenskap' | 'lokasjon' | 'utledet'

export type InkluderGeometri = InkluderGeometriEnum
