/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type SideposisjonEnum =
  | 'MH'
  | 'MV'
  | 'VT'
  | 'M'
  | 'H'
  | 'HT'
  | 'HV'
  | 'K'
  | 'V'
  | 'L'
  | 'R0'

export type Sideposisjon = SideposisjonEnum
