/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Egenskap } from './Egenskap.ts'
import type { Egenskapstype } from './Egenskapstype.ts'

export type StrukturEgenskap = (Egenskap & {
  egenskapstype: 'Struktur'
}) & {
  /**
   * @type array | undefined
   */
  innhold?: Egenskap[]
  /**
   * @type string
   */
  egenskapstype: Egenskapstype
  /**
   * @type integer, int32
   */
  id: number
  /**
   * @type string
   */
  navn: string
}
