/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type VegobjektVersjonSegmentert = {
  /**
   * @type integer, int64
   */
  id: number
  /**
   * @type integer, int32
   */
  versjon: number
  /**
   * @type integer, int32
   */
  type: number
  /**
   * @description Tidspunktet da endringen ble gjort tilgjengelig i Les API V4
   * @type string, date-time
   */
  tidspunkt: string
}
