/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Vegfase } from './Vegfase.ts'
import type { Vegkategori } from './Vegkategori.ts'

export type Vegsystem = {
  /**
   * @type string
   */
  vegkategori: Vegkategori
  /**
   * @type string
   */
  fase: Vegfase
  /**
   * @type integer | undefined, int32
   */
  nummer?: number
}
