/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.vt.nvdb.datakatalog.model

import no.vegvesen.vt.nvdb.datakatalog.model.Egenskapstype
import no.vegvesen.vt.nvdb.datakatalog.model.EgenskapstypeEnum
import no.vegvesen.vt.nvdb.datakatalog.model.Viktighet

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param egenskapstype 
 * @param sorteringsnummer 
 * @param avledet 
 * @param skrivebeskyttet 
 * @param obligatoriskVerdi 
 * @param sensitivitet 
 * @param høydereferanseTall 
 * @param nøyaktighetskravGrunnriss 
 * @param nøyaktighetskravHøyde 
 * @param referansegeometriTilstrekkelig 
 * @param viktighet 
 * @param kategori 
 * @param navn 
 * @param kortnavn 
 * @param beskrivelse 
 * @param veiledning 
 * @param sosinavn 
 * @param sosinvdbnavn 
 * @param komplementærEgenskapstype 
 * @param gruppesorteringsnummer 
 * @param grunnrissreferanse 
 * @param høydereferanse 
 * @param sosiReferanse 
 * @param tilleggskrav 
 * @param tilknytning 
 * @param vegobjekttypeid 
 * @param innenforMor 
 * @param startdato 
 * @param sluttdato 
 * @param assosiasjonskrav 
 * @param assosiasjonskravkommentar 
 */


data class EgenskapstypeAssosiasjon (

    @Json(name = "id")
    override val id: kotlin.Int,

    @Json(name = "egenskapstype")
    override val egenskapstype: EgenskapstypeEnum,

    @Json(name = "sorteringsnummer")
    override val sorteringsnummer: kotlin.Int,

    @Json(name = "avledet")
    override val avledet: kotlin.Boolean,

    @Json(name = "skrivebeskyttet")
    override val skrivebeskyttet: kotlin.Boolean,

    @Json(name = "obligatorisk_verdi")
    override val obligatoriskVerdi: kotlin.Boolean,

    @Json(name = "sensitivitet")
    override val sensitivitet: kotlin.Int,

    @Json(name = "høydereferanse_tall")
    override val høydereferanseTall: kotlin.Int,

    @Json(name = "nøyaktighetskrav_grunnriss")
    override val nøyaktighetskravGrunnriss: kotlin.Double,

    @Json(name = "nøyaktighetskrav_høyde")
    override val nøyaktighetskravHøyde: kotlin.Double,

    @Json(name = "referansegeometri_tilstrekkelig")
    override val referansegeometriTilstrekkelig: kotlin.Boolean,

    @Json(name = "viktighet")
    override val viktighet: Viktighet,

    @Json(name = "kategori")
    override val kategori: kotlin.Int,

    @Json(name = "navn")
    override val navn: kotlin.String? = null,

    @Json(name = "kortnavn")
    override val kortnavn: kotlin.String? = null,

    @Json(name = "beskrivelse")
    override val beskrivelse: kotlin.String? = null,

    @Json(name = "veiledning")
    override val veiledning: kotlin.String? = null,

    @Json(name = "sosinavn")
    override val sosinavn: kotlin.String? = null,

    @Json(name = "sosinvdbnavn")
    override val sosinvdbnavn: kotlin.String? = null,

    @Json(name = "komplementær_egenskapstype")
    override val komplementærEgenskapstype: kotlin.Int? = null,

    @Json(name = "gruppesorteringsnummer")
    override val gruppesorteringsnummer: kotlin.Int? = null,

    @Json(name = "grunnrissreferanse")
    override val grunnrissreferanse: kotlin.String? = null,

    @Json(name = "høydereferanse")
    override val høydereferanse: kotlin.String? = null,

    @Json(name = "sosi_referanse")
    override val sosiReferanse: kotlin.String? = null,

    @Json(name = "tilleggskrav")
    override val tilleggskrav: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "tilknytning")
    val tilknytning: kotlin.Int? = null,

    @Json(name = "vegobjekttypeid")
    val vegobjekttypeid: kotlin.Int? = null,

    @Json(name = "innenfor_mor")
    val innenforMor: kotlin.Int? = null,

    @Json(name = "startdato")
    val startdato: kotlinx.datetime.LocalDate? = null,

    @Json(name = "sluttdato")
    val sluttdato: kotlinx.datetime.LocalDate? = null,

    @Json(name = "assosiasjonskrav")
    val assosiasjonskrav: kotlin.Int? = null,

    @Json(name = "assosiasjonskravkommentar")
    val assosiasjonskravkommentar: kotlin.String? = null

) : Egenskapstype {


}

