/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.vt.nvdb.datakatalog.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: Assosiasjon,Boolsk,Binær,Tekst,Dato,Flyttall,Heltall,Struktur,Geometri,Stedfesting,Kortdato,Tid,Liste,Tekstenum,Heltallenum,Flyttallenum
 */

@JsonClass(generateAdapter = false)
enum class EgenskapstypeEnum(val value: kotlin.String) {

    @Json(name = "Assosiasjon")
    Assosiasjon("Assosiasjon"),

    @Json(name = "Boolsk")
    Boolsk("Boolsk"),

    @Json(name = "Binær")
    Binær("Binær"),

    @Json(name = "Tekst")
    Tekst("Tekst"),

    @Json(name = "Dato")
    Dato("Dato"),

    @Json(name = "Flyttall")
    Flyttall("Flyttall"),

    @Json(name = "Heltall")
    Heltall("Heltall"),

    @Json(name = "Struktur")
    Struktur("Struktur"),

    @Json(name = "Geometri")
    Geometri("Geometri"),

    @Json(name = "Stedfesting")
    Stedfesting("Stedfesting"),

    @Json(name = "Kortdato")
    Kortdato("Kortdato"),

    @Json(name = "Tid")
    Tid("Tid"),

    @Json(name = "Liste")
    Liste("Liste"),

    @Json(name = "Tekstenum")
    Tekstenum("Tekstenum"),

    @Json(name = "Heltallenum")
    Heltallenum("Heltallenum"),

    @Json(name = "Flyttallenum")
    Flyttallenum("Flyttallenum");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is EgenskapstypeEnum) "$data" else null

        /**
         * Returns a valid [EgenskapstypeEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): EgenskapstypeEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

