/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.vt.nvdb.datakatalog.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param kortnavnBrukbar 
 * @param sorteringsnummer 
 * @param standardverdi 
 * @param type 
 * @param kortnavn 
 * @param kortnavnlengde 
 * @param beskrivelse 
 * @param objektlisteDato 
 * @param sluttdato 
 * @param komplementærEnumverdi 
 * @param verdi 
 */


data class EnumverdiTekst (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "kortnavn_brukbar")
    val kortnavnBrukbar: kotlin.Boolean,

    @Json(name = "sorteringsnummer")
    val sorteringsnummer: kotlin.Int,

    @Json(name = "standardverdi")
    val standardverdi: kotlin.Boolean,

    @Json(name = "type")
    val type: kotlin.String,

    @Json(name = "kortnavn")
    val kortnavn: kotlin.String? = null,

    @Json(name = "kortnavnlengde")
    val kortnavnlengde: kotlin.Int? = null,

    @Json(name = "beskrivelse")
    val beskrivelse: kotlin.String? = null,

    @Json(name = "objektliste_dato")
    val objektlisteDato: kotlinx.datetime.LocalDate? = null,

    @Json(name = "sluttdato")
    val sluttdato: kotlinx.datetime.LocalDate? = null,

    @Json(name = "komplementær_enumverdi")
    val komplementærEnumverdi: kotlin.Int? = null,

    @Json(name = "verdi")
    val verdi: kotlin.String? = null

) {


}

