/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.vt.nvdb.datakatalog.model

import no.vegvesen.vt.nvdb.datakatalog.model.EgenskapstypeEnum
import no.vegvesen.vt.nvdb.datakatalog.model.Stedfesting
import no.vegvesen.vt.nvdb.datakatalog.model.Viktighet

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param egenskapstype 
 * @param sorteringsnummer 
 * @param avledet 
 * @param skrivebeskyttet 
 * @param obligatoriskVerdi 
 * @param sensitivitet 
 * @param høydereferanseTall 
 * @param nøyaktighetskravGrunnriss 
 * @param nøyaktighetskravHøyde 
 * @param referansegeometriTilstrekkelig 
 * @param viktighet 
 * @param kategori 
 * @param navn 
 * @param kortnavn 
 * @param beskrivelse 
 * @param veiledning 
 * @param sosinavn 
 * @param sosinvdbnavn 
 * @param komplementærEgenskapstype 
 * @param gruppesorteringsnummer 
 * @param grunnrissreferanse 
 * @param høydereferanse 
 * @param sosiReferanse 
 * @param stedfestingstype 
 * @param geometritype 
 * @param overlappOk 
 * @param kjørefeltRelevant 
 * @param sideposisjonRelevant 
 * @param innenforMor 
 * @param vegnettsajourholdSplitt 
 * @param overlappsautomatikk 
 * @param retningRelevant 
 */


data class StedfestingEnkel (

    @Json(name = "id")
    override val id: kotlin.Int,

    @Json(name = "egenskapstype")
    override val egenskapstype: EgenskapstypeEnum,

    @Json(name = "sorteringsnummer")
    override val sorteringsnummer: kotlin.Int,

    @Json(name = "avledet")
    override val avledet: kotlin.Boolean,

    @Json(name = "skrivebeskyttet")
    override val skrivebeskyttet: kotlin.Boolean,

    @Json(name = "obligatorisk_verdi")
    override val obligatoriskVerdi: kotlin.Boolean,

    @Json(name = "sensitivitet")
    override val sensitivitet: kotlin.Int,

    @Json(name = "høydereferanse_tall")
    override val høydereferanseTall: kotlin.Int,

    @Json(name = "nøyaktighetskrav_grunnriss")
    override val nøyaktighetskravGrunnriss: kotlin.Double,

    @Json(name = "nøyaktighetskrav_høyde")
    override val nøyaktighetskravHøyde: kotlin.Double,

    @Json(name = "referansegeometri_tilstrekkelig")
    override val referansegeometriTilstrekkelig: kotlin.Boolean,

    @Json(name = "viktighet")
    override val viktighet: Viktighet,

    @Json(name = "kategori")
    override val kategori: kotlin.Int,

    @Json(name = "navn")
    override val navn: kotlin.String? = null,

    @Json(name = "kortnavn")
    override val kortnavn: kotlin.String? = null,

    @Json(name = "beskrivelse")
    override val beskrivelse: kotlin.String? = null,

    @Json(name = "veiledning")
    override val veiledning: kotlin.String? = null,

    @Json(name = "sosinavn")
    override val sosinavn: kotlin.String? = null,

    @Json(name = "sosinvdbnavn")
    override val sosinvdbnavn: kotlin.String? = null,

    @Json(name = "komplementær_egenskapstype")
    override val komplementærEgenskapstype: kotlin.Int? = null,

    @Json(name = "gruppesorteringsnummer")
    override val gruppesorteringsnummer: kotlin.Int? = null,

    @Json(name = "grunnrissreferanse")
    override val grunnrissreferanse: kotlin.String? = null,

    @Json(name = "høydereferanse")
    override val høydereferanse: kotlin.String? = null,

    @Json(name = "sosi_referanse")
    override val sosiReferanse: kotlin.String? = null,

    @Json(name = "stedfestingstype")
    val stedfestingstype: StedfestingEnkel.Stedfestingstype? = null,

    @Json(name = "geometritype")
    val geometritype: StedfestingEnkel.Geometritype? = null,

    @Json(name = "overlapp_ok")
    val overlappOk: kotlin.Boolean? = null,

    @Json(name = "kjørefelt_relevant")
    val kjørefeltRelevant: StedfestingEnkel.KjørefeltRelevant? = null,

    @Json(name = "sideposisjon_relevant")
    val sideposisjonRelevant: StedfestingEnkel.SideposisjonRelevant? = null,

    @Json(name = "innenfor_mor")
    val innenforMor: kotlin.Boolean? = null,

    @Json(name = "vegnettsajourhold_splitt")
    val vegnettsajourholdSplitt: StedfestingEnkel.VegnettsajourholdSplitt? = null,

    @Json(name = "overlappsautomatikk")
    val overlappsautomatikk: kotlin.String? = null,

    @Json(name = "retning_relevant")
    val retningRelevant: kotlin.Boolean? = null

) : Stedfesting {

    /**
     * 
     *
     * Values: Punkt,Linje,Sving
     */
    @JsonClass(generateAdapter = false)
    enum class Stedfestingstype(val value: kotlin.String) {
        @Json(name = "Punkt") Punkt("Punkt"),
        @Json(name = "Linje") Linje("Linje"),
        @Json(name = "Sving") Sving("Sving");
    }
    /**
     * 
     *
     * Values: PUNKT,LINJE,SVING
     */
    @JsonClass(generateAdapter = false)
    enum class Geometritype(val value: kotlin.String) {
        @Json(name = "PUNKT") PUNKT("PUNKT"),
        @Json(name = "LINJE") LINJE("LINJE"),
        @Json(name = "SVING") SVING("SVING");
    }
    /**
     * 
     *
     * Values: KAN,NEI,MÅ
     */
    @JsonClass(generateAdapter = false)
    enum class KjørefeltRelevant(val value: kotlin.String) {
        @Json(name = "KAN") KAN("KAN"),
        @Json(name = "NEI") NEI("NEI"),
        @Json(name = "MÅ") MÅ("MÅ");
    }
    /**
     * 
     *
     * Values: KAN,NEI,MÅ
     */
    @JsonClass(generateAdapter = false)
    enum class SideposisjonRelevant(val value: kotlin.String) {
        @Json(name = "KAN") KAN("KAN"),
        @Json(name = "NEI") NEI("NEI"),
        @Json(name = "MÅ") MÅ("MÅ");
    }
    /**
     * 
     *
     * Values: IKKE_TATT_STILLING,KAN_IKKE_SPLITTES,KAN_SPLITTES
     */
    @JsonClass(generateAdapter = false)
    enum class VegnettsajourholdSplitt(val value: kotlin.String) {
        @Json(name = "IKKE_TATT_STILLING") IKKE_TATT_STILLING("IKKE_TATT_STILLING"),
        @Json(name = "KAN_IKKE_SPLITTES") KAN_IKKE_SPLITTES("KAN_IKKE_SPLITTES"),
        @Json(name = "KAN_SPLITTES") KAN_SPLITTES("KAN_SPLITTES");
    }

}

