/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package no.vegvesen.vt.nvdb.datakatalog.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param primærkategori 
 * @param nummer 
 * @param sorteringsnummer 
 * @param navn 
 * @param kortnavn 
 * @param beskrivelse 
 * @param startDato 
 */


data class VegobjektKategori (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "primærkategori")
    val primærkategori: kotlin.Boolean,

    @Json(name = "nummer")
    val nummer: kotlin.Int,

    @Json(name = "sorteringsnummer")
    val sorteringsnummer: kotlin.Int,

    @Json(name = "navn")
    val navn: kotlin.String? = null,

    @Json(name = "kortnavn")
    val kortnavn: kotlin.String? = null,

    @Json(name = "beskrivelse")
    val beskrivelse: kotlin.String? = null,

    @Json(name = "startDato")
    val startDato: kotlinx.datetime.LocalDate? = null

) {


}

