/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { egenskapstypeEnumSchema } from './egenskapstypeEnumSchema.ts'
import { egenskapstypeSchema } from './egenskapstypeSchema.ts'
import { viktighetSchema } from './viktighetSchema.ts'
import { z } from 'zod/v4'

export const egenskapstypeTidSchema = z
  .lazy(() => egenskapstypeSchema)
  .and(
    z.object({
      egenskapstype: z.literal('Tid'),
    }),
  )
  .and(
    z.object({
      objektliste_dato: z.optional(z.iso.date()),
      slutt_dato: z.optional(z.iso.date()),
      lengdeavhengig_verdi: z.boolean(),
      ajourhold_snu: z.boolean(),
      standardverdi: z.optional(z.string()),
      min_anbefalt: z.optional(z.string()),
      maks_anbefalt: z.optional(z.string()),
      feltmønster: z.optional(z.string()),
      avledet: z.boolean(),
      get egenskapstype() {
        return egenskapstypeEnumSchema
      },
      høydereferanse_tall: z.int(),
      id: z.int(),
      kategori: z.int(),
      nøyaktighetskrav_grunnriss: z.number(),
      nøyaktighetskrav_høyde: z.number(),
      obligatorisk_verdi: z.boolean(),
      referansegeometri_tilstrekkelig: z.boolean(),
      sensitivitet: z.int(),
      skrivebeskyttet: z.boolean(),
      sorteringsnummer: z.int(),
      get viktighet() {
        return viktighetSchema
      },
    }),
  )
