import { z } from 'zod'

export const egenskapstypeSchema = z.object({
  id: z.number(),
  navn: z.string().optional(),
  egenskapstype: z.enum([
    `Assosiasjon`,
    `Boolsk`,
    `Binær`,
    `Tekst`,
    `Dato`,
    `Flyttall`,
    `Heltall`,
    `Struktur`,
    `Geometri`,
    `Stedfesting`,
    `Kortdato`,
    `Tid`,
    `Liste`,
    `Tekstenum`,
    `Heltallenum`,
    `Flyttallenum`,
  ]),
  kortnavn: z.string().optional(),
  beskrivelse: z.string().optional(),
  sosinavn: z.string().optional(),
  sosinvdbnavn: z.string().optional(),
  sorteringsnummer: z.number(),
  avledet: z.boolean(),
  komplementær_egenskapstype: z.number().optional(),
  obligatorisk_verdi: z.boolean(),
  skrivebeskyttet: z.boolean(),
  sensitivitet: z.number(),
  gruppesorteringsnummer: z.number().optional(),
  veiledning: z.string().optional(),
  grunnrissreferanse: z.string().optional(),
  høydereferanse: z.string().optional(),
  høydereferanse_tall: z.number(),
  nøyaktighetskrav_grunnriss: z.number(),
  nøyaktighetskrav_høyde: z.number(),
  sosi_referanse: z.string().optional(),
  referansegeometri_tilstrekkelig: z.boolean(),
  viktighet: z.enum([
    `IKKE_SATT`,
    `PÅKREVD_ABSOLUTT`,
    `PÅKREVD_IKKE_ABSOLUTT`,
    `BETINGET`,
    `OPSJONELL`,
    `MINDRE_VIKTIG`,
    `HISTORISK`,
  ]),
  kategori: z.number(),
})
