/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { egenskapstypeEnumSchema } from './egenskapstypeEnumSchema.ts'
import { egenskapstypeSchema } from './egenskapstypeSchema.ts'
import { viktighetSchema } from './viktighetSchema.ts'
import { z } from 'zod/v4'

export const egenskapstypeListeSchema = z
  .lazy(() => egenskapstypeSchema)
  .and(
    z.object({
      egenskapstype: z.literal('Liste'),
    }),
  )
  .and(
    z.object({
      maksimalt_antall_verdier: z.optional(z.int()),
      minimalt_antall_verdier: z.optional(z.int()),
      get innhold() {
        return egenskapstypeSchema
      },
      avledet: z.boolean(),
      get egenskapstype() {
        return egenskapstypeEnumSchema
      },
      høydereferanse_tall: z.int(),
      id: z.int(),
      kategori: z.int(),
      nøyaktighetskrav_grunnriss: z.number(),
      nøyaktighetskrav_høyde: z.number(),
      obligatorisk_verdi: z.boolean(),
      referansegeometri_tilstrekkelig: z.boolean(),
      sensitivitet: z.int(),
      skrivebeskyttet: z.boolean(),
      sorteringsnummer: z.int(),
      get viktighet() {
        return viktighetSchema
      },
    }),
  )
