/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const enumverdiFlyttallSchema = z.object({
  id: z.int(),
  kortnavn: z.optional(z.string()),
  kortnavnlengde: z.optional(z.int()),
  kortnavn_brukbar: z.boolean(),
  beskrivelse: z.optional(z.string()),
  sorteringsnummer: z.int(),
  objektliste_dato: z.optional(z.iso.date()),
  sluttdato: z.optional(z.iso.date()),
  standardverdi: z.boolean(),
  komplementær_enumverdi: z.optional(z.int()),
  verdi: z.optional(z.number()),
  type: z.string(),
})
