/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailSchema } from './problemDetailSchema.ts'
import { vegobjekttypeSchema } from './vegobjekttypeSchema.ts'
import { z } from 'zod/v4'

export const getVegobjekttypePathParamsSchema = z.object({
  vegobjekttypeid: z.coerce.number().int(),
})

export const getVegobjekttypeQueryParamsSchema = z
  .object({
    inkluder: z.optional(
      z
        .array(
          z.enum([
            'egenskapstyper',
            'relasjonstyper',
            'stedfesting',
            'alle',
            'minimum',
          ]),
        )
        .refine((items) => new Set(items).size === items.length, {
          message: 'Array entries must be unique',
        })
        .describe(
          'Kommaseparert liste med hvilke informasjonsfelter som skal inkluderes i tillegg til vegobjekttypenes metadata.',
        ),
    ),
  })
  .optional()

/**
 * @description OK
 */
export const getVegobjekttype200Schema = z.lazy(() => vegobjekttypeSchema)

/**
 * @description Not Found
 */
export const getVegobjekttype404Schema = z.lazy(() => problemDetailSchema)

/**
 * @description Internal Server Error
 */
export const getVegobjekttype500Schema = z.lazy(() => problemDetailSchema)

/**
 * @description Service Unavailable
 */
export const getVegobjekttype503Schema = z.lazy(() => problemDetailSchema)

export const getVegobjekttypeQueryResponseSchema = z.lazy(
  () => getVegobjekttype200Schema,
)
