/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { problemDetailSchema } from './problemDetailSchema.ts'
import { versjonSchema } from './versjonSchema.ts'
import { z } from 'zod/v4'

/**
 * @description OK
 */
export const getVersjon200Schema = z.lazy(() => versjonSchema)

/**
 * @description Not Found
 */
export const getVersjon404Schema = z.lazy(() => problemDetailSchema)

/**
 * @description Internal Server Error
 */
export const getVersjon500Schema = z.lazy(() => problemDetailSchema)

/**
 * @description Service Unavailable
 */
export const getVersjon503Schema = z.lazy(() => problemDetailSchema)

export const getVersjonQueryResponseSchema = z.lazy(() => getVersjon200Schema)
