/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const viktighetSchema = z.enum([
  'IKKE_SATT',
  'PÅKREVD_ABSOLUTT',
  'PÅKREVD_IKKE_ABSOLUTT',
  'BETINGET',
  'OPSJONELL',
  'MINDRE_VIKTIG',
  'HISTORISK',
])
