/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { egenskapSchema } from './egenskapSchema.ts'
import { egenskapstypeSchema } from './egenskapstypeSchema.ts'
import { z } from 'zod/v4'

export const datoEgenskapSchema = z
  .lazy(() => egenskapSchema)
  .and(
    z.object({
      egenskapstype: z.literal('Dato'),
    }),
  )
  .and(
    z.object({
      verdi: z.optional(z.iso.date()),
      get egenskapstype() {
        return egenskapstypeSchema
      },
      id: z.int(),
      navn: z.string(),
    }),
  )
