/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { egenskapstypeSchema } from './egenskapstypeSchema.ts'
import { z } from 'zod/v4'

export const egenskapSchema = z.object({
  id: z.int(),
  navn: z.string(),
  get egenskapstype() {
    return egenskapstypeSchema
  },
})
