/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { SRIDSchema } from './SRIDSchema.ts'
import { z } from 'zod/v4'

export const geometriSchema = z.object({
  wkt: z.string(),
  get srid() {
    return SRIDSchema.describe(
      'Hvilket geografiske referansesystem koordinatene er i',
    )
  },
  forenklet: z.optional(
    z
      .boolean()
      .default('false')
      .describe(
        'Indikerer at geometrien er forenklet. Kun inkludert om den er true',
      ),
  ),
  egengeometri: z.optional(
    z
      .boolean()
      .describe(
        'Angir om geometrien er vegobjektets egengeometri, eller om geometrien er utledet fra vegnettes geometri',
      ),
  ),
})
