/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const inkluderGeometriSchema = z.enum([
  'ingen',
  'egenskap',
  'lokasjon',
  'utledet',
])
