/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { egenskapSchema } from './egenskapSchema.ts'
import { egenskapstypeSchema } from './egenskapstypeSchema.ts'
import { z } from 'zod/v4'

export const kortDatoEgenskapSchema = z
  .lazy(() => egenskapSchema)
  .and(
    z.object({
      egenskapstype: z.literal('Kortdato'),
    }),
  )
  .and(
    z.object({
      verdi: z.optional(
        z
          .string()
          .regex(/^(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$/)
          .describe('Måned og dato på formatet MM-DD'),
      ),
      get egenskapstype() {
        return egenskapstypeSchema
      },
      id: z.int(),
      navn: z.string(),
    }),
  )
