/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { adresseSchema } from './adresseSchema.ts'
import { geometriSchema } from './geometriSchema.ts'
import { kontraktsomradeSchema } from './kontraktsomradeSchema.ts'
import { riksvegruteSchema } from './riksvegruteSchema.ts'
import { stedfestingSchema } from './stedfestingSchema.ts'
import { vegforvalterSchema } from './vegforvalterSchema.ts'
import { vegsystemreferanseSchema } from './vegsystemreferanseSchema.ts'
import { z } from 'zod/v4'

export const lokasjonSchema = z.object({
  kommuner: z.array(z.int()),
  fylker: z.array(z.int()),
  get kontraktsområder() {
    return z
      .array(kontraktsomradeSchema)
      .describe(
        'Utelatt om vegobjektet ikke overlapper med noen kontraktsområder',
      )
      .optional()
  },
  get riksvegruter() {
    return z
      .array(riksvegruteSchema)
      .describe('Utelatt om vegobjektet ikke overlapper med noen riksvegruter')
      .optional()
  },
  get vegforvaltere() {
    return z
      .array(vegforvalterSchema)
      .describe('Utelatt om vegobjektet ikke overlapper med noen vegforvaltere')
      .optional()
  },
  get adresser() {
    return z
      .array(adresseSchema)
      .describe('Utelatt om vegobjektet ikke overlapper med noen adresser')
      .optional()
  },
  get vegsystemreferanser() {
    return z
      .array(vegsystemreferanseSchema)
      .describe('Utelatt om vegobjektet ikke har noen vegsystemreferanser')
      .optional()
  },
  get stedfestinger() {
    return z
      .array(stedfestingSchema)
      .describe('Utelatt om vegobjektet ikke har noen stedfestinger')
      .optional()
  },
  get geometri() {
    return geometriSchema
      .describe(
        'Kun med om inkludergeometri=lokasjon eller inkludergeometri ikke er oppgitt',
      )
      .optional()
  },
  lengde: z.optional(z.number().describe('Utelatt om lengde er lik 0')),
})
