/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { relasjonSchema } from './relasjonSchema.ts'
import { relasjonstypeSchema } from './relasjonstypeSchema.ts'
import { vegobjektSchema } from './vegobjektSchema.ts'
import { vegobjektTypeSchema } from './vegobjektTypeSchema.ts'
import { z } from 'zod/v4'

export const relasjonMedVegobjekterSchema = z
  .lazy(() => relasjonSchema)
  .and(
    z.object({
      relasjonstype: z.literal('vegobjekter'),
    }),
  )
  .and(
    z.object({
      get vegobjekter() {
        return z.array(vegobjektSchema)
      },
      id: z.int(),
      get relasjonstype() {
        return relasjonstypeSchema
      },
      get type() {
        return vegobjektTypeSchema
      },
    }),
  )
