/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { retningSchema } from './retningSchema.ts'
import { sideposisjonSchema } from './sideposisjonSchema.ts'
import { stedfestingstypeSchema } from './stedfestingstypeSchema.ts'
import { z } from 'zod/v4'

export const stedfestingSchema = z.object({
  get type() {
    return stedfestingstypeSchema
  },
  veglenkesekvensid: z.optional(z.int()),
  nodeid: z.optional(z.int()),
  relativPosisjon: z.optional(z.number()),
  startposisjon: z.optional(z.number()),
  sluttposisjon: z.optional(z.number()),
  get startpunkt() {
    return stedfestingSchema.optional()
  },
  get sluttpunkt() {
    return stedfestingSchema.optional()
  },
  get retning() {
    return retningSchema.optional()
  },
  kjørefelt: z.optional(
    z.array(z.string()).describe('Utelatt for svingstedfesting'),
  ),
  get sideposisjon() {
    return sideposisjonSchema.optional()
  },
  kortform: z.optional(z.string()),
})
