/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { adskilteLopSchema } from './adskilteLopSchema.ts'
import { retningSchema } from './retningSchema.ts'
import { trafikantgruppeSchema } from './trafikantgruppeSchema.ts'
import { z } from 'zod/v4'

export const strekningSchema = z.object({
  strekning: z.int(),
  delstrekning: z.int(),
  arm: z.boolean(),
  get adskilte_løp() {
    return adskilteLopSchema
  },
  get trafikantgruppe() {
    return trafikantgruppeSchema
  },
  get retning() {
    return retningSchema
  },
  meter: z.optional(z.number()),
  fra_meter: z.optional(z.number()),
  til_meter: z.optional(z.number()),
  adskilte_løp_nummer: z.optional(z.string()),
})
