/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const veglenkeTypeSchema = z.enum([
  'Ukjent',
  'DETALJERT',
  'KONNEKTERING',
  'DETALJERT_KONNEKTERING',
  'HOVED',
])
