/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { vegobjekterStatistikkSchema } from './vegobjekterStatistikkSchema.ts'
import { z } from 'zod/v4'

export const vegobjekterStatistikkMedTypeSchema = z.object({
  id: z.int(),
  navn: z.string(),
  href: z.string(),
  get statistikk() {
    return vegobjekterStatistikkSchema
  },
})
