import { geometriSchema } from './geometriSchema'
import { vegsystemreferanseSchema } from './vegsystemreferanseSchema'
import { z } from 'zod'

export const vegsegmentSchema = z.object({
  veglenkesekvensid: z.number(),
  startposisjon: z.number().optional(),
  sluttposisjon: z.number().optional(),
  relativPosisjon: z.number().optional(),
  lengde: z.number().optional(),
  retning: z.enum([`MED`, `MOT`]),
  veglenkeType: z.enum([
    `Ukjent`,
    `DETALJERT`,
    `KONNEKTERING`,
    `DETALJERT_KONNEKTERING`,
    `HOVED`,
  ]),
  'detaljniv\u00E5': z.enum([
    `Vegtrase`,
    `Kjørebane`,
    `Kjørefelt`,
    `Vegtrase og kjørebane`,
  ]),
  typeVeg: z.enum([
    `Kanalisert veg`,
    `Enkel bilveg`,
    `Rampe`,
    `Rundkjøring`,
    `Bilferje`,
    `Passasjerferje`,
    `Gang- og sykkelveg`,
    `Sykkelveg`,
    `Gangveg`,
    `Gågate`,
    `Fortau`,
    `Trapp`,
    `Gangfelt`,
    `Gatetun`,
    `Traktorveg`,
    `Sti`,
    `Annet`,
  ]),
  typeVeg_sosi: z.enum([
    `kanalisertVeg`,
    `enkelBilveg`,
    `rampe`,
    `rundkjøring`,
    `bilferje`,
    `passasjerferje`,
    `gangOgSykkelveg`,
    `sykkelveg`,
    `gangveg`,
    `gågate`,
    `fortau`,
    `trapp`,
    `gangfelt`,
    `gatetun`,
    `traktorveg`,
    `sti`,
    `annet`,
  ]),
  startdato: z.string(),
  sluttdato: z.string().optional(),
  geometri: z.lazy(() => geometriSchema),
  kommune: z.number(),
  fylke: z.number(),
  vegsystemreferanse: z.lazy(() => vegsystemreferanseSchema),
  'kontraktsomr\u00E5der': z.array(z.number()).optional(),
  riksvegruter: z.array(z.number()).optional(),
})
