import { geometriSchema } from './geometriSchema'
import { vegsystemreferanseSchema } from './vegsystemreferanseSchema'
import { z } from 'zod'

export const vegsegmentSchema = z.object({
  veglenkesekvensid: z.number().int(),
  startposisjon: z.number().optional(),
  sluttposisjon: z.number().optional(),
  relativPosisjon: z.number().optional(),
  lengde: z.number().optional(),
  retning: z.enum(['MED', 'MOT']),
  'kj\u00F8refelt': z.array(z.string()).optional(),
  sideposisjon: z
    .enum([
      'MH',
      'MV',
      'VT',
      'M',
      'H',
      'HT',
      'VH',
      'HV',
      'K',
      'V',
      'L',
      'R',
      'R0',
    ])
    .optional(),
  feltoversikt: z.array(z.string()).optional(),
  veglenkeType: z.enum([
    'Ukjent',
    'DETALJERT',
    'KONNEKTERING',
    'DETALJERT_KONNEKTERING',
    'HOVED',
  ]),
  'detaljniv\u00E5': z.enum([
    'Vegtrase',
    'Kj\u00F8rebane',
    'Kj\u00F8refelt',
    'Vegtrase og kj\u00F8rebane',
  ]),
  typeVeg: z.enum([
    'Kanalisert veg',
    'Enkel bilveg',
    'Rampe',
    'Rundkj\u00F8ring',
    'Bilferje',
    'Passasjerferje',
    'Gang- og sykkelveg',
    'Sykkelveg',
    'Gangveg',
    'G\u00E5gate',
    'Fortau',
    'Trapp',
    'Gangfelt',
    'Gatetun',
    'Traktorveg',
    'Sti',
    'Annet',
  ]),
  typeVeg_sosi: z.enum([
    'kanalisertVeg',
    'enkelBilveg',
    'rampe',
    'rundkj\u00F8ring',
    'bilferje',
    'passasjerferje',
    'gangOgSykkelveg',
    'sykkelveg',
    'gangveg',
    'g\u00E5gate',
    'fortau',
    'trapp',
    'gangfelt',
    'gatetun',
    'traktorveg',
    'sti',
    'annet',
  ]),
  startdato: z.string().date(),
  sluttdato: z.string().date().optional(),
  geometri: z.lazy(() => geometriSchema),
  kommune: z.number().int(),
  fylke: z.number().int(),
  vegsystemreferanse: z.lazy(() => vegsystemreferanseSchema).optional(),
  'kontraktsomr\u00E5der': z.array(z.number().int()).optional(),
  riksvegruter: z.array(z.number().int()).optional(),
  vegforvaltere: z.array(z.number().int()).optional(),
  adresser: z.array(z.number().int()).optional(),
})
