/*
 * NVDB API Les Vegnett
 * Dette API-et brukes til å lese vegnettelementer. Les mer om bruk av API-et på https://nvdb.test.atlas.vegvesen.no/produkter/nvdbapil/v4/Vegnett
 *
 * The version of the OpenAPI document: v4
 * Contact: nvdb@vegvesen.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.vegvesen.vt.nvdb.vegnett.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import no.vegvesen.vt.nvdb.vegnett.model.PosisjonGeometri;
import no.vegvesen.vt.nvdb.vegnett.model.PosisjonVeglenkesekvens;
import no.vegvesen.vt.nvdb.vegnett.model.Vegsystemreferanse;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PosisjonMedAvstand
 */
@JsonPropertyOrder({
  PosisjonMedAvstand.JSON_PROPERTY_VEGSYSTEMREFERANSE,
  PosisjonMedAvstand.JSON_PROPERTY_VEGLENKESEKVENS,
  PosisjonMedAvstand.JSON_PROPERTY_GEOMETRI,
  PosisjonMedAvstand.JSON_PROPERTY_KOMMUNE,
  PosisjonMedAvstand.JSON_PROPERTY_AVSTAND
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class PosisjonMedAvstand {
  public static final String JSON_PROPERTY_VEGSYSTEMREFERANSE = "vegsystemreferanse";
  @jakarta.annotation.Nonnull
  private Vegsystemreferanse vegsystemreferanse;

  public static final String JSON_PROPERTY_VEGLENKESEKVENS = "veglenkesekvens";
  @jakarta.annotation.Nonnull
  private PosisjonVeglenkesekvens veglenkesekvens;

  public static final String JSON_PROPERTY_GEOMETRI = "geometri";
  @jakarta.annotation.Nonnull
  private PosisjonGeometri geometri;

  public static final String JSON_PROPERTY_KOMMUNE = "kommune";
  @jakarta.annotation.Nonnull
  private Integer kommune;

  public static final String JSON_PROPERTY_AVSTAND = "avstand";
  @jakarta.annotation.Nonnull
  private Double avstand;

  public PosisjonMedAvstand() {
  }

  public PosisjonMedAvstand vegsystemreferanse(@jakarta.annotation.Nonnull Vegsystemreferanse vegsystemreferanse) {
    
    this.vegsystemreferanse = vegsystemreferanse;
    return this;
  }

  /**
   * Get vegsystemreferanse
   * @return vegsystemreferanse
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VEGSYSTEMREFERANSE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Vegsystemreferanse getVegsystemreferanse() {
    return vegsystemreferanse;
  }


  @JsonProperty(JSON_PROPERTY_VEGSYSTEMREFERANSE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVegsystemreferanse(@jakarta.annotation.Nonnull Vegsystemreferanse vegsystemreferanse) {
    this.vegsystemreferanse = vegsystemreferanse;
  }

  public PosisjonMedAvstand veglenkesekvens(@jakarta.annotation.Nonnull PosisjonVeglenkesekvens veglenkesekvens) {
    
    this.veglenkesekvens = veglenkesekvens;
    return this;
  }

  /**
   * Get veglenkesekvens
   * @return veglenkesekvens
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VEGLENKESEKVENS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PosisjonVeglenkesekvens getVeglenkesekvens() {
    return veglenkesekvens;
  }


  @JsonProperty(JSON_PROPERTY_VEGLENKESEKVENS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVeglenkesekvens(@jakarta.annotation.Nonnull PosisjonVeglenkesekvens veglenkesekvens) {
    this.veglenkesekvens = veglenkesekvens;
  }

  public PosisjonMedAvstand geometri(@jakarta.annotation.Nonnull PosisjonGeometri geometri) {
    
    this.geometri = geometri;
    return this;
  }

  /**
   * Get geometri
   * @return geometri
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GEOMETRI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PosisjonGeometri getGeometri() {
    return geometri;
  }


  @JsonProperty(JSON_PROPERTY_GEOMETRI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGeometri(@jakarta.annotation.Nonnull PosisjonGeometri geometri) {
    this.geometri = geometri;
  }

  public PosisjonMedAvstand kommune(@jakarta.annotation.Nonnull Integer kommune) {
    
    this.kommune = kommune;
    return this;
  }

  /**
   * Get kommune
   * @return kommune
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_KOMMUNE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getKommune() {
    return kommune;
  }


  @JsonProperty(JSON_PROPERTY_KOMMUNE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKommune(@jakarta.annotation.Nonnull Integer kommune) {
    this.kommune = kommune;
  }

  public PosisjonMedAvstand avstand(@jakarta.annotation.Nonnull Double avstand) {
    
    this.avstand = avstand;
    return this;
  }

  /**
   * Get avstand
   * @return avstand
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AVSTAND)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getAvstand() {
    return avstand;
  }


  @JsonProperty(JSON_PROPERTY_AVSTAND)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAvstand(@jakarta.annotation.Nonnull Double avstand) {
    this.avstand = avstand;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PosisjonMedAvstand posisjonMedAvstand = (PosisjonMedAvstand) o;
    return Objects.equals(this.vegsystemreferanse, posisjonMedAvstand.vegsystemreferanse) &&
        Objects.equals(this.veglenkesekvens, posisjonMedAvstand.veglenkesekvens) &&
        Objects.equals(this.geometri, posisjonMedAvstand.geometri) &&
        Objects.equals(this.kommune, posisjonMedAvstand.kommune) &&
        Objects.equals(this.avstand, posisjonMedAvstand.avstand);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vegsystemreferanse, veglenkesekvens, geometri, kommune, avstand);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PosisjonMedAvstand {\n");
    sb.append("    vegsystemreferanse: ").append(toIndentedString(vegsystemreferanse)).append("\n");
    sb.append("    veglenkesekvens: ").append(toIndentedString(veglenkesekvens)).append("\n");
    sb.append("    geometri: ").append(toIndentedString(geometri)).append("\n");
    sb.append("    kommune: ").append(toIndentedString(kommune)).append("\n");
    sb.append("    avstand: ").append(toIndentedString(avstand)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

