/*
 * NVDB API Les Vegnett
 * Dette API-et brukes til å lese vegnettelementer. Les mer om bruk av API-et på https://nvdb.test.atlas.vegvesen.no/produkter/nvdbapil/v4/Vegnett
 *
 * The version of the OpenAPI document: v4
 * Contact: nvdb@vegvesen.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.vegvesen.vt.nvdb.vegnett.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import no.vegvesen.vt.nvdb.vegnett.model.Segment;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Punkt
 */
@JsonPropertyOrder({
  Punkt.JSON_PROPERTY_VEGLENKESEKVENSID,
  Punkt.JSON_PROPERTY_RELATIV_POSISJON,
  Punkt.JSON_PROPERTY_KORTFORM
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
@JsonIgnoreProperties(
  value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)

public class Punkt extends Segment {
  public static final String JSON_PROPERTY_VEGLENKESEKVENSID = "veglenkesekvensid";
  @jakarta.annotation.Nonnull
  private Long veglenkesekvensid;

  public static final String JSON_PROPERTY_RELATIV_POSISJON = "relativPosisjon";
  @jakarta.annotation.Nonnull
  private Double relativPosisjon;

  public static final String JSON_PROPERTY_KORTFORM = "kortform";
  @jakarta.annotation.Nonnull
  private String kortform;

  public Punkt() {

  }

  public Punkt veglenkesekvensid(@jakarta.annotation.Nonnull Long veglenkesekvensid) {
    
    this.veglenkesekvensid = veglenkesekvensid;
    return this;
  }

  /**
   * Get veglenkesekvensid
   * @return veglenkesekvensid
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VEGLENKESEKVENSID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getVeglenkesekvensid() {
    return veglenkesekvensid;
  }


  @JsonProperty(JSON_PROPERTY_VEGLENKESEKVENSID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVeglenkesekvensid(@jakarta.annotation.Nonnull Long veglenkesekvensid) {
    this.veglenkesekvensid = veglenkesekvensid;
  }

  public Punkt relativPosisjon(@jakarta.annotation.Nonnull Double relativPosisjon) {
    
    this.relativPosisjon = relativPosisjon;
    return this;
  }

  /**
   * Get relativPosisjon
   * @return relativPosisjon
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RELATIV_POSISJON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getRelativPosisjon() {
    return relativPosisjon;
  }


  @JsonProperty(JSON_PROPERTY_RELATIV_POSISJON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRelativPosisjon(@jakarta.annotation.Nonnull Double relativPosisjon) {
    this.relativPosisjon = relativPosisjon;
  }

  public Punkt kortform(@jakarta.annotation.Nonnull String kortform) {
    
    this.kortform = kortform;
    return this;
  }

  /**
   * Get kortform
   * @return kortform
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_KORTFORM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKortform() {
    return kortform;
  }


  @JsonProperty(JSON_PROPERTY_KORTFORM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKortform(@jakarta.annotation.Nonnull String kortform) {
    this.kortform = kortform;
  }


  @Override
  public Punkt type(@jakarta.annotation.Nonnull String type) {
    this.setType(type);
    return this;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Punkt punkt = (Punkt) o;
    return Objects.equals(this.veglenkesekvensid, punkt.veglenkesekvensid) &&
        Objects.equals(this.relativPosisjon, punkt.relativPosisjon) &&
        Objects.equals(this.kortform, punkt.kortform) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(veglenkesekvensid, relativPosisjon, kortform, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Punkt {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    veglenkesekvensid: ").append(toIndentedString(veglenkesekvensid)).append("\n");
    sb.append("    relativPosisjon: ").append(toIndentedString(relativPosisjon)).append("\n");
    sb.append("    kortform: ").append(toIndentedString(kortform)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

