/*
 * NVDB API Les Vegnett
 * Dette API-et brukes til å lese vegnettelementer. Les mer om bruk av API-et på https://nvdb.test.atlas.vegvesen.no/produkter/nvdbapil/v4/Vegnett
 *
 * The version of the OpenAPI document: v4
 * Contact: nvdb@vegvesen.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.vegvesen.vt.nvdb.vegnett.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import no.vegvesen.vt.nvdb.vegnett.model.Adresse;
import no.vegvesen.vt.nvdb.vegnett.model.Detaljniva;
import no.vegvesen.vt.nvdb.vegnett.model.GeometriMedKvalitet;
import no.vegvesen.vt.nvdb.vegnett.model.Kontraktsomrade;
import no.vegvesen.vt.nvdb.vegnett.model.Malemetode;
import no.vegvesen.vt.nvdb.vegnett.model.Metadata;
import no.vegvesen.vt.nvdb.vegnett.model.Riksvegrute;
import no.vegvesen.vt.nvdb.vegnett.model.Superstedfesting;
import no.vegvesen.vt.nvdb.vegnett.model.TypeVeg;
import no.vegvesen.vt.nvdb.vegnett.model.TypeVegSosi;
import no.vegvesen.vt.nvdb.vegnett.model.VeglenkeType;
import no.vegvesen.vt.nvdb.vegnett.model.Vegsystemreferanse;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Rutesegment
 */
@JsonPropertyOrder({
  Rutesegment.JSON_PROPERTY_VEGLENKESEKVENSID,
  Rutesegment.JSON_PROPERTY_HREF,
  Rutesegment.JSON_PROPERTY_METADATA,
  Rutesegment.JSON_PROPERTY_STARTPOSISJON,
  Rutesegment.JSON_PROPERTY_SLUTTPOSISJON,
  Rutesegment.JSON_PROPERTY_KORTFORM,
  Rutesegment.JSON_PROPERTY_VEGLENKENUMMER,
  Rutesegment.JSON_PROPERTY_SEGMENTNUMMER,
  Rutesegment.JSON_PROPERTY_STARTNODE,
  Rutesegment.JSON_PROPERTY_SLUTTNODE,
  Rutesegment.JSON_PROPERTY_REFERANSE,
  Rutesegment.JSON_PROPERTY_TYPE,
  Rutesegment.JSON_PROPERTY_DETALJNIVå,
  Rutesegment.JSON_PROPERTY_TYPE_VEG,
  Rutesegment.JSON_PROPERTY_TYPE_VEG_SOSI,
  Rutesegment.JSON_PROPERTY_MåLEMETODE,
  Rutesegment.JSON_PROPERTY_MåLEDATO,
  Rutesegment.JSON_PROPERTY_SUPERSTEDFESTING,
  Rutesegment.JSON_PROPERTY_FELTOVERSIKT,
  Rutesegment.JSON_PROPERTY_GEOMETRI,
  Rutesegment.JSON_PROPERTY_LENGDE,
  Rutesegment.JSON_PROPERTY_FYLKE,
  Rutesegment.JSON_PROPERTY_KOMMUNE,
  Rutesegment.JSON_PROPERTY_VEGSYSTEMREFERANSE,
  Rutesegment.JSON_PROPERTY_KONTRAKTSOMRåDER,
  Rutesegment.JSON_PROPERTY_RIKSVEGRUTER,
  Rutesegment.JSON_PROPERTY_ADRESSE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class Rutesegment {
  public static final String JSON_PROPERTY_VEGLENKESEKVENSID = "veglenkesekvensid";
  @jakarta.annotation.Nonnull
  private Long veglenkesekvensid;

  public static final String JSON_PROPERTY_HREF = "href";
  @jakarta.annotation.Nonnull
  private String href;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @jakarta.annotation.Nonnull
  private Metadata metadata;

  public static final String JSON_PROPERTY_STARTPOSISJON = "startposisjon";
  @jakarta.annotation.Nonnull
  private Double startposisjon;

  public static final String JSON_PROPERTY_SLUTTPOSISJON = "sluttposisjon";
  @jakarta.annotation.Nonnull
  private Double sluttposisjon;

  public static final String JSON_PROPERTY_KORTFORM = "kortform";
  @jakarta.annotation.Nonnull
  private String kortform;

  public static final String JSON_PROPERTY_VEGLENKENUMMER = "veglenkenummer";
  @jakarta.annotation.Nonnull
  private Integer veglenkenummer;

  public static final String JSON_PROPERTY_SEGMENTNUMMER = "segmentnummer";
  @jakarta.annotation.Nonnull
  private Integer segmentnummer;

  public static final String JSON_PROPERTY_STARTNODE = "startnode";
  @jakarta.annotation.Nullable
  private String startnode;

  public static final String JSON_PROPERTY_SLUTTNODE = "sluttnode";
  @jakarta.annotation.Nullable
  private String sluttnode;

  public static final String JSON_PROPERTY_REFERANSE = "referanse";
  @jakarta.annotation.Nonnull
  private String referanse;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private VeglenkeType type;

  public static final String JSON_PROPERTY_DETALJNIVå = "detaljnivå";
  @jakarta.annotation.Nonnull
  private Detaljniva detaljnivå;

  public static final String JSON_PROPERTY_TYPE_VEG = "typeVeg";
  @jakarta.annotation.Nonnull
  private TypeVeg typeVeg;

  public static final String JSON_PROPERTY_TYPE_VEG_SOSI = "typeVeg_sosi";
  @jakarta.annotation.Nonnull
  private TypeVegSosi typeVegSosi;

  public static final String JSON_PROPERTY_MåLEMETODE = "målemetode";
  @jakarta.annotation.Nonnull
  private Malemetode målemetode;

  public static final String JSON_PROPERTY_MåLEDATO = "måledato";
  @jakarta.annotation.Nullable
  private LocalDate måledato;

  public static final String JSON_PROPERTY_SUPERSTEDFESTING = "superstedfesting";
  @jakarta.annotation.Nullable
  private Superstedfesting superstedfesting;

  public static final String JSON_PROPERTY_FELTOVERSIKT = "feltoversikt";
  @jakarta.annotation.Nullable
  private List<String> feltoversikt = new ArrayList<>();

  public static final String JSON_PROPERTY_GEOMETRI = "geometri";
  @jakarta.annotation.Nonnull
  private GeometriMedKvalitet geometri;

  public static final String JSON_PROPERTY_LENGDE = "lengde";
  @jakarta.annotation.Nonnull
  private Double lengde;

  public static final String JSON_PROPERTY_FYLKE = "fylke";
  @jakarta.annotation.Nonnull
  private Integer fylke;

  public static final String JSON_PROPERTY_KOMMUNE = "kommune";
  @jakarta.annotation.Nonnull
  private Integer kommune;

  public static final String JSON_PROPERTY_VEGSYSTEMREFERANSE = "vegsystemreferanse";
  @jakarta.annotation.Nonnull
  private Vegsystemreferanse vegsystemreferanse;

  public static final String JSON_PROPERTY_KONTRAKTSOMRåDER = "kontraktsområder";
  @jakarta.annotation.Nonnull
  private List<Kontraktsomrade> kontraktsområder = new ArrayList<>();

  public static final String JSON_PROPERTY_RIKSVEGRUTER = "riksvegruter";
  @jakarta.annotation.Nonnull
  private List<Riksvegrute> riksvegruter = new ArrayList<>();

  public static final String JSON_PROPERTY_ADRESSE = "adresse";
  @jakarta.annotation.Nullable
  private Adresse adresse;

  public Rutesegment() {
  }

  public Rutesegment veglenkesekvensid(@jakarta.annotation.Nonnull Long veglenkesekvensid) {
    
    this.veglenkesekvensid = veglenkesekvensid;
    return this;
  }

  /**
   * Get veglenkesekvensid
   * @return veglenkesekvensid
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VEGLENKESEKVENSID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getVeglenkesekvensid() {
    return veglenkesekvensid;
  }


  @JsonProperty(JSON_PROPERTY_VEGLENKESEKVENSID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVeglenkesekvensid(@jakarta.annotation.Nonnull Long veglenkesekvensid) {
    this.veglenkesekvensid = veglenkesekvensid;
  }

  public Rutesegment href(@jakarta.annotation.Nonnull String href) {
    
    this.href = href;
    return this;
  }

  /**
   * Get href
   * @return href
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getHref() {
    return href;
  }


  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHref(@jakarta.annotation.Nonnull String href) {
    this.href = href;
  }

  public Rutesegment metadata(@jakarta.annotation.Nonnull Metadata metadata) {
    
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Metadata getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMetadata(@jakarta.annotation.Nonnull Metadata metadata) {
    this.metadata = metadata;
  }

  public Rutesegment startposisjon(@jakarta.annotation.Nonnull Double startposisjon) {
    
    this.startposisjon = startposisjon;
    return this;
  }

  /**
   * Get startposisjon
   * @return startposisjon
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STARTPOSISJON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getStartposisjon() {
    return startposisjon;
  }


  @JsonProperty(JSON_PROPERTY_STARTPOSISJON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStartposisjon(@jakarta.annotation.Nonnull Double startposisjon) {
    this.startposisjon = startposisjon;
  }

  public Rutesegment sluttposisjon(@jakarta.annotation.Nonnull Double sluttposisjon) {
    
    this.sluttposisjon = sluttposisjon;
    return this;
  }

  /**
   * Get sluttposisjon
   * @return sluttposisjon
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SLUTTPOSISJON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getSluttposisjon() {
    return sluttposisjon;
  }


  @JsonProperty(JSON_PROPERTY_SLUTTPOSISJON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSluttposisjon(@jakarta.annotation.Nonnull Double sluttposisjon) {
    this.sluttposisjon = sluttposisjon;
  }

  public Rutesegment kortform(@jakarta.annotation.Nonnull String kortform) {
    
    this.kortform = kortform;
    return this;
  }

  /**
   * Get kortform
   * @return kortform
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_KORTFORM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKortform() {
    return kortform;
  }


  @JsonProperty(JSON_PROPERTY_KORTFORM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKortform(@jakarta.annotation.Nonnull String kortform) {
    this.kortform = kortform;
  }

  public Rutesegment veglenkenummer(@jakarta.annotation.Nonnull Integer veglenkenummer) {
    
    this.veglenkenummer = veglenkenummer;
    return this;
  }

  /**
   * Get veglenkenummer
   * @return veglenkenummer
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VEGLENKENUMMER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getVeglenkenummer() {
    return veglenkenummer;
  }


  @JsonProperty(JSON_PROPERTY_VEGLENKENUMMER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVeglenkenummer(@jakarta.annotation.Nonnull Integer veglenkenummer) {
    this.veglenkenummer = veglenkenummer;
  }

  public Rutesegment segmentnummer(@jakarta.annotation.Nonnull Integer segmentnummer) {
    
    this.segmentnummer = segmentnummer;
    return this;
  }

  /**
   * Get segmentnummer
   * @return segmentnummer
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SEGMENTNUMMER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSegmentnummer() {
    return segmentnummer;
  }


  @JsonProperty(JSON_PROPERTY_SEGMENTNUMMER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSegmentnummer(@jakarta.annotation.Nonnull Integer segmentnummer) {
    this.segmentnummer = segmentnummer;
  }

  public Rutesegment startnode(@jakarta.annotation.Nullable String startnode) {
    
    this.startnode = startnode;
    return this;
  }

  /**
   * Get startnode
   * @return startnode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STARTNODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStartnode() {
    return startnode;
  }


  @JsonProperty(JSON_PROPERTY_STARTNODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartnode(@jakarta.annotation.Nullable String startnode) {
    this.startnode = startnode;
  }

  public Rutesegment sluttnode(@jakarta.annotation.Nullable String sluttnode) {
    
    this.sluttnode = sluttnode;
    return this;
  }

  /**
   * Get sluttnode
   * @return sluttnode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SLUTTNODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSluttnode() {
    return sluttnode;
  }


  @JsonProperty(JSON_PROPERTY_SLUTTNODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSluttnode(@jakarta.annotation.Nullable String sluttnode) {
    this.sluttnode = sluttnode;
  }

  public Rutesegment referanse(@jakarta.annotation.Nonnull String referanse) {
    
    this.referanse = referanse;
    return this;
  }

  /**
   * Get referanse
   * @return referanse
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REFERANSE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getReferanse() {
    return referanse;
  }


  @JsonProperty(JSON_PROPERTY_REFERANSE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReferanse(@jakarta.annotation.Nonnull String referanse) {
    this.referanse = referanse;
  }

  public Rutesegment type(@jakarta.annotation.Nonnull VeglenkeType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public VeglenkeType getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull VeglenkeType type) {
    this.type = type;
  }

  public Rutesegment detaljnivå(@jakarta.annotation.Nonnull Detaljniva detaljnivå) {
    
    this.detaljnivå = detaljnivå;
    return this;
  }

  /**
   * Get detaljnivå
   * @return detaljnivå
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DETALJNIVå)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Detaljniva getDetaljnivå() {
    return detaljnivå;
  }


  @JsonProperty(JSON_PROPERTY_DETALJNIVå)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDetaljnivå(@jakarta.annotation.Nonnull Detaljniva detaljnivå) {
    this.detaljnivå = detaljnivå;
  }

  public Rutesegment typeVeg(@jakarta.annotation.Nonnull TypeVeg typeVeg) {
    
    this.typeVeg = typeVeg;
    return this;
  }

  /**
   * Get typeVeg
   * @return typeVeg
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE_VEG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeVeg getTypeVeg() {
    return typeVeg;
  }


  @JsonProperty(JSON_PROPERTY_TYPE_VEG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTypeVeg(@jakarta.annotation.Nonnull TypeVeg typeVeg) {
    this.typeVeg = typeVeg;
  }

  public Rutesegment typeVegSosi(@jakarta.annotation.Nonnull TypeVegSosi typeVegSosi) {
    
    this.typeVegSosi = typeVegSosi;
    return this;
  }

  /**
   * Get typeVegSosi
   * @return typeVegSosi
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE_VEG_SOSI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeVegSosi getTypeVegSosi() {
    return typeVegSosi;
  }


  @JsonProperty(JSON_PROPERTY_TYPE_VEG_SOSI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTypeVegSosi(@jakarta.annotation.Nonnull TypeVegSosi typeVegSosi) {
    this.typeVegSosi = typeVegSosi;
  }

  public Rutesegment målemetode(@jakarta.annotation.Nonnull Malemetode målemetode) {
    
    this.målemetode = målemetode;
    return this;
  }

  /**
   * Get målemetode
   * @return målemetode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MåLEMETODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Malemetode getMålemetode() {
    return målemetode;
  }


  @JsonProperty(JSON_PROPERTY_MåLEMETODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMålemetode(@jakarta.annotation.Nonnull Malemetode målemetode) {
    this.målemetode = målemetode;
  }

  public Rutesegment måledato(@jakarta.annotation.Nullable LocalDate måledato) {
    
    this.måledato = måledato;
    return this;
  }

  /**
   * Get måledato
   * @return måledato
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MåLEDATO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getMåledato() {
    return måledato;
  }


  @JsonProperty(JSON_PROPERTY_MåLEDATO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMåledato(@jakarta.annotation.Nullable LocalDate måledato) {
    this.måledato = måledato;
  }

  public Rutesegment superstedfesting(@jakarta.annotation.Nullable Superstedfesting superstedfesting) {
    
    this.superstedfesting = superstedfesting;
    return this;
  }

  /**
   * Get superstedfesting
   * @return superstedfesting
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPERSTEDFESTING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Superstedfesting getSuperstedfesting() {
    return superstedfesting;
  }


  @JsonProperty(JSON_PROPERTY_SUPERSTEDFESTING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuperstedfesting(@jakarta.annotation.Nullable Superstedfesting superstedfesting) {
    this.superstedfesting = superstedfesting;
  }

  public Rutesegment feltoversikt(@jakarta.annotation.Nullable List<String> feltoversikt) {
    
    this.feltoversikt = feltoversikt;
    return this;
  }

  public Rutesegment addFeltoversiktItem(String feltoversiktItem) {
    if (this.feltoversikt == null) {
      this.feltoversikt = new ArrayList<>();
    }
    this.feltoversikt.add(feltoversiktItem);
    return this;
  }

  /**
   * Get feltoversikt
   * @return feltoversikt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FELTOVERSIKT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getFeltoversikt() {
    return feltoversikt;
  }


  @JsonProperty(JSON_PROPERTY_FELTOVERSIKT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFeltoversikt(@jakarta.annotation.Nullable List<String> feltoversikt) {
    this.feltoversikt = feltoversikt;
  }

  public Rutesegment geometri(@jakarta.annotation.Nonnull GeometriMedKvalitet geometri) {
    
    this.geometri = geometri;
    return this;
  }

  /**
   * Get geometri
   * @return geometri
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GEOMETRI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public GeometriMedKvalitet getGeometri() {
    return geometri;
  }


  @JsonProperty(JSON_PROPERTY_GEOMETRI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGeometri(@jakarta.annotation.Nonnull GeometriMedKvalitet geometri) {
    this.geometri = geometri;
  }

  public Rutesegment lengde(@jakarta.annotation.Nonnull Double lengde) {
    
    this.lengde = lengde;
    return this;
  }

  /**
   * Get lengde
   * @return lengde
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LENGDE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getLengde() {
    return lengde;
  }


  @JsonProperty(JSON_PROPERTY_LENGDE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLengde(@jakarta.annotation.Nonnull Double lengde) {
    this.lengde = lengde;
  }

  public Rutesegment fylke(@jakarta.annotation.Nonnull Integer fylke) {
    
    this.fylke = fylke;
    return this;
  }

  /**
   * Get fylke
   * @return fylke
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FYLKE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getFylke() {
    return fylke;
  }


  @JsonProperty(JSON_PROPERTY_FYLKE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFylke(@jakarta.annotation.Nonnull Integer fylke) {
    this.fylke = fylke;
  }

  public Rutesegment kommune(@jakarta.annotation.Nonnull Integer kommune) {
    
    this.kommune = kommune;
    return this;
  }

  /**
   * Get kommune
   * @return kommune
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_KOMMUNE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getKommune() {
    return kommune;
  }


  @JsonProperty(JSON_PROPERTY_KOMMUNE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKommune(@jakarta.annotation.Nonnull Integer kommune) {
    this.kommune = kommune;
  }

  public Rutesegment vegsystemreferanse(@jakarta.annotation.Nonnull Vegsystemreferanse vegsystemreferanse) {
    
    this.vegsystemreferanse = vegsystemreferanse;
    return this;
  }

  /**
   * Get vegsystemreferanse
   * @return vegsystemreferanse
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VEGSYSTEMREFERANSE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Vegsystemreferanse getVegsystemreferanse() {
    return vegsystemreferanse;
  }


  @JsonProperty(JSON_PROPERTY_VEGSYSTEMREFERANSE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVegsystemreferanse(@jakarta.annotation.Nonnull Vegsystemreferanse vegsystemreferanse) {
    this.vegsystemreferanse = vegsystemreferanse;
  }

  public Rutesegment kontraktsområder(@jakarta.annotation.Nonnull List<Kontraktsomrade> kontraktsområder) {
    
    this.kontraktsområder = kontraktsområder;
    return this;
  }

  public Rutesegment addKontraktsområderItem(Kontraktsomrade kontraktsområderItem) {
    if (this.kontraktsområder == null) {
      this.kontraktsområder = new ArrayList<>();
    }
    this.kontraktsområder.add(kontraktsområderItem);
    return this;
  }

  /**
   * Get kontraktsområder
   * @return kontraktsområder
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_KONTRAKTSOMRåDER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Kontraktsomrade> getKontraktsområder() {
    return kontraktsområder;
  }


  @JsonProperty(JSON_PROPERTY_KONTRAKTSOMRåDER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKontraktsområder(@jakarta.annotation.Nonnull List<Kontraktsomrade> kontraktsområder) {
    this.kontraktsområder = kontraktsområder;
  }

  public Rutesegment riksvegruter(@jakarta.annotation.Nonnull List<Riksvegrute> riksvegruter) {
    
    this.riksvegruter = riksvegruter;
    return this;
  }

  public Rutesegment addRiksvegruterItem(Riksvegrute riksvegruterItem) {
    if (this.riksvegruter == null) {
      this.riksvegruter = new ArrayList<>();
    }
    this.riksvegruter.add(riksvegruterItem);
    return this;
  }

  /**
   * Get riksvegruter
   * @return riksvegruter
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RIKSVEGRUTER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Riksvegrute> getRiksvegruter() {
    return riksvegruter;
  }


  @JsonProperty(JSON_PROPERTY_RIKSVEGRUTER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRiksvegruter(@jakarta.annotation.Nonnull List<Riksvegrute> riksvegruter) {
    this.riksvegruter = riksvegruter;
  }

  public Rutesegment adresse(@jakarta.annotation.Nullable Adresse adresse) {
    
    this.adresse = adresse;
    return this;
  }

  /**
   * Get adresse
   * @return adresse
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADRESSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Adresse getAdresse() {
    return adresse;
  }


  @JsonProperty(JSON_PROPERTY_ADRESSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdresse(@jakarta.annotation.Nullable Adresse adresse) {
    this.adresse = adresse;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Rutesegment rutesegment = (Rutesegment) o;
    return Objects.equals(this.veglenkesekvensid, rutesegment.veglenkesekvensid) &&
        Objects.equals(this.href, rutesegment.href) &&
        Objects.equals(this.metadata, rutesegment.metadata) &&
        Objects.equals(this.startposisjon, rutesegment.startposisjon) &&
        Objects.equals(this.sluttposisjon, rutesegment.sluttposisjon) &&
        Objects.equals(this.kortform, rutesegment.kortform) &&
        Objects.equals(this.veglenkenummer, rutesegment.veglenkenummer) &&
        Objects.equals(this.segmentnummer, rutesegment.segmentnummer) &&
        Objects.equals(this.startnode, rutesegment.startnode) &&
        Objects.equals(this.sluttnode, rutesegment.sluttnode) &&
        Objects.equals(this.referanse, rutesegment.referanse) &&
        Objects.equals(this.type, rutesegment.type) &&
        Objects.equals(this.detaljnivå, rutesegment.detaljnivå) &&
        Objects.equals(this.typeVeg, rutesegment.typeVeg) &&
        Objects.equals(this.typeVegSosi, rutesegment.typeVegSosi) &&
        Objects.equals(this.målemetode, rutesegment.målemetode) &&
        Objects.equals(this.måledato, rutesegment.måledato) &&
        Objects.equals(this.superstedfesting, rutesegment.superstedfesting) &&
        Objects.equals(this.feltoversikt, rutesegment.feltoversikt) &&
        Objects.equals(this.geometri, rutesegment.geometri) &&
        Objects.equals(this.lengde, rutesegment.lengde) &&
        Objects.equals(this.fylke, rutesegment.fylke) &&
        Objects.equals(this.kommune, rutesegment.kommune) &&
        Objects.equals(this.vegsystemreferanse, rutesegment.vegsystemreferanse) &&
        Objects.equals(this.kontraktsområder, rutesegment.kontraktsområder) &&
        Objects.equals(this.riksvegruter, rutesegment.riksvegruter) &&
        Objects.equals(this.adresse, rutesegment.adresse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(veglenkesekvensid, href, metadata, startposisjon, sluttposisjon, kortform, veglenkenummer, segmentnummer, startnode, sluttnode, referanse, type, detaljnivå, typeVeg, typeVegSosi, målemetode, måledato, superstedfesting, feltoversikt, geometri, lengde, fylke, kommune, vegsystemreferanse, kontraktsområder, riksvegruter, adresse);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Rutesegment {\n");
    sb.append("    veglenkesekvensid: ").append(toIndentedString(veglenkesekvensid)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    startposisjon: ").append(toIndentedString(startposisjon)).append("\n");
    sb.append("    sluttposisjon: ").append(toIndentedString(sluttposisjon)).append("\n");
    sb.append("    kortform: ").append(toIndentedString(kortform)).append("\n");
    sb.append("    veglenkenummer: ").append(toIndentedString(veglenkenummer)).append("\n");
    sb.append("    segmentnummer: ").append(toIndentedString(segmentnummer)).append("\n");
    sb.append("    startnode: ").append(toIndentedString(startnode)).append("\n");
    sb.append("    sluttnode: ").append(toIndentedString(sluttnode)).append("\n");
    sb.append("    referanse: ").append(toIndentedString(referanse)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    detaljnivå: ").append(toIndentedString(detaljnivå)).append("\n");
    sb.append("    typeVeg: ").append(toIndentedString(typeVeg)).append("\n");
    sb.append("    typeVegSosi: ").append(toIndentedString(typeVegSosi)).append("\n");
    sb.append("    målemetode: ").append(toIndentedString(målemetode)).append("\n");
    sb.append("    måledato: ").append(toIndentedString(måledato)).append("\n");
    sb.append("    superstedfesting: ").append(toIndentedString(superstedfesting)).append("\n");
    sb.append("    feltoversikt: ").append(toIndentedString(feltoversikt)).append("\n");
    sb.append("    geometri: ").append(toIndentedString(geometri)).append("\n");
    sb.append("    lengde: ").append(toIndentedString(lengde)).append("\n");
    sb.append("    fylke: ").append(toIndentedString(fylke)).append("\n");
    sb.append("    kommune: ").append(toIndentedString(kommune)).append("\n");
    sb.append("    vegsystemreferanse: ").append(toIndentedString(vegsystemreferanse)).append("\n");
    sb.append("    kontraktsområder: ").append(toIndentedString(kontraktsområder)).append("\n");
    sb.append("    riksvegruter: ").append(toIndentedString(riksvegruter)).append("\n");
    sb.append("    adresse: ").append(toIndentedString(adresse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

