/*
 * NVDB API Les Vegnett
 * Dette API-et brukes til å lese vegnettelementer. Les mer om bruk av API-et på https://nvdb.test.atlas.vegvesen.no/produkter/nvdbapil/v4/Vegnett
 *
 * The version of the OpenAPI document: v4
 * Contact: nvdb@vegvesen.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.vegvesen.vt.nvdb.vegnett.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import no.vegvesen.vt.nvdb.vegnett.model.Adresse;
import no.vegvesen.vt.nvdb.vegnett.model.GeometriMedKvalitet;
import no.vegvesen.vt.nvdb.vegnett.model.Kontraktsomrade;
import no.vegvesen.vt.nvdb.vegnett.model.Metadata;
import no.vegvesen.vt.nvdb.vegnett.model.Riksvegrute;
import no.vegvesen.vt.nvdb.vegnett.model.Superstedfesting;
import no.vegvesen.vt.nvdb.vegnett.model.Vegforvalter;
import no.vegvesen.vt.nvdb.vegnett.model.Vegsystemreferanse;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Veglenkesegment
 */
@JsonPropertyOrder({
  Veglenkesegment.JSON_PROPERTY_VEGLENKESEKVENSID,
  Veglenkesegment.JSON_PROPERTY_HREF,
  Veglenkesegment.JSON_PROPERTY_METADATA,
  Veglenkesegment.JSON_PROPERTY_STARTPOSISJON,
  Veglenkesegment.JSON_PROPERTY_SLUTTPOSISJON,
  Veglenkesegment.JSON_PROPERTY_KORTFORM,
  Veglenkesegment.JSON_PROPERTY_VEGLENKENUMMER,
  Veglenkesegment.JSON_PROPERTY_SEGMENTNUMMER,
  Veglenkesegment.JSON_PROPERTY_STARTNODE,
  Veglenkesegment.JSON_PROPERTY_SLUTTNODE,
  Veglenkesegment.JSON_PROPERTY_REFERANSE,
  Veglenkesegment.JSON_PROPERTY_TYPE,
  Veglenkesegment.JSON_PROPERTY_DETALJNIVå,
  Veglenkesegment.JSON_PROPERTY_TYPE_VEG,
  Veglenkesegment.JSON_PROPERTY_TYPE_VEG_SOSI,
  Veglenkesegment.JSON_PROPERTY_MåLEMETODE,
  Veglenkesegment.JSON_PROPERTY_MåLEDATO,
  Veglenkesegment.JSON_PROPERTY_SUPERSTEDFESTING,
  Veglenkesegment.JSON_PROPERTY_FELTOVERSIKT,
  Veglenkesegment.JSON_PROPERTY_GEOMETRI,
  Veglenkesegment.JSON_PROPERTY_LENGDE,
  Veglenkesegment.JSON_PROPERTY_FYLKE,
  Veglenkesegment.JSON_PROPERTY_KOMMUNE,
  Veglenkesegment.JSON_PROPERTY_VEGSYSTEMREFERANSE,
  Veglenkesegment.JSON_PROPERTY_KONTRAKTSOMRåDER,
  Veglenkesegment.JSON_PROPERTY_RIKSVEGRUTER,
  Veglenkesegment.JSON_PROPERTY_VEGFORVALTERE,
  Veglenkesegment.JSON_PROPERTY_ADRESSE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class Veglenkesegment {
  public static final String JSON_PROPERTY_VEGLENKESEKVENSID = "veglenkesekvensid";
  @jakarta.annotation.Nonnull
  private Long veglenkesekvensid;

  public static final String JSON_PROPERTY_HREF = "href";
  @jakarta.annotation.Nonnull
  private String href;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @jakarta.annotation.Nonnull
  private Metadata metadata;

  public static final String JSON_PROPERTY_STARTPOSISJON = "startposisjon";
  @jakarta.annotation.Nonnull
  private Double startposisjon;

  public static final String JSON_PROPERTY_SLUTTPOSISJON = "sluttposisjon";
  @jakarta.annotation.Nonnull
  private Double sluttposisjon;

  public static final String JSON_PROPERTY_KORTFORM = "kortform";
  @jakarta.annotation.Nonnull
  private String kortform;

  public static final String JSON_PROPERTY_VEGLENKENUMMER = "veglenkenummer";
  @jakarta.annotation.Nonnull
  private Integer veglenkenummer;

  public static final String JSON_PROPERTY_SEGMENTNUMMER = "segmentnummer";
  @jakarta.annotation.Nonnull
  private Integer segmentnummer;

  public static final String JSON_PROPERTY_STARTNODE = "startnode";
  @jakarta.annotation.Nonnull
  private String startnode;

  public static final String JSON_PROPERTY_SLUTTNODE = "sluttnode";
  @jakarta.annotation.Nonnull
  private String sluttnode;

  public static final String JSON_PROPERTY_REFERANSE = "referanse";
  @jakarta.annotation.Nonnull
  private String referanse;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    UKJENT(String.valueOf("Ukjent")),
    
    DETALJERT(String.valueOf("DETALJERT")),
    
    KONNEKTERING(String.valueOf("KONNEKTERING")),
    
    DETALJERT_KONNEKTERING(String.valueOf("DETALJERT_KONNEKTERING")),
    
    HOVED(String.valueOf("HOVED"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  /**
   * Gets or Sets detaljnivå
   */
  public enum DetaljnivEnum {
    VEGTRASE(String.valueOf("Vegtrase")),
    
    KJ_REBANE(String.valueOf("Kjørebane")),
    
    KJ_REFELT(String.valueOf("Kjørefelt")),
    
    VEGTRASE_OG_KJ_REBANE(String.valueOf("Vegtrase og kjørebane"));

    private String value;

    DetaljnivEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DetaljnivEnum fromValue(String value) {
      for (DetaljnivEnum b : DetaljnivEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DETALJNIVå = "detaljnivå";
  @jakarta.annotation.Nonnull
  private DetaljnivEnum detaljnivå;

  /**
   * Gets or Sets typeVeg
   */
  public enum TypeVegEnum {
    ENKEL_BILVEG(String.valueOf("Enkel bilveg")),
    
    KANALISERT_VEG(String.valueOf("Kanalisert veg")),
    
    RAMPE(String.valueOf("Rampe")),
    
    RUNDKJ_RING(String.valueOf("Rundkjøring")),
    
    BILFERJE(String.valueOf("Bilferje")),
    
    GANG_OG_SYKKELVEG(String.valueOf("Gang- og sykkelveg")),
    
    SYKKELVEG(String.valueOf("Sykkelveg")),
    
    GANGVEG(String.valueOf("Gangveg")),
    
    G_GATE(String.valueOf("Gågate")),
    
    FORTAU(String.valueOf("Fortau")),
    
    TRAPP(String.valueOf("Trapp")),
    
    GANGFELT(String.valueOf("Gangfelt")),
    
    GATETUN(String.valueOf("Gatetun")),
    
    PASSASJERFERJE(String.valueOf("Passasjerferje")),
    
    TRAKTORVEG(String.valueOf("Traktorveg")),
    
    STI(String.valueOf("Sti")),
    
    ANNET(String.valueOf("Annet"));

    private String value;

    TypeVegEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeVegEnum fromValue(String value) {
      for (TypeVegEnum b : TypeVegEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE_VEG = "typeVeg";
  @jakarta.annotation.Nonnull
  private TypeVegEnum typeVeg;

  /**
   * Gets or Sets typeVegSosi
   */
  public enum TypeVegSosiEnum {
    KANALISERT_VEG(String.valueOf("kanalisertVeg")),
    
    ENKEL_BILVEG(String.valueOf("enkelBilveg")),
    
    RAMPE(String.valueOf("rampe")),
    
    RUNDKJ_RING(String.valueOf("rundkjøring")),
    
    BILFERJE(String.valueOf("bilferje")),
    
    PASSASJERFERJE(String.valueOf("passasjerferje")),
    
    GANG_OG_SYKKELVEG(String.valueOf("gangOgSykkelveg")),
    
    SYKKELVEG(String.valueOf("sykkelveg")),
    
    GANGVEG(String.valueOf("gangveg")),
    
    G_GATE(String.valueOf("gågate")),
    
    FORTAU(String.valueOf("fortau")),
    
    TRAPP(String.valueOf("trapp")),
    
    GANGFELT(String.valueOf("gangfelt")),
    
    GATETUN(String.valueOf("gatetun")),
    
    TRAKTORVEG(String.valueOf("traktorveg")),
    
    STI(String.valueOf("sti")),
    
    ANNET(String.valueOf("annet"));

    private String value;

    TypeVegSosiEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeVegSosiEnum fromValue(String value) {
      for (TypeVegSosiEnum b : TypeVegSosiEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE_VEG_SOSI = "typeVeg_sosi";
  @jakarta.annotation.Nonnull
  private TypeVegSosiEnum typeVegSosi;

  /**
   * Gets or Sets målemetode
   */
  public enum MlemetodeEnum {
    METRERT(String.valueOf("Metrert")),
    
    GEOMETRISK(String.valueOf("Geometrisk"));

    private String value;

    MlemetodeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MlemetodeEnum fromValue(String value) {
      for (MlemetodeEnum b : MlemetodeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MåLEMETODE = "målemetode";
  @jakarta.annotation.Nonnull
  private MlemetodeEnum målemetode;

  public static final String JSON_PROPERTY_MåLEDATO = "måledato";
  @jakarta.annotation.Nullable
  private LocalDate måledato;

  public static final String JSON_PROPERTY_SUPERSTEDFESTING = "superstedfesting";
  @jakarta.annotation.Nullable
  private Superstedfesting superstedfesting;

  public static final String JSON_PROPERTY_FELTOVERSIKT = "feltoversikt";
  @jakarta.annotation.Nullable
  private List<String> feltoversikt = new ArrayList<>();

  public static final String JSON_PROPERTY_GEOMETRI = "geometri";
  @jakarta.annotation.Nonnull
  private GeometriMedKvalitet geometri;

  public static final String JSON_PROPERTY_LENGDE = "lengde";
  @jakarta.annotation.Nonnull
  private Double lengde;

  public static final String JSON_PROPERTY_FYLKE = "fylke";
  @jakarta.annotation.Nonnull
  private Integer fylke;

  public static final String JSON_PROPERTY_KOMMUNE = "kommune";
  @jakarta.annotation.Nonnull
  private Integer kommune;

  public static final String JSON_PROPERTY_VEGSYSTEMREFERANSE = "vegsystemreferanse";
  @jakarta.annotation.Nonnull
  private Vegsystemreferanse vegsystemreferanse;

  public static final String JSON_PROPERTY_KONTRAKTSOMRåDER = "kontraktsområder";
  @jakarta.annotation.Nullable
  private List<Kontraktsomrade> kontraktsområder = new ArrayList<>();

  public static final String JSON_PROPERTY_RIKSVEGRUTER = "riksvegruter";
  @jakarta.annotation.Nullable
  private List<Riksvegrute> riksvegruter = new ArrayList<>();

  public static final String JSON_PROPERTY_VEGFORVALTERE = "vegforvaltere";
  @jakarta.annotation.Nullable
  private List<Vegforvalter> vegforvaltere = new ArrayList<>();

  public static final String JSON_PROPERTY_ADRESSE = "adresse";
  @jakarta.annotation.Nullable
  private Adresse adresse;

  public Veglenkesegment() {
  }

  public Veglenkesegment veglenkesekvensid(@jakarta.annotation.Nonnull Long veglenkesekvensid) {
    
    this.veglenkesekvensid = veglenkesekvensid;
    return this;
  }

  /**
   * Get veglenkesekvensid
   * @return veglenkesekvensid
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VEGLENKESEKVENSID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getVeglenkesekvensid() {
    return veglenkesekvensid;
  }


  @JsonProperty(JSON_PROPERTY_VEGLENKESEKVENSID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVeglenkesekvensid(@jakarta.annotation.Nonnull Long veglenkesekvensid) {
    this.veglenkesekvensid = veglenkesekvensid;
  }

  public Veglenkesegment href(@jakarta.annotation.Nonnull String href) {
    
    this.href = href;
    return this;
  }

  /**
   * URL-en til den segmenterte veglenkesekvensen som dette segmentet tilhører
   * @return href
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getHref() {
    return href;
  }


  @JsonProperty(JSON_PROPERTY_HREF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHref(@jakarta.annotation.Nonnull String href) {
    this.href = href;
  }

  public Veglenkesegment metadata(@jakarta.annotation.Nonnull Metadata metadata) {
    
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Metadata getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMetadata(@jakarta.annotation.Nonnull Metadata metadata) {
    this.metadata = metadata;
  }

  public Veglenkesegment startposisjon(@jakarta.annotation.Nonnull Double startposisjon) {
    
    this.startposisjon = startposisjon;
    return this;
  }

  /**
   * Get startposisjon
   * @return startposisjon
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STARTPOSISJON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getStartposisjon() {
    return startposisjon;
  }


  @JsonProperty(JSON_PROPERTY_STARTPOSISJON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStartposisjon(@jakarta.annotation.Nonnull Double startposisjon) {
    this.startposisjon = startposisjon;
  }

  public Veglenkesegment sluttposisjon(@jakarta.annotation.Nonnull Double sluttposisjon) {
    
    this.sluttposisjon = sluttposisjon;
    return this;
  }

  /**
   * Get sluttposisjon
   * @return sluttposisjon
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SLUTTPOSISJON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getSluttposisjon() {
    return sluttposisjon;
  }


  @JsonProperty(JSON_PROPERTY_SLUTTPOSISJON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSluttposisjon(@jakarta.annotation.Nonnull Double sluttposisjon) {
    this.sluttposisjon = sluttposisjon;
  }

  public Veglenkesegment kortform(@jakarta.annotation.Nonnull String kortform) {
    
    this.kortform = kortform;
    return this;
  }

  /**
   * Get kortform
   * @return kortform
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_KORTFORM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKortform() {
    return kortform;
  }


  @JsonProperty(JSON_PROPERTY_KORTFORM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKortform(@jakarta.annotation.Nonnull String kortform) {
    this.kortform = kortform;
  }

  public Veglenkesegment veglenkenummer(@jakarta.annotation.Nonnull Integer veglenkenummer) {
    
    this.veglenkenummer = veglenkenummer;
    return this;
  }

  /**
   * Get veglenkenummer
   * @return veglenkenummer
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VEGLENKENUMMER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getVeglenkenummer() {
    return veglenkenummer;
  }


  @JsonProperty(JSON_PROPERTY_VEGLENKENUMMER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVeglenkenummer(@jakarta.annotation.Nonnull Integer veglenkenummer) {
    this.veglenkenummer = veglenkenummer;
  }

  public Veglenkesegment segmentnummer(@jakarta.annotation.Nonnull Integer segmentnummer) {
    
    this.segmentnummer = segmentnummer;
    return this;
  }

  /**
   * Get segmentnummer
   * @return segmentnummer
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SEGMENTNUMMER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSegmentnummer() {
    return segmentnummer;
  }


  @JsonProperty(JSON_PROPERTY_SEGMENTNUMMER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSegmentnummer(@jakarta.annotation.Nonnull Integer segmentnummer) {
    this.segmentnummer = segmentnummer;
  }

  public Veglenkesegment startnode(@jakarta.annotation.Nonnull String startnode) {
    
    this.startnode = startnode;
    return this;
  }

  /**
   * I V4 så er fiktive noder representert som posisjon@veglenkesekvens
   * @return startnode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STARTNODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStartnode() {
    return startnode;
  }


  @JsonProperty(JSON_PROPERTY_STARTNODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStartnode(@jakarta.annotation.Nonnull String startnode) {
    this.startnode = startnode;
  }

  public Veglenkesegment sluttnode(@jakarta.annotation.Nonnull String sluttnode) {
    
    this.sluttnode = sluttnode;
    return this;
  }

  /**
   * I V4 så er fiktive noder representert som posisjon@veglenkesekvens
   * @return sluttnode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SLUTTNODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSluttnode() {
    return sluttnode;
  }


  @JsonProperty(JSON_PROPERTY_SLUTTNODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSluttnode(@jakarta.annotation.Nonnull String sluttnode) {
    this.sluttnode = sluttnode;
  }

  public Veglenkesegment referanse(@jakarta.annotation.Nonnull String referanse) {
    
    this.referanse = referanse;
    return this;
  }

  /**
   * Kombinasjon av veglenkesekvensid, veglenkenummer og segmentnummer. Unik for hvert segment.
   * @return referanse
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REFERANSE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getReferanse() {
    return referanse;
  }


  @JsonProperty(JSON_PROPERTY_REFERANSE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReferanse(@jakarta.annotation.Nonnull String referanse) {
    this.referanse = referanse;
  }

  public Veglenkesegment type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public Veglenkesegment detaljnivå(@jakarta.annotation.Nonnull DetaljnivEnum detaljnivå) {
    
    this.detaljnivå = detaljnivå;
    return this;
  }

  /**
   * Get detaljnivå
   * @return detaljnivå
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DETALJNIVå)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public DetaljnivEnum getDetaljnivå() {
    return detaljnivå;
  }


  @JsonProperty(JSON_PROPERTY_DETALJNIVå)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDetaljnivå(@jakarta.annotation.Nonnull DetaljnivEnum detaljnivå) {
    this.detaljnivå = detaljnivå;
  }

  public Veglenkesegment typeVeg(@jakarta.annotation.Nonnull TypeVegEnum typeVeg) {
    
    this.typeVeg = typeVeg;
    return this;
  }

  /**
   * Get typeVeg
   * @return typeVeg
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE_VEG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeVegEnum getTypeVeg() {
    return typeVeg;
  }


  @JsonProperty(JSON_PROPERTY_TYPE_VEG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTypeVeg(@jakarta.annotation.Nonnull TypeVegEnum typeVeg) {
    this.typeVeg = typeVeg;
  }

  public Veglenkesegment typeVegSosi(@jakarta.annotation.Nonnull TypeVegSosiEnum typeVegSosi) {
    
    this.typeVegSosi = typeVegSosi;
    return this;
  }

  /**
   * Get typeVegSosi
   * @return typeVegSosi
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE_VEG_SOSI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeVegSosiEnum getTypeVegSosi() {
    return typeVegSosi;
  }


  @JsonProperty(JSON_PROPERTY_TYPE_VEG_SOSI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTypeVegSosi(@jakarta.annotation.Nonnull TypeVegSosiEnum typeVegSosi) {
    this.typeVegSosi = typeVegSosi;
  }

  public Veglenkesegment målemetode(@jakarta.annotation.Nonnull MlemetodeEnum målemetode) {
    
    this.målemetode = målemetode;
    return this;
  }

  /**
   * Get målemetode
   * @return målemetode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MåLEMETODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MlemetodeEnum getMålemetode() {
    return målemetode;
  }


  @JsonProperty(JSON_PROPERTY_MåLEMETODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMålemetode(@jakarta.annotation.Nonnull MlemetodeEnum målemetode) {
    this.målemetode = målemetode;
  }

  public Veglenkesegment måledato(@jakarta.annotation.Nullable LocalDate måledato) {
    
    this.måledato = måledato;
    return this;
  }

  /**
   * Get måledato
   * @return måledato
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MåLEDATO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getMåledato() {
    return måledato;
  }


  @JsonProperty(JSON_PROPERTY_MåLEDATO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMåledato(@jakarta.annotation.Nullable LocalDate måledato) {
    this.måledato = måledato;
  }

  public Veglenkesegment superstedfesting(@jakarta.annotation.Nullable Superstedfesting superstedfesting) {
    
    this.superstedfesting = superstedfesting;
    return this;
  }

  /**
   * Get superstedfesting
   * @return superstedfesting
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPERSTEDFESTING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Superstedfesting getSuperstedfesting() {
    return superstedfesting;
  }


  @JsonProperty(JSON_PROPERTY_SUPERSTEDFESTING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuperstedfesting(@jakarta.annotation.Nullable Superstedfesting superstedfesting) {
    this.superstedfesting = superstedfesting;
  }

  public Veglenkesegment feltoversikt(@jakarta.annotation.Nullable List<String> feltoversikt) {
    
    this.feltoversikt = feltoversikt;
    return this;
  }

  public Veglenkesegment addFeltoversiktItem(String feltoversiktItem) {
    if (this.feltoversikt == null) {
      this.feltoversikt = new ArrayList<>();
    }
    this.feltoversikt.add(feltoversiktItem);
    return this;
  }

  /**
   * Get feltoversikt
   * @return feltoversikt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FELTOVERSIKT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getFeltoversikt() {
    return feltoversikt;
  }


  @JsonProperty(JSON_PROPERTY_FELTOVERSIKT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFeltoversikt(@jakarta.annotation.Nullable List<String> feltoversikt) {
    this.feltoversikt = feltoversikt;
  }

  public Veglenkesegment geometri(@jakarta.annotation.Nonnull GeometriMedKvalitet geometri) {
    
    this.geometri = geometri;
    return this;
  }

  /**
   * Get geometri
   * @return geometri
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GEOMETRI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public GeometriMedKvalitet getGeometri() {
    return geometri;
  }


  @JsonProperty(JSON_PROPERTY_GEOMETRI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGeometri(@jakarta.annotation.Nonnull GeometriMedKvalitet geometri) {
    this.geometri = geometri;
  }

  public Veglenkesegment lengde(@jakarta.annotation.Nonnull Double lengde) {
    
    this.lengde = lengde;
    return this;
  }

  /**
   * Get lengde
   * @return lengde
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LENGDE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getLengde() {
    return lengde;
  }


  @JsonProperty(JSON_PROPERTY_LENGDE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLengde(@jakarta.annotation.Nonnull Double lengde) {
    this.lengde = lengde;
  }

  public Veglenkesegment fylke(@jakarta.annotation.Nonnull Integer fylke) {
    
    this.fylke = fylke;
    return this;
  }

  /**
   * Get fylke
   * @return fylke
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FYLKE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getFylke() {
    return fylke;
  }


  @JsonProperty(JSON_PROPERTY_FYLKE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFylke(@jakarta.annotation.Nonnull Integer fylke) {
    this.fylke = fylke;
  }

  public Veglenkesegment kommune(@jakarta.annotation.Nonnull Integer kommune) {
    
    this.kommune = kommune;
    return this;
  }

  /**
   * Get kommune
   * @return kommune
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_KOMMUNE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getKommune() {
    return kommune;
  }


  @JsonProperty(JSON_PROPERTY_KOMMUNE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKommune(@jakarta.annotation.Nonnull Integer kommune) {
    this.kommune = kommune;
  }

  public Veglenkesegment vegsystemreferanse(@jakarta.annotation.Nonnull Vegsystemreferanse vegsystemreferanse) {
    
    this.vegsystemreferanse = vegsystemreferanse;
    return this;
  }

  /**
   * Get vegsystemreferanse
   * @return vegsystemreferanse
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VEGSYSTEMREFERANSE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Vegsystemreferanse getVegsystemreferanse() {
    return vegsystemreferanse;
  }


  @JsonProperty(JSON_PROPERTY_VEGSYSTEMREFERANSE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVegsystemreferanse(@jakarta.annotation.Nonnull Vegsystemreferanse vegsystemreferanse) {
    this.vegsystemreferanse = vegsystemreferanse;
  }

  public Veglenkesegment kontraktsområder(@jakarta.annotation.Nullable List<Kontraktsomrade> kontraktsområder) {
    
    this.kontraktsområder = kontraktsområder;
    return this;
  }

  public Veglenkesegment addKontraktsområderItem(Kontraktsomrade kontraktsområderItem) {
    if (this.kontraktsområder == null) {
      this.kontraktsområder = new ArrayList<>();
    }
    this.kontraktsområder.add(kontraktsområderItem);
    return this;
  }

  /**
   * Get kontraktsområder
   * @return kontraktsområder
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KONTRAKTSOMRåDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Kontraktsomrade> getKontraktsområder() {
    return kontraktsområder;
  }


  @JsonProperty(JSON_PROPERTY_KONTRAKTSOMRåDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKontraktsområder(@jakarta.annotation.Nullable List<Kontraktsomrade> kontraktsområder) {
    this.kontraktsområder = kontraktsområder;
  }

  public Veglenkesegment riksvegruter(@jakarta.annotation.Nullable List<Riksvegrute> riksvegruter) {
    
    this.riksvegruter = riksvegruter;
    return this;
  }

  public Veglenkesegment addRiksvegruterItem(Riksvegrute riksvegruterItem) {
    if (this.riksvegruter == null) {
      this.riksvegruter = new ArrayList<>();
    }
    this.riksvegruter.add(riksvegruterItem);
    return this;
  }

  /**
   * Get riksvegruter
   * @return riksvegruter
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RIKSVEGRUTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Riksvegrute> getRiksvegruter() {
    return riksvegruter;
  }


  @JsonProperty(JSON_PROPERTY_RIKSVEGRUTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRiksvegruter(@jakarta.annotation.Nullable List<Riksvegrute> riksvegruter) {
    this.riksvegruter = riksvegruter;
  }

  public Veglenkesegment vegforvaltere(@jakarta.annotation.Nullable List<Vegforvalter> vegforvaltere) {
    
    this.vegforvaltere = vegforvaltere;
    return this;
  }

  public Veglenkesegment addVegforvaltereItem(Vegforvalter vegforvaltereItem) {
    if (this.vegforvaltere == null) {
      this.vegforvaltere = new ArrayList<>();
    }
    this.vegforvaltere.add(vegforvaltereItem);
    return this;
  }

  /**
   * Get vegforvaltere
   * @return vegforvaltere
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VEGFORVALTERE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Vegforvalter> getVegforvaltere() {
    return vegforvaltere;
  }


  @JsonProperty(JSON_PROPERTY_VEGFORVALTERE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVegforvaltere(@jakarta.annotation.Nullable List<Vegforvalter> vegforvaltere) {
    this.vegforvaltere = vegforvaltere;
  }

  public Veglenkesegment adresse(@jakarta.annotation.Nullable Adresse adresse) {
    
    this.adresse = adresse;
    return this;
  }

  /**
   * Get adresse
   * @return adresse
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADRESSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Adresse getAdresse() {
    return adresse;
  }


  @JsonProperty(JSON_PROPERTY_ADRESSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdresse(@jakarta.annotation.Nullable Adresse adresse) {
    this.adresse = adresse;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Veglenkesegment veglenkesegment = (Veglenkesegment) o;
    return Objects.equals(this.veglenkesekvensid, veglenkesegment.veglenkesekvensid) &&
        Objects.equals(this.href, veglenkesegment.href) &&
        Objects.equals(this.metadata, veglenkesegment.metadata) &&
        Objects.equals(this.startposisjon, veglenkesegment.startposisjon) &&
        Objects.equals(this.sluttposisjon, veglenkesegment.sluttposisjon) &&
        Objects.equals(this.kortform, veglenkesegment.kortform) &&
        Objects.equals(this.veglenkenummer, veglenkesegment.veglenkenummer) &&
        Objects.equals(this.segmentnummer, veglenkesegment.segmentnummer) &&
        Objects.equals(this.startnode, veglenkesegment.startnode) &&
        Objects.equals(this.sluttnode, veglenkesegment.sluttnode) &&
        Objects.equals(this.referanse, veglenkesegment.referanse) &&
        Objects.equals(this.type, veglenkesegment.type) &&
        Objects.equals(this.detaljnivå, veglenkesegment.detaljnivå) &&
        Objects.equals(this.typeVeg, veglenkesegment.typeVeg) &&
        Objects.equals(this.typeVegSosi, veglenkesegment.typeVegSosi) &&
        Objects.equals(this.målemetode, veglenkesegment.målemetode) &&
        Objects.equals(this.måledato, veglenkesegment.måledato) &&
        Objects.equals(this.superstedfesting, veglenkesegment.superstedfesting) &&
        Objects.equals(this.feltoversikt, veglenkesegment.feltoversikt) &&
        Objects.equals(this.geometri, veglenkesegment.geometri) &&
        Objects.equals(this.lengde, veglenkesegment.lengde) &&
        Objects.equals(this.fylke, veglenkesegment.fylke) &&
        Objects.equals(this.kommune, veglenkesegment.kommune) &&
        Objects.equals(this.vegsystemreferanse, veglenkesegment.vegsystemreferanse) &&
        Objects.equals(this.kontraktsområder, veglenkesegment.kontraktsområder) &&
        Objects.equals(this.riksvegruter, veglenkesegment.riksvegruter) &&
        Objects.equals(this.vegforvaltere, veglenkesegment.vegforvaltere) &&
        Objects.equals(this.adresse, veglenkesegment.adresse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(veglenkesekvensid, href, metadata, startposisjon, sluttposisjon, kortform, veglenkenummer, segmentnummer, startnode, sluttnode, referanse, type, detaljnivå, typeVeg, typeVegSosi, målemetode, måledato, superstedfesting, feltoversikt, geometri, lengde, fylke, kommune, vegsystemreferanse, kontraktsområder, riksvegruter, vegforvaltere, adresse);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Veglenkesegment {\n");
    sb.append("    veglenkesekvensid: ").append(toIndentedString(veglenkesekvensid)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    startposisjon: ").append(toIndentedString(startposisjon)).append("\n");
    sb.append("    sluttposisjon: ").append(toIndentedString(sluttposisjon)).append("\n");
    sb.append("    kortform: ").append(toIndentedString(kortform)).append("\n");
    sb.append("    veglenkenummer: ").append(toIndentedString(veglenkenummer)).append("\n");
    sb.append("    segmentnummer: ").append(toIndentedString(segmentnummer)).append("\n");
    sb.append("    startnode: ").append(toIndentedString(startnode)).append("\n");
    sb.append("    sluttnode: ").append(toIndentedString(sluttnode)).append("\n");
    sb.append("    referanse: ").append(toIndentedString(referanse)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    detaljnivå: ").append(toIndentedString(detaljnivå)).append("\n");
    sb.append("    typeVeg: ").append(toIndentedString(typeVeg)).append("\n");
    sb.append("    typeVegSosi: ").append(toIndentedString(typeVegSosi)).append("\n");
    sb.append("    målemetode: ").append(toIndentedString(målemetode)).append("\n");
    sb.append("    måledato: ").append(toIndentedString(måledato)).append("\n");
    sb.append("    superstedfesting: ").append(toIndentedString(superstedfesting)).append("\n");
    sb.append("    feltoversikt: ").append(toIndentedString(feltoversikt)).append("\n");
    sb.append("    geometri: ").append(toIndentedString(geometri)).append("\n");
    sb.append("    lengde: ").append(toIndentedString(lengde)).append("\n");
    sb.append("    fylke: ").append(toIndentedString(fylke)).append("\n");
    sb.append("    kommune: ").append(toIndentedString(kommune)).append("\n");
    sb.append("    vegsystemreferanse: ").append(toIndentedString(vegsystemreferanse)).append("\n");
    sb.append("    kontraktsområder: ").append(toIndentedString(kontraktsområder)).append("\n");
    sb.append("    riksvegruter: ").append(toIndentedString(riksvegruter)).append("\n");
    sb.append("    vegforvaltere: ").append(toIndentedString(vegforvaltere)).append("\n");
    sb.append("    adresse: ").append(toIndentedString(adresse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

