/*
 * NVDB API Les Vegobjekter
 * Dette API-et brukes til å lese vegobjekter. Les mer om bruk av API-et på https://nvdb.atlas.vegvesen.no/produkter/nvdbapil/v4/Vegobjekter
 *
 * The version of the OpenAPI document: v4
 * Contact: nvdb@vegvesen.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.vegvesen.vt.nvdb.vegobjekter.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MetrertLokasjon
 */
@JsonPropertyOrder({
  MetrertLokasjon.JSON_PROPERTY_RETNING,
  MetrertLokasjon.JSON_PROPERTY_SIDEPOSISJON,
  MetrertLokasjon.JSON_PROPERTY_KJøREFELT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class MetrertLokasjon {
  /**
   * Gets or Sets retning
   */
  public enum RetningEnum {
    MED(String.valueOf("MED")),
    
    MOT(String.valueOf("MOT"));

    private String value;

    RetningEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RetningEnum fromValue(String value) {
      for (RetningEnum b : RetningEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RETNING = "retning";
  @jakarta.annotation.Nullable
  private RetningEnum retning;

  /**
   * Gets or Sets sideposisjon
   */
  public enum SideposisjonEnum {
    MH(String.valueOf("MH")),
    
    MV(String.valueOf("MV")),
    
    VT(String.valueOf("VT")),
    
    M(String.valueOf("M")),
    
    H(String.valueOf("H")),
    
    HT(String.valueOf("HT")),
    
    VH(String.valueOf("VH")),
    
    HV(String.valueOf("HV")),
    
    K(String.valueOf("K")),
    
    V(String.valueOf("V")),
    
    L(String.valueOf("L")),
    
    R(String.valueOf("R")),
    
    R0(String.valueOf("R0"));

    private String value;

    SideposisjonEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SideposisjonEnum fromValue(String value) {
      for (SideposisjonEnum b : SideposisjonEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SIDEPOSISJON = "sideposisjon";
  @jakarta.annotation.Nullable
  private SideposisjonEnum sideposisjon;

  public static final String JSON_PROPERTY_KJøREFELT = "kjørefelt";
  @jakarta.annotation.Nullable
  private List<String> kjørefelt = new ArrayList<>();

  public MetrertLokasjon() {
  }

  public MetrertLokasjon retning(@jakarta.annotation.Nullable RetningEnum retning) {
    
    this.retning = retning;
    return this;
  }

  /**
   * Get retning
   * @return retning
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RETNING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RetningEnum getRetning() {
    return retning;
  }


  @JsonProperty(JSON_PROPERTY_RETNING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetning(@jakarta.annotation.Nullable RetningEnum retning) {
    this.retning = retning;
  }

  public MetrertLokasjon sideposisjon(@jakarta.annotation.Nullable SideposisjonEnum sideposisjon) {
    
    this.sideposisjon = sideposisjon;
    return this;
  }

  /**
   * Get sideposisjon
   * @return sideposisjon
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIDEPOSISJON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SideposisjonEnum getSideposisjon() {
    return sideposisjon;
  }


  @JsonProperty(JSON_PROPERTY_SIDEPOSISJON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSideposisjon(@jakarta.annotation.Nullable SideposisjonEnum sideposisjon) {
    this.sideposisjon = sideposisjon;
  }

  public MetrertLokasjon kjørefelt(@jakarta.annotation.Nullable List<String> kjørefelt) {
    
    this.kjørefelt = kjørefelt;
    return this;
  }

  public MetrertLokasjon addKjørefeltItem(String kjørefeltItem) {
    if (this.kjørefelt == null) {
      this.kjørefelt = new ArrayList<>();
    }
    this.kjørefelt.add(kjørefeltItem);
    return this;
  }

  /**
   * Get kjørefelt
   * @return kjørefelt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KJøREFELT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getKjørefelt() {
    return kjørefelt;
  }


  @JsonProperty(JSON_PROPERTY_KJøREFELT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKjørefelt(@jakarta.annotation.Nullable List<String> kjørefelt) {
    this.kjørefelt = kjørefelt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetrertLokasjon metrertLokasjon = (MetrertLokasjon) o;
    return Objects.equals(this.retning, metrertLokasjon.retning) &&
        Objects.equals(this.sideposisjon, metrertLokasjon.sideposisjon) &&
        Objects.equals(this.kjørefelt, metrertLokasjon.kjørefelt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(retning, sideposisjon, kjørefelt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetrertLokasjon {\n");
    sb.append("    retning: ").append(toIndentedString(retning)).append("\n");
    sb.append("    sideposisjon: ").append(toIndentedString(sideposisjon)).append("\n");
    sb.append("    kjørefelt: ").append(toIndentedString(kjørefelt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

