/*
 * NVDB API Les Vegobjekter
 * Dette API-et brukes til å lese vegobjekter. Les mer om bruk av API-et på https://nvdb.atlas.vegvesen.no/produkter/nvdbapil/v4/Vegobjekter
 *
 * The version of the OpenAPI document: v4
 * Contact: nvdb@vegvesen.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.vegvesen.vt.nvdb.vegobjekter.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UtledetGeometri
 */
@JsonPropertyOrder({
  UtledetGeometri.JSON_PROPERTY_WKT,
  UtledetGeometri.JSON_PROPERTY_SRID,
  UtledetGeometri.JSON_PROPERTY_EGENGEOMETRI,
  UtledetGeometri.JSON_PROPERTY_FORENKLET,
  UtledetGeometri.JSON_PROPERTY_LENGDE,
  UtledetGeometri.JSON_PROPERTY_AREAL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class UtledetGeometri {
  public static final String JSON_PROPERTY_WKT = "wkt";
  @jakarta.annotation.Nonnull
  private String wkt;

  /**
   * Gets or Sets srid
   */
  public enum SridEnum {
    _5972(String.valueOf("5972")),
    
    _5973(String.valueOf("5973")),
    
    _5975(String.valueOf("5975")),
    
    _4326(String.valueOf("4326"));

    private String value;

    SridEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SridEnum fromValue(String value) {
      for (SridEnum b : SridEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SRID = "srid";
  @jakarta.annotation.Nonnull
  private SridEnum srid;

  public static final String JSON_PROPERTY_EGENGEOMETRI = "egengeometri";
  @jakarta.annotation.Nonnull
  private Boolean egengeometri;

  public static final String JSON_PROPERTY_FORENKLET = "forenklet";
  @jakarta.annotation.Nullable
  private Boolean forenklet;

  public static final String JSON_PROPERTY_LENGDE = "lengde";
  @jakarta.annotation.Nullable
  private Double lengde;

  public static final String JSON_PROPERTY_AREAL = "areal";
  @jakarta.annotation.Nullable
  private Double areal;

  public UtledetGeometri() {
  }

  public UtledetGeometri wkt(@jakarta.annotation.Nonnull String wkt) {
    
    this.wkt = wkt;
    return this;
  }

  /**
   * Get wkt
   * @return wkt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_WKT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getWkt() {
    return wkt;
  }


  @JsonProperty(JSON_PROPERTY_WKT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWkt(@jakarta.annotation.Nonnull String wkt) {
    this.wkt = wkt;
  }

  public UtledetGeometri srid(@jakarta.annotation.Nonnull SridEnum srid) {
    
    this.srid = srid;
    return this;
  }

  /**
   * Get srid
   * @return srid
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SRID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SridEnum getSrid() {
    return srid;
  }


  @JsonProperty(JSON_PROPERTY_SRID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSrid(@jakarta.annotation.Nonnull SridEnum srid) {
    this.srid = srid;
  }

  public UtledetGeometri egengeometri(@jakarta.annotation.Nonnull Boolean egengeometri) {
    
    this.egengeometri = egengeometri;
    return this;
  }

  /**
   * Get egengeometri
   * @return egengeometri
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EGENGEOMETRI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getEgengeometri() {
    return egengeometri;
  }


  @JsonProperty(JSON_PROPERTY_EGENGEOMETRI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEgengeometri(@jakarta.annotation.Nonnull Boolean egengeometri) {
    this.egengeometri = egengeometri;
  }

  public UtledetGeometri forenklet(@jakarta.annotation.Nullable Boolean forenklet) {
    
    this.forenklet = forenklet;
    return this;
  }

  /**
   * Get forenklet
   * @return forenklet
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FORENKLET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getForenklet() {
    return forenklet;
  }


  @JsonProperty(JSON_PROPERTY_FORENKLET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setForenklet(@jakarta.annotation.Nullable Boolean forenklet) {
    this.forenklet = forenklet;
  }

  public UtledetGeometri lengde(@jakarta.annotation.Nullable Double lengde) {
    
    this.lengde = lengde;
    return this;
  }

  /**
   * Get lengde
   * @return lengde
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LENGDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getLengde() {
    return lengde;
  }


  @JsonProperty(JSON_PROPERTY_LENGDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLengde(@jakarta.annotation.Nullable Double lengde) {
    this.lengde = lengde;
  }

  public UtledetGeometri areal(@jakarta.annotation.Nullable Double areal) {
    
    this.areal = areal;
    return this;
  }

  /**
   * Get areal
   * @return areal
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AREAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getAreal() {
    return areal;
  }


  @JsonProperty(JSON_PROPERTY_AREAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAreal(@jakarta.annotation.Nullable Double areal) {
    this.areal = areal;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UtledetGeometri utledetGeometri = (UtledetGeometri) o;
    return Objects.equals(this.wkt, utledetGeometri.wkt) &&
        Objects.equals(this.srid, utledetGeometri.srid) &&
        Objects.equals(this.egengeometri, utledetGeometri.egengeometri) &&
        Objects.equals(this.forenklet, utledetGeometri.forenklet) &&
        Objects.equals(this.lengde, utledetGeometri.lengde) &&
        Objects.equals(this.areal, utledetGeometri.areal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(wkt, srid, egengeometri, forenklet, lengde, areal);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UtledetGeometri {\n");
    sb.append("    wkt: ").append(toIndentedString(wkt)).append("\n");
    sb.append("    srid: ").append(toIndentedString(srid)).append("\n");
    sb.append("    egengeometri: ").append(toIndentedString(egengeometri)).append("\n");
    sb.append("    forenklet: ").append(toIndentedString(forenklet)).append("\n");
    sb.append("    lengde: ").append(toIndentedString(lengde)).append("\n");
    sb.append("    areal: ").append(toIndentedString(areal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

