/*
 * NVDB API Les Vegobjekter
 * Dette API-et brukes til å lese vegobjekter.<br><br>[Dokumentasjon for Vegobjekter API](https://nvdb-docs.atlas.vegvesen.no/nvdbapil/v4/Vegobjekter)
 *
 * The version of the OpenAPI document: v4
 * Contact: nvdb@vegvesen.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.vegvesen.vt.nvdb.vegobjekter.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VegobjektVersjonSegmentert
 */
@JsonPropertyOrder({
  VegobjektVersjonSegmentert.JSON_PROPERTY_ID,
  VegobjektVersjonSegmentert.JSON_PROPERTY_VERSJON,
  VegobjektVersjonSegmentert.JSON_PROPERTY_TYPE,
  VegobjektVersjonSegmentert.JSON_PROPERTY_TIDSPUNKT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class VegobjektVersjonSegmentert {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private Long id;

  public static final String JSON_PROPERTY_VERSJON = "versjon";
  @jakarta.annotation.Nonnull
  private Integer versjon;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private Integer type;

  public static final String JSON_PROPERTY_TIDSPUNKT = "tidspunkt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime tidspunkt;

  public VegobjektVersjonSegmentert() {
  }

  public VegobjektVersjonSegmentert id(@jakarta.annotation.Nonnull Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull Long id) {
    this.id = id;
  }

  public VegobjektVersjonSegmentert versjon(@jakarta.annotation.Nonnull Integer versjon) {
    
    this.versjon = versjon;
    return this;
  }

  /**
   * Get versjon
   * @return versjon
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VERSJON, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getVersjon() {
    return versjon;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSJON, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersjon(@jakarta.annotation.Nonnull Integer versjon) {
    this.versjon = versjon;
  }

  public VegobjektVersjonSegmentert type(@jakarta.annotation.Nonnull Integer type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull Integer type) {
    this.type = type;
  }

  public VegobjektVersjonSegmentert tidspunkt(@jakarta.annotation.Nonnull OffsetDateTime tidspunkt) {
    
    this.tidspunkt = tidspunkt;
    return this;
  }

  /**
   * Tidspunktet da endringen ble gjort tilgjengelig i Les API V4
   * @return tidspunkt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TIDSPUNKT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getTidspunkt() {
    return tidspunkt;
  }


  @JsonProperty(value = JSON_PROPERTY_TIDSPUNKT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTidspunkt(@jakarta.annotation.Nonnull OffsetDateTime tidspunkt) {
    this.tidspunkt = tidspunkt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VegobjektVersjonSegmentert vegobjektVersjonSegmentert = (VegobjektVersjonSegmentert) o;
    return Objects.equals(this.id, vegobjektVersjonSegmentert.id) &&
        Objects.equals(this.versjon, vegobjektVersjonSegmentert.versjon) &&
        Objects.equals(this.type, vegobjektVersjonSegmentert.type) &&
        Objects.equals(this.tidspunkt, vegobjektVersjonSegmentert.tidspunkt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, versjon, type, tidspunkt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VegobjektVersjonSegmentert {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    versjon: ").append(toIndentedString(versjon)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    tidspunkt: ").append(toIndentedString(tidspunkt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

