/*
 * NVDB API Les Vegobjekter
 * Dette API-et brukes til å lese vegobjekter. Les mer om bruk av API-et på https://nvdb.atlas.vegvesen.no/produkter/nvdbapil/v4/Vegobjekter
 *
 * The version of the OpenAPI document: v4
 * Contact: nvdb@vegvesen.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.vegvesen.vt.nvdb.vegobjekter.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import no.vegvesen.vt.nvdb.vegobjekter.model.Vegkategori;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VegobjekterStatistikkGruppert
 */
@JsonPropertyOrder({
  VegobjekterStatistikkGruppert.JSON_PROPERTY_ANTALL,
  VegobjekterStatistikkGruppert.JSON_PROPERTY_LENGDE,
  VegobjekterStatistikkGruppert.JSON_PROPERTY_FYLKE,
  VegobjekterStatistikkGruppert.JSON_PROPERTY_KOMMUNE,
  VegobjekterStatistikkGruppert.JSON_PROPERTY_VEGKATEGORI
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class VegobjekterStatistikkGruppert {
  public static final String JSON_PROPERTY_ANTALL = "antall";
  @jakarta.annotation.Nullable
  private Integer antall;

  public static final String JSON_PROPERTY_LENGDE = "lengde";
  @jakarta.annotation.Nullable
  private Double lengde;

  public static final String JSON_PROPERTY_FYLKE = "fylke";
  @jakarta.annotation.Nullable
  private Integer fylke;

  public static final String JSON_PROPERTY_KOMMUNE = "kommune";
  @jakarta.annotation.Nullable
  private Integer kommune;

  public static final String JSON_PROPERTY_VEGKATEGORI = "vegkategori";
  @jakarta.annotation.Nullable
  private Vegkategori vegkategori;

  public VegobjekterStatistikkGruppert() {
  }

  public VegobjekterStatistikkGruppert antall(@jakarta.annotation.Nullable Integer antall) {
    
    this.antall = antall;
    return this;
  }

  /**
   * Antallet objekter i gruppen. Utelatt dersom inkluder&#x3D;lengde
   * @return antall
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ANTALL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAntall() {
    return antall;
  }


  @JsonProperty(JSON_PROPERTY_ANTALL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAntall(@jakarta.annotation.Nullable Integer antall) {
    this.antall = antall;
  }

  public VegobjekterStatistikkGruppert lengde(@jakarta.annotation.Nullable Double lengde) {
    
    this.lengde = lengde;
    return this;
  }

  /**
   * Den summerte lengden av objektene i gruppen. Utelatt dersom inkluder&#x3D;antall
   * @return lengde
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LENGDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getLengde() {
    return lengde;
  }


  @JsonProperty(JSON_PROPERTY_LENGDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLengde(@jakarta.annotation.Nullable Double lengde) {
    this.lengde = lengde;
  }

  public VegobjekterStatistikkGruppert fylke(@jakarta.annotation.Nullable Integer fylke) {
    
    this.fylke = fylke;
    return this;
  }

  /**
   * Hvilket fylke gruppen tilhører. Utelatt hvis ikke gruppert på fylke
   * @return fylke
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FYLKE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFylke() {
    return fylke;
  }


  @JsonProperty(JSON_PROPERTY_FYLKE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFylke(@jakarta.annotation.Nullable Integer fylke) {
    this.fylke = fylke;
  }

  public VegobjekterStatistikkGruppert kommune(@jakarta.annotation.Nullable Integer kommune) {
    
    this.kommune = kommune;
    return this;
  }

  /**
   * Hvilken kommune gruppen tilhører. Utelatt hvis ikke gruppert på kommune
   * @return kommune
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KOMMUNE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getKommune() {
    return kommune;
  }


  @JsonProperty(JSON_PROPERTY_KOMMUNE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKommune(@jakarta.annotation.Nullable Integer kommune) {
    this.kommune = kommune;
  }

  public VegobjekterStatistikkGruppert vegkategori(@jakarta.annotation.Nullable Vegkategori vegkategori) {
    
    this.vegkategori = vegkategori;
    return this;
  }

  /**
   * Hvilken vegkategori gruppen tilhører. Utelatt hvis ikke gruppert på vegkategori
   * @return vegkategori
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VEGKATEGORI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Vegkategori getVegkategori() {
    return vegkategori;
  }


  @JsonProperty(JSON_PROPERTY_VEGKATEGORI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVegkategori(@jakarta.annotation.Nullable Vegkategori vegkategori) {
    this.vegkategori = vegkategori;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VegobjekterStatistikkGruppert vegobjekterStatistikkGruppert = (VegobjekterStatistikkGruppert) o;
    return Objects.equals(this.antall, vegobjekterStatistikkGruppert.antall) &&
        Objects.equals(this.lengde, vegobjekterStatistikkGruppert.lengde) &&
        Objects.equals(this.fylke, vegobjekterStatistikkGruppert.fylke) &&
        Objects.equals(this.kommune, vegobjekterStatistikkGruppert.kommune) &&
        Objects.equals(this.vegkategori, vegobjekterStatistikkGruppert.vegkategori);
  }

  @Override
  public int hashCode() {
    return Objects.hash(antall, lengde, fylke, kommune, vegkategori);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VegobjekterStatistikkGruppert {\n");
    sb.append("    antall: ").append(toIndentedString(antall)).append("\n");
    sb.append("    lengde: ").append(toIndentedString(lengde)).append("\n");
    sb.append("    fylke: ").append(toIndentedString(fylke)).append("\n");
    sb.append("    kommune: ").append(toIndentedString(kommune)).append("\n");
    sb.append("    vegkategori: ").append(toIndentedString(vegkategori)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

