/*
 * NVDB API Les Vegobjekter
 * Dette API-et brukes til å lese vegobjekter. Les mer om bruk av API-et på https://nvdb.atlas.vegvesen.no/produkter/nvdbapil/v4/Vegobjekter
 *
 * The version of the OpenAPI document: v4
 * Contact: nvdb@vegvesen.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.vegvesen.vt.nvdb.vegobjekter.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import no.vegvesen.vt.nvdb.vegobjekter.model.VegobjektType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VegobjektMetadata
 */
@JsonPropertyOrder({
  VegobjektMetadata.JSON_PROPERTY_TYPE,
  VegobjektMetadata.JSON_PROPERTY_VERSJON,
  VegobjektMetadata.JSON_PROPERTY_STARTDATO,
  VegobjektMetadata.JSON_PROPERTY_SLUTTDATO,
  VegobjektMetadata.JSON_PROPERTY_SIST_MODIFISERT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class VegobjektMetadata {
  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private VegobjektType type;

  public static final String JSON_PROPERTY_VERSJON = "versjon";
  @jakarta.annotation.Nonnull
  private Integer versjon;

  public static final String JSON_PROPERTY_STARTDATO = "startdato";
  @jakarta.annotation.Nonnull
  private LocalDate startdato;

  public static final String JSON_PROPERTY_SLUTTDATO = "sluttdato";
  @jakarta.annotation.Nullable
  private LocalDate sluttdato;

  public static final String JSON_PROPERTY_SIST_MODIFISERT = "sist_modifisert";
  @jakarta.annotation.Nonnull
  private String sistModifisert;

  public VegobjektMetadata() {
  }

  public VegobjektMetadata type(@jakarta.annotation.Nonnull VegobjektType type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public VegobjektType getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull VegobjektType type) {
    this.type = type;
  }

  public VegobjektMetadata versjon(@jakarta.annotation.Nonnull Integer versjon) {
    
    this.versjon = versjon;
    return this;
  }

  /**
   * Get versjon
   * @return versjon
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VERSJON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getVersjon() {
    return versjon;
  }


  @JsonProperty(JSON_PROPERTY_VERSJON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersjon(@jakarta.annotation.Nonnull Integer versjon) {
    this.versjon = versjon;
  }

  public VegobjektMetadata startdato(@jakarta.annotation.Nonnull LocalDate startdato) {
    
    this.startdato = startdato;
    return this;
  }

  /**
   * Get startdato
   * @return startdato
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STARTDATO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getStartdato() {
    return startdato;
  }


  @JsonProperty(JSON_PROPERTY_STARTDATO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStartdato(@jakarta.annotation.Nonnull LocalDate startdato) {
    this.startdato = startdato;
  }

  public VegobjektMetadata sluttdato(@jakarta.annotation.Nullable LocalDate sluttdato) {
    
    this.sluttdato = sluttdato;
    return this;
  }

  /**
   * Get sluttdato
   * @return sluttdato
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SLUTTDATO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getSluttdato() {
    return sluttdato;
  }


  @JsonProperty(JSON_PROPERTY_SLUTTDATO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSluttdato(@jakarta.annotation.Nullable LocalDate sluttdato) {
    this.sluttdato = sluttdato;
  }

  public VegobjektMetadata sistModifisert(@jakarta.annotation.Nonnull String sistModifisert) {
    
    this.sistModifisert = sistModifisert;
    return this;
  }

  /**
   * Dato og tid i UTC-format: yyyy-MM-ddTHH:mm:ssZ
   * @return sistModifisert
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SIST_MODIFISERT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSistModifisert() {
    return sistModifisert;
  }


  @JsonProperty(JSON_PROPERTY_SIST_MODIFISERT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSistModifisert(@jakarta.annotation.Nonnull String sistModifisert) {
    this.sistModifisert = sistModifisert;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VegobjektMetadata vegobjektMetadata = (VegobjektMetadata) o;
    return Objects.equals(this.type, vegobjektMetadata.type) &&
        Objects.equals(this.versjon, vegobjektMetadata.versjon) &&
        Objects.equals(this.startdato, vegobjektMetadata.startdato) &&
        Objects.equals(this.sluttdato, vegobjektMetadata.sluttdato) &&
        Objects.equals(this.sistModifisert, vegobjektMetadata.sistModifisert);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, versjon, startdato, sluttdato, sistModifisert);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VegobjektMetadata {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    versjon: ").append(toIndentedString(versjon)).append("\n");
    sb.append("    startdato: ").append(toIndentedString(startdato)).append("\n");
    sb.append("    sluttdato: ").append(toIndentedString(sluttdato)).append("\n");
    sb.append("    sistModifisert: ").append(toIndentedString(sistModifisert)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

