/* tslint:disable */
/* eslint-disable */
/**
 * NVDB Datakatalog API
 * API-et gir tilgang til å hente vegobjekttyper med tilhørende metadata fra datakatalogen.<br><br>[Dokumentasjon for Datakatalog API](https://nvdb-docs.atlas.vegvesen.no/nvdbapil/v4/Datakatalog)
 *
 * The version of the OpenAPI document: v1
 * Contact: nvdb@vegvesen.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface AssosiasjonstypeVegobjekttype
 */
export interface AssosiasjonstypeVegobjekttype {
  /**
   *
   * @type {number}
   * @memberof AssosiasjonstypeVegobjekttype
   */
  id: number
  /**
   *
   * @type {string}
   * @memberof AssosiasjonstypeVegobjekttype
   */
  navn?: string
  /**
   *
   * @type {Date}
   * @memberof AssosiasjonstypeVegobjekttype
   */
  objektlisteDato?: Date
}

/**
 * Check if a given object implements the AssosiasjonstypeVegobjekttype interface.
 */
export function instanceOfAssosiasjonstypeVegobjekttype(
  value: object,
): value is AssosiasjonstypeVegobjekttype {
  if (!('id' in value) || value['id'] === undefined) return false
  return true
}

export function AssosiasjonstypeVegobjekttypeFromJSON(
  json: any,
): AssosiasjonstypeVegobjekttype {
  return AssosiasjonstypeVegobjekttypeFromJSONTyped(json, false)
}

export function AssosiasjonstypeVegobjekttypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AssosiasjonstypeVegobjekttype {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    navn: json['navn'] == null ? undefined : json['navn'],
    objektlisteDato:
      json['objektliste_dato'] == null
        ? undefined
        : new Date(json['objektliste_dato']),
  }
}

export function AssosiasjonstypeVegobjekttypeToJSON(
  json: any,
): AssosiasjonstypeVegobjekttype {
  return AssosiasjonstypeVegobjekttypeToJSONTyped(json, false)
}

export function AssosiasjonstypeVegobjekttypeToJSONTyped(
  value?: AssosiasjonstypeVegobjekttype | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    navn: value['navn'],
    objektliste_dato:
      value['objektlisteDato'] == null
        ? value['objektlisteDato']
        : value['objektlisteDato'].toISOString().substring(0, 10),
  }
}
