/* tslint:disable */
/* eslint-disable */
/**
 * NVDB Datakatalog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { AssosiasjonstypeVegobjekttype } from './AssosiasjonstypeVegobjekttype'
import {
  AssosiasjonstypeVegobjekttypeFromJSON,
  AssosiasjonstypeVegobjekttypeFromJSONTyped,
  AssosiasjonstypeVegobjekttypeToJSON,
  AssosiasjonstypeVegobjekttypeToJSONTyped,
} from './AssosiasjonstypeVegobjekttype'
import type { AssosiasjonstypeListeInnhold } from './AssosiasjonstypeListeInnhold'
import {
  AssosiasjonstypeListeInnholdFromJSON,
  AssosiasjonstypeListeInnholdFromJSONTyped,
  AssosiasjonstypeListeInnholdToJSON,
  AssosiasjonstypeListeInnholdToJSONTyped,
} from './AssosiasjonstypeListeInnhold'

/**
 *
 * @export
 * @interface Assosiasjonstype
 */
export interface Assosiasjonstype {
  /**
   *
   * @type {number}
   * @memberof Assosiasjonstype
   */
  id: number
  /**
   *
   * @type {string}
   * @memberof Assosiasjonstype
   */
  navn?: string
  /**
   *
   * @type {string}
   * @memberof Assosiasjonstype
   */
  egenskapstype: string
  /**
   *
   * @type {number}
   * @memberof Assosiasjonstype
   */
  maksimaltAntallVerdier?: number
  /**
   *
   * @type {number}
   * @memberof Assosiasjonstype
   */
  minimaltAntallVerdier?: number
  /**
   *
   * @type {AssosiasjonstypeListeInnhold}
   * @memberof Assosiasjonstype
   */
  innhold?: AssosiasjonstypeListeInnhold
  /**
   *
   * @type {AssosiasjonstypeVegobjekttype}
   * @memberof Assosiasjonstype
   */
  type?: AssosiasjonstypeVegobjekttype
}

/**
 * Check if a given object implements the Assosiasjonstype interface.
 */
export function instanceOfAssosiasjonstype(
  value: object,
): value is Assosiasjonstype {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('egenskapstype' in value) || value['egenskapstype'] === undefined)
    return false
  return true
}

export function AssosiasjonstypeFromJSON(json: any): Assosiasjonstype {
  return AssosiasjonstypeFromJSONTyped(json, false)
}

export function AssosiasjonstypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Assosiasjonstype {
  if (json == null) {
    return json
  }
  return {
    id: json['id'],
    navn: json['navn'] == null ? undefined : json['navn'],
    egenskapstype: json['egenskapstype'],
    maksimaltAntallVerdier:
      json['maksimalt_antall_verdier'] == null
        ? undefined
        : json['maksimalt_antall_verdier'],
    minimaltAntallVerdier:
      json['minimalt_antall_verdier'] == null
        ? undefined
        : json['minimalt_antall_verdier'],
    innhold:
      json['innhold'] == null
        ? undefined
        : AssosiasjonstypeListeInnholdFromJSON(json['innhold']),
    type:
      json['type'] == null
        ? undefined
        : AssosiasjonstypeVegobjekttypeFromJSON(json['type']),
  }
}

export function AssosiasjonstypeToJSON(json: any): Assosiasjonstype {
  return AssosiasjonstypeToJSONTyped(json, false)
}

export function AssosiasjonstypeToJSONTyped(
  value?: Assosiasjonstype | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    id: value['id'],
    navn: value['navn'],
    egenskapstype: value['egenskapstype'],
    maksimalt_antall_verdier: value['maksimaltAntallVerdier'],
    minimalt_antall_verdier: value['minimaltAntallVerdier'],
    innhold: AssosiasjonstypeListeInnholdToJSON(value['innhold']),
    type: AssosiasjonstypeVegobjekttypeToJSON(value['type']),
  }
}
