/* tslint:disable */
/* eslint-disable */
/**
 * NVDB Datakatalog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { AssosiasjonstypeListeInnhold } from './AssosiasjonstypeListeInnhold'
import {
  AssosiasjonstypeListeInnholdFromJSON,
  AssosiasjonstypeListeInnholdFromJSONTyped,
  AssosiasjonstypeListeInnholdToJSON,
} from './AssosiasjonstypeListeInnhold'
import type { AssosiasjonstypeVegobjekttype } from './AssosiasjonstypeVegobjekttype'
import {
  AssosiasjonstypeVegobjekttypeFromJSON,
  AssosiasjonstypeVegobjekttypeFromJSONTyped,
  AssosiasjonstypeVegobjekttypeToJSON,
} from './AssosiasjonstypeVegobjekttype'

/**
 *
 * @export
 * @interface Assosiasjonstype
 */
export interface Assosiasjonstype {
  /**
   *
   * @type {number}
   * @memberof Assosiasjonstype
   */
  id: number
  /**
   *
   * @type {string}
   * @memberof Assosiasjonstype
   */
  navn?: string
  /**
   *
   * @type {string}
   * @memberof Assosiasjonstype
   */
  egenskapstype: string
  /**
   *
   * @type {number}
   * @memberof Assosiasjonstype
   */
  maksimaltAntallVerdier?: number
  /**
   *
   * @type {number}
   * @memberof Assosiasjonstype
   */
  minimaltAntallVerdier?: number
  /**
   *
   * @type {AssosiasjonstypeListeInnhold}
   * @memberof Assosiasjonstype
   */
  innhold?: AssosiasjonstypeListeInnhold
  /**
   *
   * @type {AssosiasjonstypeVegobjekttype}
   * @memberof Assosiasjonstype
   */
  type?: AssosiasjonstypeVegobjekttype
}

/**
 * Check if a given object implements the Assosiasjonstype interface.
 */
export function instanceOfAssosiasjonstype(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && 'id' in value
  isInstance = isInstance && 'egenskapstype' in value

  return isInstance
}

export function AssosiasjonstypeFromJSON(json: any): Assosiasjonstype {
  return AssosiasjonstypeFromJSONTyped(json, false)
}

export function AssosiasjonstypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Assosiasjonstype {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
    navn: !exists(json, 'navn') ? undefined : json['navn'],
    egenskapstype: json['egenskapstype'],
    maksimaltAntallVerdier: !exists(json, 'maksimalt_antall_verdier')
      ? undefined
      : json['maksimalt_antall_verdier'],
    minimaltAntallVerdier: !exists(json, 'minimalt_antall_verdier')
      ? undefined
      : json['minimalt_antall_verdier'],
    innhold: !exists(json, 'innhold')
      ? undefined
      : AssosiasjonstypeListeInnholdFromJSON(json['innhold']),
    type: !exists(json, 'type')
      ? undefined
      : AssosiasjonstypeVegobjekttypeFromJSON(json['type']),
  }
}

export function AssosiasjonstypeToJSON(value?: Assosiasjonstype | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    navn: value.navn,
    egenskapstype: value.egenskapstype,
    maksimalt_antall_verdier: value.maksimaltAntallVerdier,
    minimalt_antall_verdier: value.minimaltAntallVerdier,
    innhold: AssosiasjonstypeListeInnholdToJSON(value.innhold),
    type: AssosiasjonstypeVegobjekttypeToJSON(value.type),
  }
}
