/* tslint:disable */
/* eslint-disable */
/**
 * NVDB Datakatalog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Egenskapstype } from './Egenskapstype';
import {
    EgenskapstypeFromJSON,
    EgenskapstypeFromJSONTyped,
    EgenskapstypeToJSON,
} from './Egenskapstype';
import type { Enhet } from './Enhet';
import {
    EnhetFromJSON,
    EnhetFromJSONTyped,
    EnhetToJSON,
} from './Enhet';

/**
 * 
 * @export
 * @interface EgenskapstypeHeltall
 */
export interface EgenskapstypeHeltall extends Egenskapstype {
    /**
     * 
     * @type {Date}
     * @memberof EgenskapstypeHeltall
     */
    objektlisteDato?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EgenskapstypeHeltall
     */
    sluttDato?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof EgenskapstypeHeltall
     */
    lengdeavhengigVerdi: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EgenskapstypeHeltall
     */
    ajourholdSnu: boolean;
    /**
     * 
     * @type {number}
     * @memberof EgenskapstypeHeltall
     */
    standardverdi?: number;
    /**
     * 
     * @type {number}
     * @memberof EgenskapstypeHeltall
     */
    minAnbefalt?: number;
    /**
     * 
     * @type {number}
     * @memberof EgenskapstypeHeltall
     */
    maksAnbefalt?: number;
    /**
     * 
     * @type {number}
     * @memberof EgenskapstypeHeltall
     */
    min?: number;
    /**
     * 
     * @type {number}
     * @memberof EgenskapstypeHeltall
     */
    maks?: number;
    /**
     * 
     * @type {number}
     * @memberof EgenskapstypeHeltall
     */
    feltlengde?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EgenskapstypeHeltall
     */
    fortegnsendringSnu: boolean;
    /**
     * 
     * @type {Enhet}
     * @memberof EgenskapstypeHeltall
     */
    enhet?: Enhet;
}



/**
 * Check if a given object implements the EgenskapstypeHeltall interface.
 */
export function instanceOfEgenskapstypeHeltall(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "lengdeavhengigVerdi" in value;
    isInstance = isInstance && "ajourholdSnu" in value;
    isInstance = isInstance && "fortegnsendringSnu" in value;

    return isInstance;
}

export function EgenskapstypeHeltallFromJSON(json: any): EgenskapstypeHeltall {
    return EgenskapstypeHeltallFromJSONTyped(json, false);
}

export function EgenskapstypeHeltallFromJSONTyped(json: any, ignoreDiscriminator: boolean): EgenskapstypeHeltall {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...EgenskapstypeFromJSONTyped(json, ignoreDiscriminator),
        'objektlisteDato': !exists(json, 'objektliste_dato') ? undefined : (new Date(json['objektliste_dato'])),
        'sluttDato': !exists(json, 'slutt_dato') ? undefined : (new Date(json['slutt_dato'])),
        'lengdeavhengigVerdi': json['lengdeavhengig_verdi'],
        'ajourholdSnu': json['ajourhold_snu'],
        'standardverdi': !exists(json, 'standardverdi') ? undefined : json['standardverdi'],
        'minAnbefalt': !exists(json, 'min_anbefalt') ? undefined : json['min_anbefalt'],
        'maksAnbefalt': !exists(json, 'maks_anbefalt') ? undefined : json['maks_anbefalt'],
        'min': !exists(json, 'min') ? undefined : json['min'],
        'maks': !exists(json, 'maks') ? undefined : json['maks'],
        'feltlengde': !exists(json, 'feltlengde') ? undefined : json['feltlengde'],
        'fortegnsendringSnu': json['fortegnsendring_snu'],
        'enhet': !exists(json, 'enhet') ? undefined : EnhetFromJSON(json['enhet']),
    };
}

export function EgenskapstypeHeltallToJSON(value?: EgenskapstypeHeltall | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...EgenskapstypeToJSON(value),
        'objektliste_dato': value.objektlisteDato === undefined ? undefined : (value.objektlisteDato.toISOString().substring(0,10)),
        'slutt_dato': value.sluttDato === undefined ? undefined : (value.sluttDato.toISOString().substring(0,10)),
        'lengdeavhengig_verdi': value.lengdeavhengigVerdi,
        'ajourhold_snu': value.ajourholdSnu,
        'standardverdi': value.standardverdi,
        'min_anbefalt': value.minAnbefalt,
        'maks_anbefalt': value.maksAnbefalt,
        'min': value.min,
        'maks': value.maks,
        'feltlengde': value.feltlengde,
        'fortegnsendring_snu': value.fortegnsendringSnu,
        'enhet': EnhetToJSON(value.enhet),
    };
}

