/* tslint:disable */
/* eslint-disable */
/**
 * NVDB Datakatalog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Viktighet } from './Viktighet'
import {
  ViktighetFromJSON,
  ViktighetFromJSONTyped,
  ViktighetToJSON,
  ViktighetToJSONTyped,
} from './Viktighet'
import type { EnumverdiTekst } from './EnumverdiTekst'
import {
  EnumverdiTekstFromJSON,
  EnumverdiTekstFromJSONTyped,
  EnumverdiTekstToJSON,
  EnumverdiTekstToJSONTyped,
} from './EnumverdiTekst'
import type { Egenskapstype } from './Egenskapstype'
import {
  EgenskapstypeFromJSON,
  EgenskapstypeFromJSONTyped,
  EgenskapstypeToJSON,
  EgenskapstypeToJSONTyped,
} from './Egenskapstype'
import type { EgenskapstypeEnum } from './EgenskapstypeEnum'
import {
  EgenskapstypeEnumFromJSON,
  EgenskapstypeEnumFromJSONTyped,
  EgenskapstypeEnumToJSON,
  EgenskapstypeEnumToJSONTyped,
} from './EgenskapstypeEnum'

/**
 *
 * @export
 * @interface EgenskapstypeTekstenum
 */
export interface EgenskapstypeTekstenum extends Egenskapstype {
  /**
   *
   * @type {Date}
   * @memberof EgenskapstypeTekstenum
   */
  objektlisteDato?: Date
  /**
   *
   * @type {Date}
   * @memberof EgenskapstypeTekstenum
   */
  sluttDato?: Date
  /**
   *
   * @type {boolean}
   * @memberof EgenskapstypeTekstenum
   */
  lengdeavhengigVerdi: boolean
  /**
   *
   * @type {boolean}
   * @memberof EgenskapstypeTekstenum
   */
  ajourholdSnu: boolean
  /**
   *
   * @type {string}
   * @memberof EgenskapstypeTekstenum
   */
  standardverdi?: string
  /**
   *
   * @type {number}
   * @memberof EgenskapstypeTekstenum
   */
  feltlengde?: number
  /**
   *
   * @type {string}
   * @memberof EgenskapstypeTekstenum
   */
  feltmnster?: string
  /**
   *
   * @type {Array<EnumverdiTekst>}
   * @memberof EgenskapstypeTekstenum
   */
  tillatteVerdier: Array<EnumverdiTekst>
}

/**
 * Check if a given object implements the EgenskapstypeTekstenum interface.
 */
export function instanceOfEgenskapstypeTekstenum(
  value: object,
): value is EgenskapstypeTekstenum {
  if (
    !('lengdeavhengigVerdi' in value) ||
    value['lengdeavhengigVerdi'] === undefined
  )
    return false
  if (!('ajourholdSnu' in value) || value['ajourholdSnu'] === undefined)
    return false
  if (!('tillatteVerdier' in value) || value['tillatteVerdier'] === undefined)
    return false
  return true
}

export function EgenskapstypeTekstenumFromJSON(
  json: any,
): EgenskapstypeTekstenum {
  return EgenskapstypeTekstenumFromJSONTyped(json, false)
}

export function EgenskapstypeTekstenumFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EgenskapstypeTekstenum {
  if (json == null) {
    return json
  }
  return {
    ...EgenskapstypeFromJSONTyped(json, true),
    objektlisteDato:
      json['objektliste_dato'] == null
        ? undefined
        : new Date(json['objektliste_dato']),
    sluttDato:
      json['slutt_dato'] == null ? undefined : new Date(json['slutt_dato']),
    lengdeavhengigVerdi: json['lengdeavhengig_verdi'],
    ajourholdSnu: json['ajourhold_snu'],
    standardverdi:
      json['standardverdi'] == null ? undefined : json['standardverdi'],
    feltlengde: json['feltlengde'] == null ? undefined : json['feltlengde'],
    feltmnster: json['feltmønster'] == null ? undefined : json['feltmønster'],
    tillatteVerdier: (json['tillatte_verdier'] as Array<any>).map(
      EnumverdiTekstFromJSON,
    ),
  }
}

export function EgenskapstypeTekstenumToJSON(
  json: any,
): EgenskapstypeTekstenum {
  return EgenskapstypeTekstenumToJSONTyped(json, false)
}

export function EgenskapstypeTekstenumToJSONTyped(
  value?: EgenskapstypeTekstenum | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    ...EgenskapstypeToJSONTyped(value, true),
    objektliste_dato:
      value['objektlisteDato'] == null
        ? undefined
        : value['objektlisteDato'].toISOString().substring(0, 10),
    slutt_dato:
      value['sluttDato'] == null
        ? undefined
        : value['sluttDato'].toISOString().substring(0, 10),
    lengdeavhengig_verdi: value['lengdeavhengigVerdi'],
    ajourhold_snu: value['ajourholdSnu'],
    standardverdi: value['standardverdi'],
    feltlengde: value['feltlengde'],
    feltmønster: value['feltmnster'],
    tillatte_verdier: (value['tillatteVerdier'] as Array<any>).map(
      EnumverdiTekstToJSON,
    ),
  }
}
