/* tslint:disable */
/* eslint-disable */
/**
 * NVDB Datakatalog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Viktighet } from './Viktighet'
import {
  ViktighetFromJSON,
  ViktighetFromJSONTyped,
  ViktighetToJSON,
  ViktighetToJSONTyped,
} from './Viktighet'
import type { Enhet } from './Enhet'
import {
  EnhetFromJSON,
  EnhetFromJSONTyped,
  EnhetToJSON,
  EnhetToJSONTyped,
} from './Enhet'
import type { Egenskapstype } from './Egenskapstype'
import {
  EgenskapstypeFromJSON,
  EgenskapstypeFromJSONTyped,
  EgenskapstypeToJSON,
  EgenskapstypeToJSONTyped,
} from './Egenskapstype'
import type { EgenskapstypeEnum } from './EgenskapstypeEnum'
import {
  EgenskapstypeEnumFromJSON,
  EgenskapstypeEnumFromJSONTyped,
  EgenskapstypeEnumToJSON,
  EgenskapstypeEnumToJSONTyped,
} from './EgenskapstypeEnum'

/**
 *
 * @export
 * @interface EgenskapstypeHeltall
 */
export interface EgenskapstypeHeltall extends Egenskapstype {
  /**
   *
   * @type {Date}
   * @memberof EgenskapstypeHeltall
   */
  objektlisteDato?: Date
  /**
   *
   * @type {Date}
   * @memberof EgenskapstypeHeltall
   */
  sluttDato?: Date
  /**
   *
   * @type {boolean}
   * @memberof EgenskapstypeHeltall
   */
  lengdeavhengigVerdi: boolean
  /**
   *
   * @type {boolean}
   * @memberof EgenskapstypeHeltall
   */
  ajourholdSnu: boolean
  /**
   *
   * @type {number}
   * @memberof EgenskapstypeHeltall
   */
  standardverdi?: number
  /**
   *
   * @type {number}
   * @memberof EgenskapstypeHeltall
   */
  minAnbefalt?: number
  /**
   *
   * @type {number}
   * @memberof EgenskapstypeHeltall
   */
  maksAnbefalt?: number
  /**
   *
   * @type {number}
   * @memberof EgenskapstypeHeltall
   */
  min?: number
  /**
   *
   * @type {number}
   * @memberof EgenskapstypeHeltall
   */
  maks?: number
  /**
   *
   * @type {number}
   * @memberof EgenskapstypeHeltall
   */
  feltlengde?: number
  /**
   *
   * @type {boolean}
   * @memberof EgenskapstypeHeltall
   */
  fortegnsendringSnu: boolean
  /**
   *
   * @type {Enhet}
   * @memberof EgenskapstypeHeltall
   */
  enhet?: Enhet
}

/**
 * Check if a given object implements the EgenskapstypeHeltall interface.
 */
export function instanceOfEgenskapstypeHeltall(
  value: object,
): value is EgenskapstypeHeltall {
  if (
    !('lengdeavhengigVerdi' in value) ||
    value['lengdeavhengigVerdi'] === undefined
  )
    return false
  if (!('ajourholdSnu' in value) || value['ajourholdSnu'] === undefined)
    return false
  if (
    !('fortegnsendringSnu' in value) ||
    value['fortegnsendringSnu'] === undefined
  )
    return false
  return true
}

export function EgenskapstypeHeltallFromJSON(json: any): EgenskapstypeHeltall {
  return EgenskapstypeHeltallFromJSONTyped(json, false)
}

export function EgenskapstypeHeltallFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EgenskapstypeHeltall {
  if (json == null) {
    return json
  }
  return {
    ...EgenskapstypeFromJSONTyped(json, true),
    objektlisteDato:
      json['objektliste_dato'] == null
        ? undefined
        : new Date(json['objektliste_dato']),
    sluttDato:
      json['slutt_dato'] == null ? undefined : new Date(json['slutt_dato']),
    lengdeavhengigVerdi: json['lengdeavhengig_verdi'],
    ajourholdSnu: json['ajourhold_snu'],
    standardverdi:
      json['standardverdi'] == null ? undefined : json['standardverdi'],
    minAnbefalt:
      json['min_anbefalt'] == null ? undefined : json['min_anbefalt'],
    maksAnbefalt:
      json['maks_anbefalt'] == null ? undefined : json['maks_anbefalt'],
    min: json['min'] == null ? undefined : json['min'],
    maks: json['maks'] == null ? undefined : json['maks'],
    feltlengde: json['feltlengde'] == null ? undefined : json['feltlengde'],
    fortegnsendringSnu: json['fortegnsendring_snu'],
    enhet: json['enhet'] == null ? undefined : EnhetFromJSON(json['enhet']),
  }
}

export function EgenskapstypeHeltallToJSON(json: any): EgenskapstypeHeltall {
  return EgenskapstypeHeltallToJSONTyped(json, false)
}

export function EgenskapstypeHeltallToJSONTyped(
  value?: EgenskapstypeHeltall | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    ...EgenskapstypeToJSONTyped(value, true),
    objektliste_dato:
      value['objektlisteDato'] == null
        ? undefined
        : value['objektlisteDato'].toISOString().substring(0, 10),
    slutt_dato:
      value['sluttDato'] == null
        ? undefined
        : value['sluttDato'].toISOString().substring(0, 10),
    lengdeavhengig_verdi: value['lengdeavhengigVerdi'],
    ajourhold_snu: value['ajourholdSnu'],
    standardverdi: value['standardverdi'],
    min_anbefalt: value['minAnbefalt'],
    maks_anbefalt: value['maksAnbefalt'],
    min: value['min'],
    maks: value['maks'],
    feltlengde: value['feltlengde'],
    fortegnsendring_snu: value['fortegnsendringSnu'],
    enhet: EnhetToJSON(value['enhet']),
  }
}
