/* tslint:disable */
/* eslint-disable */
/**
 * NVDB Datakatalog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Enhet
 */
export interface Enhet {
    /**
     * 
     * @type {number}
     * @memberof Enhet
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Enhet
     */
    navn?: string;
    /**
     * 
     * @type {string}
     * @memberof Enhet
     */
    kortnavn?: string;
}

/**
 * Check if a given object implements the Enhet interface.
 */
export function instanceOfEnhet(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function EnhetFromJSON(json: any): Enhet {
    return EnhetFromJSONTyped(json, false);
}

export function EnhetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Enhet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'navn': !exists(json, 'navn') ? undefined : json['navn'],
        'kortnavn': !exists(json, 'kortnavn') ? undefined : json['kortnavn'],
    };
}

export function EnhetToJSON(value?: Enhet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'navn': value.navn,
        'kortnavn': value.kortnavn,
    };
}

