/* tslint:disable */
/* eslint-disable */
/**
 * NVDB Datakatalog API
 * API-et gir tilgang til å hente vegobjekttyper med tilhørende metadata fra datakatalogen.<br><br>[Dokumentasjon for Datakatalog API](https://nvdb-docs.atlas.vegvesen.no/nvdbapil/v4/Datakatalog)
 *
 * The version of the OpenAPI document: v1
 * Contact: nvdb@vegvesen.no
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Example
 */
export interface Example {
  /**
   *
   * @type {string}
   * @memberof Example
   */
  title: string
  /**
   *
   * @type {string}
   * @memberof Example
   */
  url: string
}

/**
 * Check if a given object implements the Example interface.
 */
export function instanceOfExample(value: object): value is Example {
  if (!('title' in value) || value['title'] === undefined) return false
  if (!('url' in value) || value['url'] === undefined) return false
  return true
}

export function ExampleFromJSON(json: any): Example {
  return ExampleFromJSONTyped(json, false)
}

export function ExampleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Example {
  if (json == null) {
    return json
  }
  return {
    title: json['title'],
    url: json['url'],
  }
}

export function ExampleToJSON(json: any): Example {
  return ExampleToJSONTyped(json, false)
}

export function ExampleToJSONTyped(
  value?: Example | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    title: value['title'],
    url: value['url'],
  }
}
