/* tslint:disable */
/* eslint-disable */
/**
 * NVDB Datakatalog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Viktighet } from './Viktighet'
import {
  ViktighetFromJSON,
  ViktighetFromJSONTyped,
  ViktighetToJSON,
  ViktighetToJSONTyped,
} from './Viktighet'
import type { EgenskapstypeEnum } from './EgenskapstypeEnum'
import {
  EgenskapstypeEnumFromJSON,
  EgenskapstypeEnumFromJSONTyped,
  EgenskapstypeEnumToJSON,
  EgenskapstypeEnumToJSONTyped,
} from './EgenskapstypeEnum'

import {
  StedfestingListe,
  StedfestingListeFromJSONTyped,
  StedfestingListeToJSON,
  StedfestingListeToJSONTyped,
} from './StedfestingListe'
import {
  StedfestingEnkel,
  StedfestingEnkelFromJSONTyped,
  StedfestingEnkelToJSON,
  StedfestingEnkelToJSONTyped,
} from './StedfestingEnkel'
/**
 *
 * @export
 * @interface Stedfesting
 */
export interface Stedfesting {
  /**
   *
   * @type {number}
   * @memberof Stedfesting
   */
  id: number
  /**
   *
   * @type {string}
   * @memberof Stedfesting
   */
  navn?: string
  /**
   *
   * @type {EgenskapstypeEnum}
   * @memberof Stedfesting
   */
  egenskapstype: EgenskapstypeEnum
  /**
   *
   * @type {number}
   * @memberof Stedfesting
   */
  komplementrEgenskapstype?: number
  /**
   *
   * @type {string}
   * @memberof Stedfesting
   */
  kortnavn?: string
  /**
   *
   * @type {string}
   * @memberof Stedfesting
   */
  beskrivelse?: string
  /**
   *
   * @type {string}
   * @memberof Stedfesting
   */
  veiledning?: string
  /**
   *
   * @type {string}
   * @memberof Stedfesting
   */
  sosinavn?: string
  /**
   *
   * @type {string}
   * @memberof Stedfesting
   */
  sosinvdbnavn?: string
  /**
   *
   * @type {number}
   * @memberof Stedfesting
   */
  sorteringsnummer: number
  /**
   *
   * @type {boolean}
   * @memberof Stedfesting
   */
  avledet: boolean
  /**
   *
   * @type {boolean}
   * @memberof Stedfesting
   */
  obligatoriskVerdi: boolean
  /**
   *
   * @type {boolean}
   * @memberof Stedfesting
   */
  skrivebeskyttet: boolean
  /**
   *
   * @type {number}
   * @memberof Stedfesting
   */
  sensitivitet: number
  /**
   *
   * @type {number}
   * @memberof Stedfesting
   */
  gruppesorteringsnummer?: number
  /**
   *
   * @type {string}
   * @memberof Stedfesting
   */
  grunnrissreferanse?: string
  /**
   *
   * @type {string}
   * @memberof Stedfesting
   */
  hydereferanse?: string
  /**
   *
   * @type {number}
   * @memberof Stedfesting
   */
  hydereferanseTall: number
  /**
   *
   * @type {number}
   * @memberof Stedfesting
   */
  nyaktighetskravGrunnriss: number
  /**
   *
   * @type {number}
   * @memberof Stedfesting
   */
  nyaktighetskravHyde: number
  /**
   *
   * @type {string}
   * @memberof Stedfesting
   */
  sosiReferanse?: string
  /**
   *
   * @type {boolean}
   * @memberof Stedfesting
   */
  referansegeometriTilstrekkelig: boolean
  /**
   *
   * @type {Viktighet}
   * @memberof Stedfesting
   */
  viktighet: Viktighet
  /**
   *
   * @type {number}
   * @memberof Stedfesting
   */
  kategori: number
}

/**
 * Check if a given object implements the Stedfesting interface.
 */
export function instanceOfStedfesting(value: object): value is Stedfesting {
  if (!('id' in value) || value['id'] === undefined) return false
  if (!('egenskapstype' in value) || value['egenskapstype'] === undefined)
    return false
  if (!('sorteringsnummer' in value) || value['sorteringsnummer'] === undefined)
    return false
  if (!('avledet' in value) || value['avledet'] === undefined) return false
  if (
    !('obligatoriskVerdi' in value) ||
    value['obligatoriskVerdi'] === undefined
  )
    return false
  if (!('skrivebeskyttet' in value) || value['skrivebeskyttet'] === undefined)
    return false
  if (!('sensitivitet' in value) || value['sensitivitet'] === undefined)
    return false
  if (
    !('hydereferanseTall' in value) ||
    value['hydereferanseTall'] === undefined
  )
    return false
  if (
    !('nyaktighetskravGrunnriss' in value) ||
    value['nyaktighetskravGrunnriss'] === undefined
  )
    return false
  if (
    !('nyaktighetskravHyde' in value) ||
    value['nyaktighetskravHyde'] === undefined
  )
    return false
  if (
    !('referansegeometriTilstrekkelig' in value) ||
    value['referansegeometriTilstrekkelig'] === undefined
  )
    return false
  if (!('viktighet' in value) || value['viktighet'] === undefined) return false
  if (!('kategori' in value) || value['kategori'] === undefined) return false
  return true
}

export function StedfestingFromJSON(json: any): Stedfesting {
  return StedfestingFromJSONTyped(json, false)
}

export function StedfestingFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Stedfesting {
  if (json == null) {
    return json
  }
  if (!ignoreDiscriminator) {
    if (json['egenskapstype'] === 'Liste') {
      return StedfestingListeFromJSONTyped(json, ignoreDiscriminator)
    }
    if (json['egenskapstype'] === 'Stedfesting') {
      return StedfestingEnkelFromJSONTyped(json, ignoreDiscriminator)
    }
  }
  return {
    id: json['id'],
    navn: json['navn'] == null ? undefined : json['navn'],
    egenskapstype: EgenskapstypeEnumFromJSON(json['egenskapstype']),
    komplementrEgenskapstype:
      json['komplementær_egenskapstype'] == null
        ? undefined
        : json['komplementær_egenskapstype'],
    kortnavn: json['kortnavn'] == null ? undefined : json['kortnavn'],
    beskrivelse: json['beskrivelse'] == null ? undefined : json['beskrivelse'],
    veiledning: json['veiledning'] == null ? undefined : json['veiledning'],
    sosinavn: json['sosinavn'] == null ? undefined : json['sosinavn'],
    sosinvdbnavn:
      json['sosinvdbnavn'] == null ? undefined : json['sosinvdbnavn'],
    sorteringsnummer: json['sorteringsnummer'],
    avledet: json['avledet'],
    obligatoriskVerdi: json['obligatorisk_verdi'],
    skrivebeskyttet: json['skrivebeskyttet'],
    sensitivitet: json['sensitivitet'],
    gruppesorteringsnummer:
      json['gruppesorteringsnummer'] == null
        ? undefined
        : json['gruppesorteringsnummer'],
    grunnrissreferanse:
      json['grunnrissreferanse'] == null
        ? undefined
        : json['grunnrissreferanse'],
    hydereferanse:
      json['høydereferanse'] == null ? undefined : json['høydereferanse'],
    hydereferanseTall: json['høydereferanse_tall'],
    nyaktighetskravGrunnriss: json['nøyaktighetskrav_grunnriss'],
    nyaktighetskravHyde: json['nøyaktighetskrav_høyde'],
    sosiReferanse:
      json['sosi_referanse'] == null ? undefined : json['sosi_referanse'],
    referansegeometriTilstrekkelig: json['referansegeometri_tilstrekkelig'],
    viktighet: ViktighetFromJSON(json['viktighet']),
    kategori: json['kategori'],
  }
}

export function StedfestingToJSON(json: any): Stedfesting {
  return StedfestingToJSONTyped(json, false)
}

export function StedfestingToJSONTyped(
  value?: Stedfesting | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  if (!ignoreDiscriminator) {
    switch (value['egenskapstype']) {
      case 'Liste':
        return StedfestingListeToJSONTyped(
          value as StedfestingListe,
          ignoreDiscriminator,
        )
      case 'Stedfesting':
        return StedfestingEnkelToJSONTyped(
          value as StedfestingEnkel,
          ignoreDiscriminator,
        )
      default:
        return value
    }
  }

  return {
    id: value['id'],
    navn: value['navn'],
    egenskapstype: EgenskapstypeEnumToJSON(value['egenskapstype']),
    komplementær_egenskapstype: value['komplementrEgenskapstype'],
    kortnavn: value['kortnavn'],
    beskrivelse: value['beskrivelse'],
    veiledning: value['veiledning'],
    sosinavn: value['sosinavn'],
    sosinvdbnavn: value['sosinvdbnavn'],
    sorteringsnummer: value['sorteringsnummer'],
    avledet: value['avledet'],
    obligatorisk_verdi: value['obligatoriskVerdi'],
    skrivebeskyttet: value['skrivebeskyttet'],
    sensitivitet: value['sensitivitet'],
    gruppesorteringsnummer: value['gruppesorteringsnummer'],
    grunnrissreferanse: value['grunnrissreferanse'],
    høydereferanse: value['hydereferanse'],
    høydereferanse_tall: value['hydereferanseTall'],
    nøyaktighetskrav_grunnriss: value['nyaktighetskravGrunnriss'],
    nøyaktighetskrav_høyde: value['nyaktighetskravHyde'],
    sosi_referanse: value['sosiReferanse'],
    referansegeometri_tilstrekkelig: value['referansegeometriTilstrekkelig'],
    viktighet: ViktighetToJSON(value['viktighet']),
    kategori: value['kategori'],
  }
}
