/* tslint:disable */
/* eslint-disable */
/**
 * NVDB Datakatalog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { EgenskapstypeEnum } from './EgenskapstypeEnum'
import {
  EgenskapstypeEnumFromJSON,
  EgenskapstypeEnumFromJSONTyped,
  EgenskapstypeEnumToJSON,
} from './EgenskapstypeEnum'
import type { EgenskapstypeStedfesting } from './EgenskapstypeStedfesting'
import {
  EgenskapstypeStedfestingFromJSON,
  EgenskapstypeStedfestingFromJSONTyped,
  EgenskapstypeStedfestingToJSON,
} from './EgenskapstypeStedfesting'
import type { Stedfesting } from './Stedfesting'
import {
  StedfestingFromJSON,
  StedfestingFromJSONTyped,
  StedfestingToJSON,
} from './Stedfesting'
import type { Viktighet } from './Viktighet'
import {
  ViktighetFromJSON,
  ViktighetFromJSONTyped,
  ViktighetToJSON,
} from './Viktighet'

/**
 *
 * @export
 * @interface StedfestingListe
 */
export interface StedfestingListe extends Stedfesting {
  /**
   *
   * @type {number}
   * @memberof StedfestingListe
   */
  maksimaltAntallVerdier?: number
  /**
   *
   * @type {number}
   * @memberof StedfestingListe
   */
  minimaltAntallVerdier?: number
  /**
   *
   * @type {EgenskapstypeStedfesting}
   * @memberof StedfestingListe
   */
  innhold: EgenskapstypeStedfesting
}

/**
 * Check if a given object implements the StedfestingListe interface.
 */
export function instanceOfStedfestingListe(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && 'innhold' in value

  return isInstance
}

export function StedfestingListeFromJSON(json: any): StedfestingListe {
  return StedfestingListeFromJSONTyped(json, false)
}

export function StedfestingListeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StedfestingListe {
  if (json === undefined || json === null) {
    return json
  }
  return {
    ...StedfestingFromJSONTyped(json, ignoreDiscriminator),
    maksimaltAntallVerdier: !exists(json, 'maksimalt_antall_verdier')
      ? undefined
      : json['maksimalt_antall_verdier'],
    minimaltAntallVerdier: !exists(json, 'minimalt_antall_verdier')
      ? undefined
      : json['minimalt_antall_verdier'],
    innhold: EgenskapstypeStedfestingFromJSON(json['innhold']),
  }
}

export function StedfestingListeToJSON(value?: StedfestingListe | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    ...StedfestingToJSON(value),
    maksimalt_antall_verdier: value.maksimaltAntallVerdier,
    minimalt_antall_verdier: value.minimaltAntallVerdier,
    innhold: EgenskapstypeStedfestingToJSON(value.innhold),
  }
}
