/* tslint:disable */
/* eslint-disable */
/**
 * NVDB Datakatalog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { Stedfesting } from './Stedfesting'
import {
  StedfestingFromJSON,
  StedfestingFromJSONTyped,
  StedfestingToJSON,
  StedfestingToJSONTyped,
} from './Stedfesting'
import type { Viktighet } from './Viktighet'
import {
  ViktighetFromJSON,
  ViktighetFromJSONTyped,
  ViktighetToJSON,
  ViktighetToJSONTyped,
} from './Viktighet'
import type { EgenskapstypeStedfesting } from './EgenskapstypeStedfesting'
import {
  EgenskapstypeStedfestingFromJSON,
  EgenskapstypeStedfestingFromJSONTyped,
  EgenskapstypeStedfestingToJSON,
  EgenskapstypeStedfestingToJSONTyped,
} from './EgenskapstypeStedfesting'
import type { EgenskapstypeEnum } from './EgenskapstypeEnum'
import {
  EgenskapstypeEnumFromJSON,
  EgenskapstypeEnumFromJSONTyped,
  EgenskapstypeEnumToJSON,
  EgenskapstypeEnumToJSONTyped,
} from './EgenskapstypeEnum'

/**
 *
 * @export
 * @interface StedfestingListe
 */
export interface StedfestingListe extends Stedfesting {
  /**
   *
   * @type {number}
   * @memberof StedfestingListe
   */
  maksimaltAntallVerdier?: number
  /**
   *
   * @type {number}
   * @memberof StedfestingListe
   */
  minimaltAntallVerdier?: number
  /**
   *
   * @type {EgenskapstypeStedfesting}
   * @memberof StedfestingListe
   */
  innhold: EgenskapstypeStedfesting
}

/**
 * Check if a given object implements the StedfestingListe interface.
 */
export function instanceOfStedfestingListe(
  value: object,
): value is StedfestingListe {
  if (!('innhold' in value) || value['innhold'] === undefined) return false
  return true
}

export function StedfestingListeFromJSON(json: any): StedfestingListe {
  return StedfestingListeFromJSONTyped(json, false)
}

export function StedfestingListeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StedfestingListe {
  if (json == null) {
    return json
  }
  return {
    ...StedfestingFromJSONTyped(json, true),
    maksimaltAntallVerdier:
      json['maksimalt_antall_verdier'] == null
        ? undefined
        : json['maksimalt_antall_verdier'],
    minimaltAntallVerdier:
      json['minimalt_antall_verdier'] == null
        ? undefined
        : json['minimalt_antall_verdier'],
    innhold: EgenskapstypeStedfestingFromJSON(json['innhold']),
  }
}

export function StedfestingListeToJSON(json: any): StedfestingListe {
  return StedfestingListeToJSONTyped(json, false)
}

export function StedfestingListeToJSONTyped(
  value?: StedfestingListe | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    ...StedfestingToJSONTyped(value, true),
    maksimalt_antall_verdier: value['maksimaltAntallVerdier'],
    minimalt_antall_verdier: value['minimaltAntallVerdier'],
    innhold: EgenskapstypeStedfestingToJSON(value['innhold']),
  }
}
