/* tslint:disable */
/* eslint-disable */
/**
 * NVDB Datakatalog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const Viktighet = {
  IkkeSatt: 'IKKE_SATT',
  PkrevdAbsolutt: 'PÅKREVD_ABSOLUTT',
  PkrevdIkkeAbsolutt: 'PÅKREVD_IKKE_ABSOLUTT',
  Betinget: 'BETINGET',
  Opsjonell: 'OPSJONELL',
  MindreViktig: 'MINDRE_VIKTIG',
  Historisk: 'HISTORISK',
} as const
export type Viktighet = (typeof Viktighet)[keyof typeof Viktighet]

export function instanceOfViktighet(value: any): boolean {
  for (const key in Viktighet) {
    if (Object.prototype.hasOwnProperty.call(Viktighet, key)) {
      if (Viktighet[key as keyof typeof Viktighet] === value) {
        return true
      }
    }
  }
  return false
}

export function ViktighetFromJSON(json: any): Viktighet {
  return ViktighetFromJSONTyped(json, false)
}

export function ViktighetFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Viktighet {
  return json as Viktighet
}

export function ViktighetToJSON(value?: Viktighet | null): any {
  return value as any
}

export function ViktighetToJSONTyped(
  value: any,
  ignoreDiscriminator: boolean,
): Viktighet {
  return value as Viktighet
}
