export type { GetEgenskapstypeQueryKey } from './useGetEgenskapstype.ts'
export type { GetEgenskapstypeForVegobjekttypeQueryKey } from './useGetEgenskapstypeForVegobjekttype.ts'
export type { GetEgenskapstypeForVegobjekttypeSuspenseQueryKey } from './useGetEgenskapstypeForVegobjekttypeSuspense.ts'
export type { GetEgenskapstypeKategorierQueryKey } from './useGetEgenskapstypeKategorier.ts'
export type { GetEgenskapstypeKategorierSuspenseQueryKey } from './useGetEgenskapstypeKategorierSuspense.ts'
export type { GetEgenskapstypeSuspenseQueryKey } from './useGetEgenskapstypeSuspense.ts'
export type { GetEnheterQueryKey } from './useGetEnheter.ts'
export type { GetEnheterSuspenseQueryKey } from './useGetEnheterSuspense.ts'
export type { GetKategorierQueryKey } from './useGetKategorier.ts'
export type { GetKategorierSuspenseQueryKey } from './useGetKategorierSuspense.ts'
export type { GetProduktspesifikasjonQueryKey } from './useGetProduktspesifikasjon.ts'
export type { GetProduktspesifikasjonSuspenseQueryKey } from './useGetProduktspesifikasjonSuspense.ts'
export type { GetVegobjekttypeQueryKey } from './useGetVegobjekttype.ts'
export type { GetVegobjekttyperQueryKey } from './useGetVegobjekttyper.ts'
export type { GetVegobjekttyperHistoriskQueryKey } from './useGetVegobjekttyperHistorisk.ts'
export type { GetVegobjekttyperHistoriskSuspenseQueryKey } from './useGetVegobjekttyperHistoriskSuspense.ts'
export type { GetVegobjekttyperSuspenseQueryKey } from './useGetVegobjekttyperSuspense.ts'
export type { GetVegobjekttypeSuspenseQueryKey } from './useGetVegobjekttypeSuspense.ts'
export type { GetVersjonQueryKey } from './useGetVersjon.ts'
export type { GetVersjonSuspenseQueryKey } from './useGetVersjonSuspense.ts'
export { getEgenskapstypeQueryKey } from './useGetEgenskapstype.ts'
export { getEgenskapstype } from './useGetEgenskapstype.ts'
export { getEgenskapstypeQueryOptions } from './useGetEgenskapstype.ts'
export { useGetEgenskapstype } from './useGetEgenskapstype.ts'
export { getEgenskapstypeForVegobjekttypeQueryKey } from './useGetEgenskapstypeForVegobjekttype.ts'
export { getEgenskapstypeForVegobjekttype } from './useGetEgenskapstypeForVegobjekttype.ts'
export { getEgenskapstypeForVegobjekttypeQueryOptions } from './useGetEgenskapstypeForVegobjekttype.ts'
export { useGetEgenskapstypeForVegobjekttype } from './useGetEgenskapstypeForVegobjekttype.ts'
export { getEgenskapstypeForVegobjekttypeSuspenseQueryKey } from './useGetEgenskapstypeForVegobjekttypeSuspense.ts'
export { getEgenskapstypeForVegobjekttypeSuspense } from './useGetEgenskapstypeForVegobjekttypeSuspense.ts'
export { getEgenskapstypeForVegobjekttypeSuspenseQueryOptions } from './useGetEgenskapstypeForVegobjekttypeSuspense.ts'
export { useGetEgenskapstypeForVegobjekttypeSuspense } from './useGetEgenskapstypeForVegobjekttypeSuspense.ts'
export { getEgenskapstypeKategorierQueryKey } from './useGetEgenskapstypeKategorier.ts'
export { getEgenskapstypeKategorier } from './useGetEgenskapstypeKategorier.ts'
export { getEgenskapstypeKategorierQueryOptions } from './useGetEgenskapstypeKategorier.ts'
export { useGetEgenskapstypeKategorier } from './useGetEgenskapstypeKategorier.ts'
export { getEgenskapstypeKategorierSuspenseQueryKey } from './useGetEgenskapstypeKategorierSuspense.ts'
export { getEgenskapstypeKategorierSuspense } from './useGetEgenskapstypeKategorierSuspense.ts'
export { getEgenskapstypeKategorierSuspenseQueryOptions } from './useGetEgenskapstypeKategorierSuspense.ts'
export { useGetEgenskapstypeKategorierSuspense } from './useGetEgenskapstypeKategorierSuspense.ts'
export { getEgenskapstypeSuspenseQueryKey } from './useGetEgenskapstypeSuspense.ts'
export { getEgenskapstypeSuspense } from './useGetEgenskapstypeSuspense.ts'
export { getEgenskapstypeSuspenseQueryOptions } from './useGetEgenskapstypeSuspense.ts'
export { useGetEgenskapstypeSuspense } from './useGetEgenskapstypeSuspense.ts'
export { getEnheterQueryKey } from './useGetEnheter.ts'
export { getEnheter } from './useGetEnheter.ts'
export { getEnheterQueryOptions } from './useGetEnheter.ts'
export { useGetEnheter } from './useGetEnheter.ts'
export { getEnheterSuspenseQueryKey } from './useGetEnheterSuspense.ts'
export { getEnheterSuspense } from './useGetEnheterSuspense.ts'
export { getEnheterSuspenseQueryOptions } from './useGetEnheterSuspense.ts'
export { useGetEnheterSuspense } from './useGetEnheterSuspense.ts'
export { getKategorierQueryKey } from './useGetKategorier.ts'
export { getKategorier } from './useGetKategorier.ts'
export { getKategorierQueryOptions } from './useGetKategorier.ts'
export { useGetKategorier } from './useGetKategorier.ts'
export { getKategorierSuspenseQueryKey } from './useGetKategorierSuspense.ts'
export { getKategorierSuspense } from './useGetKategorierSuspense.ts'
export { getKategorierSuspenseQueryOptions } from './useGetKategorierSuspense.ts'
export { useGetKategorierSuspense } from './useGetKategorierSuspense.ts'
export { getProduktspesifikasjonQueryKey } from './useGetProduktspesifikasjon.ts'
export { getProduktspesifikasjon } from './useGetProduktspesifikasjon.ts'
export { getProduktspesifikasjonQueryOptions } from './useGetProduktspesifikasjon.ts'
export { useGetProduktspesifikasjon } from './useGetProduktspesifikasjon.ts'
export { getProduktspesifikasjonSuspenseQueryKey } from './useGetProduktspesifikasjonSuspense.ts'
export { getProduktspesifikasjonSuspense } from './useGetProduktspesifikasjonSuspense.ts'
export { getProduktspesifikasjonSuspenseQueryOptions } from './useGetProduktspesifikasjonSuspense.ts'
export { useGetProduktspesifikasjonSuspense } from './useGetProduktspesifikasjonSuspense.ts'
export { getVegobjekttypeQueryKey } from './useGetVegobjekttype.ts'
export { getVegobjekttype } from './useGetVegobjekttype.ts'
export { getVegobjekttypeQueryOptions } from './useGetVegobjekttype.ts'
export { useGetVegobjekttype } from './useGetVegobjekttype.ts'
export { getVegobjekttyperQueryKey } from './useGetVegobjekttyper.ts'
export { getVegobjekttyper } from './useGetVegobjekttyper.ts'
export { getVegobjekttyperQueryOptions } from './useGetVegobjekttyper.ts'
export { useGetVegobjekttyper } from './useGetVegobjekttyper.ts'
export { getVegobjekttyperHistoriskQueryKey } from './useGetVegobjekttyperHistorisk.ts'
export { getVegobjekttyperHistorisk } from './useGetVegobjekttyperHistorisk.ts'
export { getVegobjekttyperHistoriskQueryOptions } from './useGetVegobjekttyperHistorisk.ts'
export { useGetVegobjekttyperHistorisk } from './useGetVegobjekttyperHistorisk.ts'
export { getVegobjekttyperHistoriskSuspenseQueryKey } from './useGetVegobjekttyperHistoriskSuspense.ts'
export { getVegobjekttyperHistoriskSuspense } from './useGetVegobjekttyperHistoriskSuspense.ts'
export { getVegobjekttyperHistoriskSuspenseQueryOptions } from './useGetVegobjekttyperHistoriskSuspense.ts'
export { useGetVegobjekttyperHistoriskSuspense } from './useGetVegobjekttyperHistoriskSuspense.ts'
export { getVegobjekttyperSuspenseQueryKey } from './useGetVegobjekttyperSuspense.ts'
export { getVegobjekttyperSuspense } from './useGetVegobjekttyperSuspense.ts'
export { getVegobjekttyperSuspenseQueryOptions } from './useGetVegobjekttyperSuspense.ts'
export { useGetVegobjekttyperSuspense } from './useGetVegobjekttyperSuspense.ts'
export { getVegobjekttypeSuspenseQueryKey } from './useGetVegobjekttypeSuspense.ts'
export { getVegobjekttypeSuspense } from './useGetVegobjekttypeSuspense.ts'
export { getVegobjekttypeSuspenseQueryOptions } from './useGetVegobjekttypeSuspense.ts'
export { useGetVegobjekttypeSuspense } from './useGetVegobjekttypeSuspense.ts'
export { getVersjonQueryKey } from './useGetVersjon.ts'
export { getVersjon } from './useGetVersjon.ts'
export { getVersjonQueryOptions } from './useGetVersjon.ts'
export { useGetVersjon } from './useGetVersjon.ts'
export { getVersjonSuspenseQueryKey } from './useGetVersjonSuspense.ts'
export { getVersjonSuspense } from './useGetVersjonSuspense.ts'
export { getVersjonSuspenseQueryOptions } from './useGetVersjonSuspense.ts'
export { useGetVersjonSuspense } from './useGetVersjonSuspense.ts'
