/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type {
  GetProduktspesifikasjonQueryResponse,
  GetProduktspesifikasjonPathParams,
  GetProduktspesifikasjon404,
  GetProduktspesifikasjon500,
  GetProduktspesifikasjon503,
} from '../models/GetProduktspesifikasjon.ts'
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { getProduktspesifikasjonQueryResponseSchema } from '../schemas/getProduktspesifikasjonSchema.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getProduktspesifikasjonQueryKey = (
  vegobjekttypeid: GetProduktspesifikasjonPathParams['vegobjekttypeid'],
) =>
  [
    {
      url: '/api/v1/vegobjekttyper/:vegobjekttypeid/produktspesifikasjon',
      params: { vegobjekttypeid: vegobjekttypeid },
    },
  ] as const

export type GetProduktspesifikasjonQueryKey = ReturnType<
  typeof getProduktspesifikasjonQueryKey
>

/**
 * @summary Returnerer produktspesifikasjonen til den angitte vegobjekttypen
 * {@link /api/v1/vegobjekttyper/:vegobjekttypeid/produktspesifikasjon}
 */
export async function getProduktspesifikasjon(
  vegobjekttypeid: GetProduktspesifikasjonPathParams['vegobjekttypeid'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetProduktspesifikasjonQueryResponse,
    ResponseErrorConfig<
      | GetProduktspesifikasjon404
      | GetProduktspesifikasjon500
      | GetProduktspesifikasjon503
    >,
    unknown
  >({
    method: 'GET',
    url: `/api/v1/vegobjekttyper/${vegobjekttypeid}/produktspesifikasjon`,
    ...requestConfig,
  })
  return getProduktspesifikasjonQueryResponseSchema.parse(res.data)
}

export function getProduktspesifikasjonQueryOptions(
  vegobjekttypeid: GetProduktspesifikasjonPathParams['vegobjekttypeid'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getProduktspesifikasjonQueryKey(vegobjekttypeid)
  return queryOptions<
    GetProduktspesifikasjonQueryResponse,
    ResponseErrorConfig<
      | GetProduktspesifikasjon404
      | GetProduktspesifikasjon500
      | GetProduktspesifikasjon503
    >,
    GetProduktspesifikasjonQueryResponse,
    typeof queryKey
  >({
    enabled: !!vegobjekttypeid,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getProduktspesifikasjon(vegobjekttypeid, config)
    },
  })
}

/**
 * @summary Returnerer produktspesifikasjonen til den angitte vegobjekttypen
 * {@link /api/v1/vegobjekttyper/:vegobjekttypeid/produktspesifikasjon}
 */
export function useGetProduktspesifikasjon<
  TData = GetProduktspesifikasjonQueryResponse,
  TQueryData = GetProduktspesifikasjonQueryResponse,
  TQueryKey extends QueryKey = GetProduktspesifikasjonQueryKey,
>(
  vegobjekttypeid: GetProduktspesifikasjonPathParams['vegobjekttypeid'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetProduktspesifikasjonQueryResponse,
        ResponseErrorConfig<
          | GetProduktspesifikasjon404
          | GetProduktspesifikasjon500
          | GetProduktspesifikasjon503
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey =
    queryOptions?.queryKey ?? getProduktspesifikasjonQueryKey(vegobjekttypeid)

  const query = useQuery(
    {
      ...getProduktspesifikasjonQueryOptions(vegobjekttypeid, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetProduktspesifikasjon404
      | GetProduktspesifikasjon500
      | GetProduktspesifikasjon503
    >
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
