/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type {
  GetKategorierQueryResponse,
  GetKategorier404,
  GetKategorier500,
  GetKategorier503,
} from '../models/GetKategorier.ts'
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { getKategorierQueryResponseSchema } from '../schemas/getKategorierSchema.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getKategorierQueryKey = () =>
  [{ url: '/api/v1/kategorier' }] as const

export type GetKategorierQueryKey = ReturnType<typeof getKategorierQueryKey>

/**
 * @summary Returnerer alle kategorier for vegobjekter
 * {@link /api/v1/kategorier}
 */
export async function getKategorier(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetKategorierQueryResponse,
    ResponseErrorConfig<GetKategorier404 | GetKategorier500 | GetKategorier503>,
    unknown
  >({ method: 'GET', url: `/api/v1/kategorier`, ...requestConfig })
  return getKategorierQueryResponseSchema.parse(res.data)
}

export function getKategorierQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getKategorierQueryKey()
  return queryOptions<
    GetKategorierQueryResponse,
    ResponseErrorConfig<GetKategorier404 | GetKategorier500 | GetKategorier503>,
    GetKategorierQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getKategorier(config)
    },
  })
}

/**
 * @summary Returnerer alle kategorier for vegobjekter
 * {@link /api/v1/kategorier}
 */
export function useGetKategorier<
  TData = GetKategorierQueryResponse,
  TQueryData = GetKategorierQueryResponse,
  TQueryKey extends QueryKey = GetKategorierQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetKategorierQueryResponse,
        ResponseErrorConfig<
          GetKategorier404 | GetKategorier500 | GetKategorier503
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getKategorierQueryKey()

  const query = useQuery(
    {
      ...getKategorierQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetKategorier404 | GetKategorier500 | GetKategorier503>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
