/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type {
  GetEgenskapstypeQueryResponse,
  GetEgenskapstypePathParams,
  GetEgenskapstype404,
  GetEgenskapstype500,
  GetEgenskapstype503,
} from '../models/GetEgenskapstype.ts'
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { getEgenskapstypeQueryResponseSchema } from '../schemas/getEgenskapstypeSchema.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getEgenskapstypeQueryKey = (
  egenskapstypeid: GetEgenskapstypePathParams['egenskapstypeid'],
) =>
  [
    {
      url: '/api/v1/egenskapstyper/:egenskapstypeid',
      params: { egenskapstypeid: egenskapstypeid },
    },
  ] as const

export type GetEgenskapstypeQueryKey = ReturnType<
  typeof getEgenskapstypeQueryKey
>

/**
 * @summary Returnerer angitt egenskapstype
 * {@link /api/v1/egenskapstyper/:egenskapstypeid}
 */
export async function getEgenskapstype(
  egenskapstypeid: GetEgenskapstypePathParams['egenskapstypeid'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetEgenskapstypeQueryResponse,
    ResponseErrorConfig<
      GetEgenskapstype404 | GetEgenskapstype500 | GetEgenskapstype503
    >,
    unknown
  >({
    method: 'GET',
    url: `/api/v1/egenskapstyper/${egenskapstypeid}`,
    ...requestConfig,
  })
  return getEgenskapstypeQueryResponseSchema.parse(res.data)
}

export function getEgenskapstypeQueryOptions(
  egenskapstypeid: GetEgenskapstypePathParams['egenskapstypeid'],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getEgenskapstypeQueryKey(egenskapstypeid)
  return queryOptions<
    GetEgenskapstypeQueryResponse,
    ResponseErrorConfig<
      GetEgenskapstype404 | GetEgenskapstype500 | GetEgenskapstype503
    >,
    GetEgenskapstypeQueryResponse,
    typeof queryKey
  >({
    enabled: !!egenskapstypeid,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getEgenskapstype(egenskapstypeid, config)
    },
  })
}

/**
 * @summary Returnerer angitt egenskapstype
 * {@link /api/v1/egenskapstyper/:egenskapstypeid}
 */
export function useGetEgenskapstype<
  TData = GetEgenskapstypeQueryResponse,
  TQueryData = GetEgenskapstypeQueryResponse,
  TQueryKey extends QueryKey = GetEgenskapstypeQueryKey,
>(
  egenskapstypeid: GetEgenskapstypePathParams['egenskapstypeid'],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetEgenskapstypeQueryResponse,
        ResponseErrorConfig<
          GetEgenskapstype404 | GetEgenskapstype500 | GetEgenskapstype503
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey =
    queryOptions?.queryKey ?? getEgenskapstypeQueryKey(egenskapstypeid)

  const query = useQuery(
    {
      ...getEgenskapstypeQueryOptions(egenskapstypeid, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      GetEgenskapstype404 | GetEgenskapstype500 | GetEgenskapstype503
    >
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
