/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type {
  GetVegobjekttypeQueryResponse,
  GetVegobjekttypePathParams,
  GetVegobjekttypeQueryParams,
  GetVegobjekttype404,
  GetVegobjekttype500,
  GetVegobjekttype503,
} from '../models/GetVegobjekttype.ts'
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import { getVegobjekttypeQueryResponseSchema } from '../schemas/getVegobjekttypeSchema.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getVegobjekttypeSuspenseQueryKey = (
  vegobjekttypeid: GetVegobjekttypePathParams['vegobjekttypeid'],
  params: GetVegobjekttypeQueryParams = {},
) =>
  [
    {
      url: '/api/v1/vegobjekttyper/:vegobjekttypeid',
      params: { vegobjekttypeid: vegobjekttypeid },
    },
    ...(params ? [params] : []),
  ] as const

export type GetVegobjekttypeSuspenseQueryKey = ReturnType<
  typeof getVegobjekttypeSuspenseQueryKey
>

/**
 * @summary Returnerer angitt vegobjekttype
 * {@link /api/v1/vegobjekttyper/:vegobjekttypeid}
 */
export async function getVegobjekttypeSuspense(
  vegobjekttypeid: GetVegobjekttypePathParams['vegobjekttypeid'],
  params?: GetVegobjekttypeQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetVegobjekttypeQueryResponse,
    ResponseErrorConfig<
      GetVegobjekttype404 | GetVegobjekttype500 | GetVegobjekttype503
    >,
    unknown
  >({
    method: 'GET',
    url: `/api/v1/vegobjekttyper/${vegobjekttypeid}`,
    params,
    ...requestConfig,
  })
  return getVegobjekttypeQueryResponseSchema.parse(res.data)
}

export function getVegobjekttypeSuspenseQueryOptions(
  vegobjekttypeid: GetVegobjekttypePathParams['vegobjekttypeid'],
  params?: GetVegobjekttypeQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getVegobjekttypeSuspenseQueryKey(vegobjekttypeid, params)
  return queryOptions<
    GetVegobjekttypeQueryResponse,
    ResponseErrorConfig<
      GetVegobjekttype404 | GetVegobjekttype500 | GetVegobjekttype503
    >,
    GetVegobjekttypeQueryResponse,
    typeof queryKey
  >({
    enabled: !!vegobjekttypeid,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getVegobjekttypeSuspense(vegobjekttypeid, params, config)
    },
  })
}

/**
 * @summary Returnerer angitt vegobjekttype
 * {@link /api/v1/vegobjekttyper/:vegobjekttypeid}
 */
export function useGetVegobjekttypeSuspense<
  TData = GetVegobjekttypeQueryResponse,
  TQueryKey extends QueryKey = GetVegobjekttypeSuspenseQueryKey,
>(
  vegobjekttypeid: GetVegobjekttypePathParams['vegobjekttypeid'],
  params?: GetVegobjekttypeQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetVegobjekttypeQueryResponse,
        ResponseErrorConfig<
          GetVegobjekttype404 | GetVegobjekttype500 | GetVegobjekttype503
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey =
    queryOptions?.queryKey ??
    getVegobjekttypeSuspenseQueryKey(vegobjekttypeid, params)

  const query = useSuspenseQuery(
    {
      ...getVegobjekttypeSuspenseQueryOptions(vegobjekttypeid, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      GetVegobjekttype404 | GetVegobjekttype500 | GetVegobjekttype503
    >
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
