/*
 * NVDB Datakatalog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package no.vegvesen.vt.nvdb.datakatalog.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import no.vegvesen.vt.nvdb.datakatalog.model.AssosiasjonstypeListeInnhold;
import no.vegvesen.vt.nvdb.datakatalog.model.AssosiasjonstypeVegobjekttype;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Assosiasjonstype
 */
@JsonPropertyOrder({
  Assosiasjonstype.JSON_PROPERTY_ID,
  Assosiasjonstype.JSON_PROPERTY_NAVN,
  Assosiasjonstype.JSON_PROPERTY_EGENSKAPSTYPE,
  Assosiasjonstype.JSON_PROPERTY_MAKSIMALT_ANTALL_VERDIER,
  Assosiasjonstype.JSON_PROPERTY_MINIMALT_ANTALL_VERDIER,
  Assosiasjonstype.JSON_PROPERTY_INNHOLD,
  Assosiasjonstype.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class Assosiasjonstype {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private Integer id;

  public static final String JSON_PROPERTY_NAVN = "navn";
  @jakarta.annotation.Nullable
  private String navn;

  public static final String JSON_PROPERTY_EGENSKAPSTYPE = "egenskapstype";
  @jakarta.annotation.Nonnull
  private String egenskapstype;

  public static final String JSON_PROPERTY_MAKSIMALT_ANTALL_VERDIER = "maksimalt_antall_verdier";
  @jakarta.annotation.Nullable
  private Integer maksimaltAntallVerdier;

  public static final String JSON_PROPERTY_MINIMALT_ANTALL_VERDIER = "minimalt_antall_verdier";
  @jakarta.annotation.Nullable
  private Integer minimaltAntallVerdier;

  public static final String JSON_PROPERTY_INNHOLD = "innhold";
  @jakarta.annotation.Nullable
  private AssosiasjonstypeListeInnhold innhold;

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nullable
  private AssosiasjonstypeVegobjekttype type;

  public Assosiasjonstype() {
  }

  public Assosiasjonstype id(@jakarta.annotation.Nonnull Integer id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull Integer id) {
    this.id = id;
  }

  public Assosiasjonstype navn(@jakarta.annotation.Nullable String navn) {
    
    this.navn = navn;
    return this;
  }

  /**
   * Get navn
   * @return navn
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAVN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNavn() {
    return navn;
  }


  @JsonProperty(JSON_PROPERTY_NAVN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNavn(@jakarta.annotation.Nullable String navn) {
    this.navn = navn;
  }

  public Assosiasjonstype egenskapstype(@jakarta.annotation.Nonnull String egenskapstype) {
    
    this.egenskapstype = egenskapstype;
    return this;
  }

  /**
   * Get egenskapstype
   * @return egenskapstype
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EGENSKAPSTYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEgenskapstype() {
    return egenskapstype;
  }


  @JsonProperty(JSON_PROPERTY_EGENSKAPSTYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEgenskapstype(@jakarta.annotation.Nonnull String egenskapstype) {
    this.egenskapstype = egenskapstype;
  }

  public Assosiasjonstype maksimaltAntallVerdier(@jakarta.annotation.Nullable Integer maksimaltAntallVerdier) {
    
    this.maksimaltAntallVerdier = maksimaltAntallVerdier;
    return this;
  }

  /**
   * Get maksimaltAntallVerdier
   * @return maksimaltAntallVerdier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAKSIMALT_ANTALL_VERDIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMaksimaltAntallVerdier() {
    return maksimaltAntallVerdier;
  }


  @JsonProperty(JSON_PROPERTY_MAKSIMALT_ANTALL_VERDIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaksimaltAntallVerdier(@jakarta.annotation.Nullable Integer maksimaltAntallVerdier) {
    this.maksimaltAntallVerdier = maksimaltAntallVerdier;
  }

  public Assosiasjonstype minimaltAntallVerdier(@jakarta.annotation.Nullable Integer minimaltAntallVerdier) {
    
    this.minimaltAntallVerdier = minimaltAntallVerdier;
    return this;
  }

  /**
   * Get minimaltAntallVerdier
   * @return minimaltAntallVerdier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MINIMALT_ANTALL_VERDIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMinimaltAntallVerdier() {
    return minimaltAntallVerdier;
  }


  @JsonProperty(JSON_PROPERTY_MINIMALT_ANTALL_VERDIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinimaltAntallVerdier(@jakarta.annotation.Nullable Integer minimaltAntallVerdier) {
    this.minimaltAntallVerdier = minimaltAntallVerdier;
  }

  public Assosiasjonstype innhold(@jakarta.annotation.Nullable AssosiasjonstypeListeInnhold innhold) {
    
    this.innhold = innhold;
    return this;
  }

  /**
   * Get innhold
   * @return innhold
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INNHOLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AssosiasjonstypeListeInnhold getInnhold() {
    return innhold;
  }


  @JsonProperty(JSON_PROPERTY_INNHOLD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInnhold(@jakarta.annotation.Nullable AssosiasjonstypeListeInnhold innhold) {
    this.innhold = innhold;
  }

  public Assosiasjonstype type(@jakarta.annotation.Nullable AssosiasjonstypeVegobjekttype type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AssosiasjonstypeVegobjekttype getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(@jakarta.annotation.Nullable AssosiasjonstypeVegobjekttype type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Assosiasjonstype assosiasjonstype = (Assosiasjonstype) o;
    return Objects.equals(this.id, assosiasjonstype.id) &&
        Objects.equals(this.navn, assosiasjonstype.navn) &&
        Objects.equals(this.egenskapstype, assosiasjonstype.egenskapstype) &&
        Objects.equals(this.maksimaltAntallVerdier, assosiasjonstype.maksimaltAntallVerdier) &&
        Objects.equals(this.minimaltAntallVerdier, assosiasjonstype.minimaltAntallVerdier) &&
        Objects.equals(this.innhold, assosiasjonstype.innhold) &&
        Objects.equals(this.type, assosiasjonstype.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, navn, egenskapstype, maksimaltAntallVerdier, minimaltAntallVerdier, innhold, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Assosiasjonstype {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    navn: ").append(toIndentedString(navn)).append("\n");
    sb.append("    egenskapstype: ").append(toIndentedString(egenskapstype)).append("\n");
    sb.append("    maksimaltAntallVerdier: ").append(toIndentedString(maksimaltAntallVerdier)).append("\n");
    sb.append("    minimaltAntallVerdier: ").append(toIndentedString(minimaltAntallVerdier)).append("\n");
    sb.append("    innhold: ").append(toIndentedString(innhold)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

