export * from './useGetVegobjektById'
export * from './useGetVegobjektByTypeAndId'
export * from './useGetVegobjektByTypeIdAndVersjon'
export * from './useGetVegobjektNotifikasjoner'
export * from './useGetVegobjektVersjoner'
export * from './useGetVegobjekterByType'
