export * from './useGetVegobjektById'
export * from './useGetVegobjektByTypeAndId'
export * from './useGetVegobjektByTypeIdAndVersjon'
export * from './useGetVegobjektEndringerForType'
export * from './useGetVegobjektVersjoner'
export * from './useGetVegobjekterByType'
