/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type {
  GetVegobjektVersjonerQueryResponse,
  GetVegobjektVersjonerPathParams,
  GetVegobjektVersjonerQueryParams,
  GetVegobjektVersjoner400,
  GetVegobjektVersjoner401,
  GetVegobjektVersjoner403,
  GetVegobjektVersjoner404,
  GetVegobjektVersjoner500,
} from '../models/GetVegobjektVersjoner.ts'
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import { getVegobjektVersjonerQueryResponseSchema } from '../schemas/getVegobjektVersjonerSchema.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getVegobjektVersjonerSuspenseQueryKey = (
  vegobjekttypeId: GetVegobjektVersjonerPathParams['vegobjekttypeId'],
  vegobjektId: GetVegobjektVersjonerPathParams['vegobjektId'],
  params: GetVegobjektVersjonerQueryParams = {},
) =>
  [
    {
      url: '/api/v4/vegobjekter/:vegobjekttypeId/:vegobjektId/versjoner',
      params: { vegobjekttypeId: vegobjekttypeId, vegobjektId: vegobjektId },
    },
    ...(params ? [params] : []),
  ] as const

export type GetVegobjektVersjonerSuspenseQueryKey = ReturnType<
  typeof getVegobjektVersjonerSuspenseQueryKey
>

/**
 * @summary Hent alle versjoner av et vegobjekt
 * {@link /api/v4/vegobjekter/:vegobjekttypeId/:vegobjektId/versjoner}
 */
export async function getVegobjektVersjonerSuspense(
  vegobjekttypeId: GetVegobjektVersjonerPathParams['vegobjekttypeId'],
  vegobjektId: GetVegobjektVersjonerPathParams['vegobjektId'],
  params?: GetVegobjektVersjonerQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetVegobjektVersjonerQueryResponse,
    ResponseErrorConfig<
      | GetVegobjektVersjoner400
      | GetVegobjektVersjoner401
      | GetVegobjektVersjoner403
      | GetVegobjektVersjoner404
      | GetVegobjektVersjoner500
    >,
    unknown
  >({
    method: 'GET',
    url: `/api/v4/vegobjekter/${vegobjekttypeId}/${vegobjektId}/versjoner`,
    params,
    ...requestConfig,
  })
  return getVegobjektVersjonerQueryResponseSchema.parse(res.data)
}

export function getVegobjektVersjonerSuspenseQueryOptions(
  vegobjekttypeId: GetVegobjektVersjonerPathParams['vegobjekttypeId'],
  vegobjektId: GetVegobjektVersjonerPathParams['vegobjektId'],
  params?: GetVegobjektVersjonerQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getVegobjektVersjonerSuspenseQueryKey(
    vegobjekttypeId,
    vegobjektId,
    params,
  )
  return queryOptions<
    GetVegobjektVersjonerQueryResponse,
    ResponseErrorConfig<
      | GetVegobjektVersjoner400
      | GetVegobjektVersjoner401
      | GetVegobjektVersjoner403
      | GetVegobjektVersjoner404
      | GetVegobjektVersjoner500
    >,
    GetVegobjektVersjonerQueryResponse,
    typeof queryKey
  >({
    enabled: !!(vegobjekttypeId && vegobjektId),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getVegobjektVersjonerSuspense(
        vegobjekttypeId,
        vegobjektId,
        params,
        config,
      )
    },
  })
}

/**
 * @summary Hent alle versjoner av et vegobjekt
 * {@link /api/v4/vegobjekter/:vegobjekttypeId/:vegobjektId/versjoner}
 */
export function useGetVegobjektVersjonerSuspense<
  TData = GetVegobjektVersjonerQueryResponse,
  TQueryKey extends QueryKey = GetVegobjektVersjonerSuspenseQueryKey,
>(
  vegobjekttypeId: GetVegobjektVersjonerPathParams['vegobjekttypeId'],
  vegobjektId: GetVegobjektVersjonerPathParams['vegobjektId'],
  params?: GetVegobjektVersjonerQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetVegobjektVersjonerQueryResponse,
        ResponseErrorConfig<
          | GetVegobjektVersjoner400
          | GetVegobjektVersjoner401
          | GetVegobjektVersjoner403
          | GetVegobjektVersjoner404
          | GetVegobjektVersjoner500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey =
    queryOptions?.queryKey ??
    getVegobjektVersjonerSuspenseQueryKey(vegobjekttypeId, vegobjektId, params)

  const query = useSuspenseQuery(
    {
      ...getVegobjektVersjonerSuspenseQueryOptions(
        vegobjekttypeId,
        vegobjektId,
        params,
        config,
      ),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetVegobjektVersjoner400
      | GetVegobjektVersjoner401
      | GetVegobjektVersjoner403
      | GetVegobjektVersjoner404
      | GetVegobjektVersjoner500
    >
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
