/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@kubb/plugin-client/clients/axios'
import type {
  GetVegobjektByTypeIdAndVersjonQueryResponse,
  GetVegobjektByTypeIdAndVersjonPathParams,
  GetVegobjektByTypeIdAndVersjonQueryParams,
  GetVegobjektByTypeIdAndVersjon400,
  GetVegobjektByTypeIdAndVersjon401,
  GetVegobjektByTypeIdAndVersjon403,
  GetVegobjektByTypeIdAndVersjon404,
  GetVegobjektByTypeIdAndVersjon500,
} from '../models/GetVegobjektByTypeIdAndVersjon.ts'
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import { getVegobjektByTypeIdAndVersjonQueryResponseSchema } from '../schemas/getVegobjektByTypeIdAndVersjonSchema.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getVegobjektByTypeIdAndVersjonSuspenseQueryKey = (
  vegobjekttypeId: GetVegobjektByTypeIdAndVersjonPathParams['vegobjekttypeId'],
  vegobjektId: GetVegobjektByTypeIdAndVersjonPathParams['vegobjektId'],
  versjon: GetVegobjektByTypeIdAndVersjonPathParams['versjon'],
  params: GetVegobjektByTypeIdAndVersjonQueryParams = {},
) =>
  [
    {
      url: '/api/v4/vegobjekter/:vegobjekttypeId/:vegobjektId/:versjon',
      params: {
        vegobjekttypeId: vegobjekttypeId,
        vegobjektId: vegobjektId,
        versjon: versjon,
      },
    },
    ...(params ? [params] : []),
  ] as const

export type GetVegobjektByTypeIdAndVersjonSuspenseQueryKey = ReturnType<
  typeof getVegobjektByTypeIdAndVersjonSuspenseQueryKey
>

/**
 * @summary Hent spesifikk versjon av et vegobjekt
 * {@link /api/v4/vegobjekter/:vegobjekttypeId/:vegobjektId/:versjon}
 */
export async function getVegobjektByTypeIdAndVersjonSuspense(
  vegobjekttypeId: GetVegobjektByTypeIdAndVersjonPathParams['vegobjekttypeId'],
  vegobjektId: GetVegobjektByTypeIdAndVersjonPathParams['vegobjektId'],
  versjon: GetVegobjektByTypeIdAndVersjonPathParams['versjon'],
  params?: GetVegobjektByTypeIdAndVersjonQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetVegobjektByTypeIdAndVersjonQueryResponse,
    ResponseErrorConfig<
      | GetVegobjektByTypeIdAndVersjon400
      | GetVegobjektByTypeIdAndVersjon401
      | GetVegobjektByTypeIdAndVersjon403
      | GetVegobjektByTypeIdAndVersjon404
      | GetVegobjektByTypeIdAndVersjon500
    >,
    unknown
  >({
    method: 'GET',
    url: `/api/v4/vegobjekter/${vegobjekttypeId}/${vegobjektId}/${versjon}`,
    params,
    ...requestConfig,
  })
  return getVegobjektByTypeIdAndVersjonQueryResponseSchema.parse(res.data)
}

export function getVegobjektByTypeIdAndVersjonSuspenseQueryOptions(
  vegobjekttypeId: GetVegobjektByTypeIdAndVersjonPathParams['vegobjekttypeId'],
  vegobjektId: GetVegobjektByTypeIdAndVersjonPathParams['vegobjektId'],
  versjon: GetVegobjektByTypeIdAndVersjonPathParams['versjon'],
  params?: GetVegobjektByTypeIdAndVersjonQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getVegobjektByTypeIdAndVersjonSuspenseQueryKey(
    vegobjekttypeId,
    vegobjektId,
    versjon,
    params,
  )
  return queryOptions<
    GetVegobjektByTypeIdAndVersjonQueryResponse,
    ResponseErrorConfig<
      | GetVegobjektByTypeIdAndVersjon400
      | GetVegobjektByTypeIdAndVersjon401
      | GetVegobjektByTypeIdAndVersjon403
      | GetVegobjektByTypeIdAndVersjon404
      | GetVegobjektByTypeIdAndVersjon500
    >,
    GetVegobjektByTypeIdAndVersjonQueryResponse,
    typeof queryKey
  >({
    enabled: !!(vegobjekttypeId && vegobjektId && versjon),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getVegobjektByTypeIdAndVersjonSuspense(
        vegobjekttypeId,
        vegobjektId,
        versjon,
        params,
        config,
      )
    },
  })
}

/**
 * @summary Hent spesifikk versjon av et vegobjekt
 * {@link /api/v4/vegobjekter/:vegobjekttypeId/:vegobjektId/:versjon}
 */
export function useGetVegobjektByTypeIdAndVersjonSuspense<
  TData = GetVegobjektByTypeIdAndVersjonQueryResponse,
  TQueryKey extends QueryKey = GetVegobjektByTypeIdAndVersjonSuspenseQueryKey,
>(
  vegobjekttypeId: GetVegobjektByTypeIdAndVersjonPathParams['vegobjekttypeId'],
  vegobjektId: GetVegobjektByTypeIdAndVersjonPathParams['vegobjektId'],
  versjon: GetVegobjektByTypeIdAndVersjonPathParams['versjon'],
  params?: GetVegobjektByTypeIdAndVersjonQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetVegobjektByTypeIdAndVersjonQueryResponse,
        ResponseErrorConfig<
          | GetVegobjektByTypeIdAndVersjon400
          | GetVegobjektByTypeIdAndVersjon401
          | GetVegobjektByTypeIdAndVersjon403
          | GetVegobjektByTypeIdAndVersjon404
          | GetVegobjektByTypeIdAndVersjon500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey =
    queryOptions?.queryKey ??
    getVegobjektByTypeIdAndVersjonSuspenseQueryKey(
      vegobjekttypeId,
      vegobjektId,
      versjon,
      params,
    )

  const query = useSuspenseQuery(
    {
      ...getVegobjektByTypeIdAndVersjonSuspenseQueryOptions(
        vegobjekttypeId,
        vegobjektId,
        versjon,
        params,
        config,
      ),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetVegobjektByTypeIdAndVersjon400
      | GetVegobjektByTypeIdAndVersjon401
      | GetVegobjektByTypeIdAndVersjon403
      | GetVegobjektByTypeIdAndVersjon404
      | GetVegobjektByTypeIdAndVersjon500
    >
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
